### ISSUE TITLE
Impact section cards not same height

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1009]
# Description
Cards on impact section are not the same height on mobile, see the screenshot below:
 Tested on chrome simulator: Galaxy S8+ 360x740

![image](https://user-images.githubusercontent.com/31519867/192137773-c990f449-a832-4ec7-8c02-b64f6bf3c30a.png)

## To reproduce
- visit: http://localhost:3000/wallets/eecdf253-05b6-419a-8425-416a3e5fc9a0

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by khalatevarun** [comment]
Please revewi the following PR, have tried fixing the issue  @RubenSmn  @dadiorchen 
https://github.com/Greenstand/treetracker-web-map-client/pull/1030

**Comment by RubenSmn** [comment]
Fixed by #1012
