### ISSUE TITLE
The menu/navigation bar

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#101]
This is a common component.

<img width="942" alt="Screen Shot 2021-09-10 at 3 14 17 PM" src="https://user-images.githubusercontent.com/5744708/132814964-294af662-7657-4629-806c-652af8b0d544.png">

---
Some hints for building components:

* Please check the pin items in the `web map` channel on slack to get the design resource.
* A tutorial of how to use the Cypress component tool to build components: 
  https://github.com/Greenstand/treetracker-wallet-web#how-to-build-a-component
* We are using MaterialUI to build the app: https://material-ui.com/
* When you are ready to raise PR for the component, please attach the screenshot of the component for review.

**Comment by dadiorchen** [comment]
Prerequisite #100

**Comment by cpaule1811** [comment]
Should Navbar also have hamburger menu button or dropdown for when the screen is small?
