### ISSUE TITLE
Featured Tree cards not same height

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1010]
# Description
The height of the tree card is not the same if the text on 1 card is longer than the others, see screenshot below.
The long names do not occur on the dev environment by default (you could mock for easy testing)

Mobile|Desktop
:-:|:-:
![image](https://user-images.githubusercontent.com/31519867/192138443-058587ee-b61f-469d-9850-b8efbc9207bd.png)|![image](https://user-images.githubusercontent.com/31519867/192138406-1de86b7d-de5f-48ed-968d-444dbf4baaaf.png)

## To reproduce
- run `npm run build-and-start`
- visit: http://localhost:3000/web-map-beta/demo/organizations/775

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by khalatevarun** [comment]
Would like to pick this issue

**Comment by khalatevarun** [comment]
PR is ready @RubenSmn , could you please send an invite to join the repo. Dont have access currently to push.

**Comment by RubenSmn** [comment]
Sorry @khalatevarun I don't see your pull request. Here is a quick guide on how to create one: https://www.dataschool.io/how-to-contribute-on-github/

**Comment by khalatevarun** [comment]
![SCR-20220927-ia3](https://user-images.githubusercontent.com/68511458/192464212-f270f4e0-f5c9-47eb-a582-0d033f729419.png)
Not able to create PR

**Comment by khalatevarun** [comment]
@RubenSmn the PR is ready.

**Comment by dadiorchen** [comment]
Because this problem has been solved by someone else, I will close this PR.
