### ISSUE TITLE
Navigating to another page does not place you at the top of that page

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1011]
# Description
When navigating to another page you do not start at the top of the new page, see the video below for a visual explanation.

[Kooha-2022-09-25-12:22:38.webm](https://user-images.githubusercontent.com/31519867/192138932-c846b449-29af-4d94-8984-882d7fe05b5b.webm)

## To reproduce
- visit: http://localhost:3000/planters/940
- scroll down to the tree section and click a tree

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
I think we still have this problem, on top page, click any planter listed, the page is not topped.

**Comment by dadiorchen** [comment]
@RubenSmn @Mohmn @khalatevarun any clues on this? I have released the newest code

**Comment by RubenSmn** [comment]
Yes we have not merged #1185 which will fix this problem

**Comment by dadiorchen** [comment]
Oh, my fault
