### ISSUE TITLE
Wrong layout for the card button

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1032]
https://prod-k8s.treetracker.org/web-map-beta/demo/planters/3350/trees/496170

![Image](https://user-images.githubusercontent.com/5744708/193157928-431853e5-38f8-4d9d-9b2a-8018bb09a742.png)

**Comment by dadiorchen** [comment]
The local/development version is correct



![Image](https://user-images.githubusercontent.com/5744708/193158092-9b4cc3d4-d23a-4872-afb1-53730f00aa0c.png)

**Comment by dharmiknotop** [comment]
Hey, I am interested in this issue can i solve this?

**Comment by RubenSmn** [comment]
@dharmiknotop go ahead!
PS: local/dev version also seems to be broken: http://localhost:3000/planters/5449/trees/953049

![image](https://user-images.githubusercontent.com/31519867/193245375-a6ce8ef5-ad95-43ae-acf4-d722240f8bc3.png)

**Comment by dharmiknotop** [comment]
hey @RubenSmn, can you pls explain how can i write my commit message for this because i trying to write added width 100% to the card button but it gives error says to follow https://github.com/conventional-changelog/commitlint/#what-is-commitlint and when i saw this i didn't understand what to write so yea can you pls help me .

**Comment by RubenSmn** [comment]
Hi @dharmiknotop ah yes we use a format for the way we write our commit message.
For example if our change result in a fix we would commit like `git commit -m "fix: xxx element was using correct xxx"`

If you want more information, I personally found this article very helpfull! https://h.daily-dev-tips.com/git-basics-conventional-commits

**Comment by dharmiknotop** [comment]
@RubenSmn made a pr pls checkout and sorry for asking but should one tag the assigner after one makes a pr or the assigner just checks on the regular base and no need to tag them after making a pr?

**Comment by RubenSmn** [comment]
@dharmiknotop the PR's are getting checked on a regular base so no need for a tag

**Comment by RubenSmn** [comment]
Solved with #1044
