### ISSUE TITLE
Missing logo on this case

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1036]
https://prod-k8s.treetracker.org/web-map-beta/demo/organizations/194/trees/785659

The logo for the org is missing on the first card 

![Image](https://user-images.githubusercontent.com/5744708/193167389-75dac661-c2f5-40c9-ae47-7d414c057d13.png)

**Comment by mohuxaiphasalik** [comment]
I have found the logo of Haiti tree project i can add logo of it ,
Please assign me this project so that I could get started.

**Comment by RubenSmn** [comment]
The logo of the organization is visible in the Breadcrumbs! @mohuxaiphasalik you can create a fork and open a pull request when you had any luck fixing the issue! Here is a good tutorial on how to if its your first time https://www.dataschool.io/how-to-contribute-on-github/

**Comment by Harshalyadav** [comment]
can you give me more about this issue?
I mean organization logo or plant logo.
Where I put this logo or if you have this logo where I get?

**Comment by RubenSmn** [comment]
@Harshalyadav the logo url is on the planter object passed down as argument: https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/pages/trees/%5Btreeid%5D.js#L54

And is already being used here: https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/pages/trees/%5Btreeid%5D.js#L328

**Comment by RubenSmn** [comment]
@Harshalyadav the logo/image is on the organization object passed as argument: https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/pages/trees/%5Btreeid%5D.js#L55

And can be used in the same way as here: https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/pages/organizations/%5Borganizationid%5D.js#L141
