### ISSUE TITLE
Display progress block when loading new page

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1039]
As the video showing, it is a bit confusing for user when we click next tree,  the old id and picture is still there and replaced by new ones when loaded, we should remove old content and replace with loading block (like this https://mui.com/material-ui/react-skeleton/#main-content) and display new content when ready.

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-09-30%20at%205.51.34%20PM.mp4?

Note, this issue is related to #976

**Comment by andrewsu31098** [comment]
Hi, I would like to tackle this issue. Think I can finish it within 1-3 days from now.

**Comment by dadiorchen** [comment]
@andrewsu31098 this is an invalid issue for now, so could you please take another one? Sorry for the confusion!
