### ISSUE TITLE
Information card 1

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#104]
Please put the component into the common folder, and make it reusable.

<img width="710" alt="Screen Shot 2021-09-10 at 3 32 37 PM" src="https://user-images.githubusercontent.com/5744708/132817504-8e904512-71af-41f5-b12b-7ff3d3fe0a66.png">

---
Some hints for building components:

* The Figma design resource: https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=2497%3A11584.
* A tutorial of how to use the Cypress component tool to build components: 
  https://github.com/Greenstand/treetracker-wallet-web#how-to-build-a-component
* We are using MaterialUI to build the app: https://material-ui.com/
* When you are ready to raise PR for the component, please attach the screenshot of the component for review.

**Comment by cpaule1811** [comment]
Hello, 

May I please be assigned this issue?

**Comment by dadiorchen** [comment]
Hi, @cpaule1811 sure, please :)

**Comment by dadiorchen** [comment]
And if you are interested to join our community, please leave you email here then I will send you a slack invitation :) we are a global team and targeted to solve the climate change and poverty problem

**Comment by cpaule1811** [comment]
Hi @dadiorchen , 

thank you I have raised the pr. That would be great. My email is charles.edwards1811@gmail.com
