### ISSUE TITLE
Can not drag draw anymore on mobile

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1046]
http://localhost:3000/trees/854318

![Image](https://user-images.githubusercontent.com/5744708/193379059-9750af43-f774-467e-8dfb-6ab3930d9533.png)

**Comment by dadiorchen** [comment]
But this is not always the case, sometime the drawer is just okay, don't know what operations cause this.

**Comment by RubenSmn** [comment]
I tested this on the Chrome simulator, visited: http://localhost:3000/trees/854318 and everything works as expected. I can drag the drawer before and after I switch trees. By clicking on the tree itself or the next/prev buttons

**Comment by dadiorchen** [comment]
That's weird, maybe my browser chrome has some problem
