### ISSUE TITLE
Information card 2

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#105]
Please put this component in the `common` folder and make this component reusable.

<img width="701" alt="Screen Shot 2021-09-10 at 3 36 52 PM" src="https://user-images.githubusercontent.com/5744708/132817871-d91deb31-9d2c-40db-bfd8-cb10ba454231.png">

---
Some hints for building components:

* Please check the pin items in the `web map` channel on slack to get the design resource.
* A tutorial of how to use the Cypress component tool to build components: 
  https://github.com/Greenstand/treetracker-wallet-web#how-to-build-a-component
* We are using MaterialUI to build the app: https://material-ui.com/
* When you are ready to raise PR for the component, please attach the screenshot of the component for review.

**Comment by gauraws** [comment]
Hi @dadiorchen Can I take this task please?

**Comment by dadiorchen** [comment]
Sure! Thanks! @gauraws and you can check the readme and our engineering book: https://greenstand.gitbook.io/engineering/ there are some reminders for development.

**Comment by gauraws** [comment]
Thanks @dadiorchen, I will start my work on it. Is there any mockup or UI template which I can use to create component? or how the component should look like? Please guide

**Comment by gauraws** [comment]
Hello, it seems I am unable to run the project as I am working behind corporate firewall, some of module is not whitelisted. Thank you

**Comment by dadiorchen** [comment]
Hi, here is our UI, and the readme also has some other useful info.
https://github.com/Greenstand/treetracker-web-map-client#ui-design-resource

**Comment by dadiorchen** [comment]
What can I help on the network problem? Actually once you install all those npm module, you don't need outward connection to internet.

**Comment by mrtillman** [comment]
@gauraws - hey Guarav are you still working on this?

**Comment by mrtillman** [comment]
@dadiorchen - let's see what @gauraws says, but if he is still blocked by the network issue, then I could work on this one.

**Comment by gauraws** [comment]
Hi, I could not work on this as I am not able to download required modules due to corporate firewall. I apologies for not informing earlier

**Comment by mrtillman** [comment]
@gauraws - ok, no problem. I'll see if I can make any progress on this task.

**Comment by mrtillman** [comment]
https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=1830%3A471

**Comment by mrtillman** [comment]
> When you are ready to raise PR for the component, please attach the screenshot of the component for review.

`src/common/TreeAge.js`

<img src="https://truthful-arithmetic.surge.sh/tree-age-component.png" width=300 />
