### ISSUE TITLE
The forward and back buttons on the tree slider / sliders are hard to see.

### ISSUE THREAD

**Issue by jeremydthomas** [Greenstand/treetracker-web-map-client#1057]
As you can see in the picture there is an arrow forward, and when you go forward there is an arrow that goes backwards that is not in the picture. If I didnt know that was there, I dont think I would see it, so I doubt website visitors would see it either. 

Try to make this more visible so that the visitors know its there.

![Inkedimage](https://user-images.githubusercontent.com/63400531/193934987-212c2f8f-4bd4-43aa-9a1b-bf9699f8dd35.jpg)

**Comment by RubenSmn** [comment]
To add to this: when hovering over the button; the button gets even darker. I think we should make the button more light / less transparent when hovering.
