### ISSUE TITLE
Display the name of the planter/org/wallet

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1068]
On the top page, it's usually the entity's lack of a logo, so we should display the name under the avatar.

So display for these three sections: featured planter, organization, wallet.

![Image](https://user-images.githubusercontent.com/5744708/194681135-b985c1be-c3e1-4b7e-a38c-e6181ee3f6f3.png)

**Comment by khalatevarun** [comment]
Hey @dadiorchen, would like to pick this issue although I have one doubt here.
We are already showing names on hover using tooltip, won't it be redundant then?

**Comment by dadiorchen** [comment]
@khalatevarun thanks! did you join our slack community?

**Comment by khalatevarun** [comment]
> @khalatevarun thanks! did you join our slack community?

not yet, I would love to, how can I join?

**Comment by dadiorchen** [comment]
Give me your email so I can invite you!

**Comment by khalatevarun** [comment]
khalatevarun@gmail.com

**Comment by dadiorchen** [comment]
@khalatevarun what's the situation for this?

**Comment by khalatevarun** [comment]
We are already showing names on hover using tooltip, won't it be redundant then?

could you please answer this?

**Comment by dadiorchen** [comment]
Please remove the tooltip and display the name directly, the reason is there are too many entities that haven't logo, so it's better to display the name directly.
