### ISSUE TITLE
Fix the layout flashing on the embed map

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1069]
When opening this url: https://prod-k8s.treetracker.org/web-map-beta/demo?embed=true before the global map showing up, there is a page shows and disappears quickly, we need to hide this.

**Comment by RubenSmn** [comment]
The same issue is happening with https://prod-k8s.treetracker.org/web-map-beta/demo/top?embed=true

**Comment by ojafero** [comment]
@dadiorchen I loaded production data, but still can't recreate the problem locally.
