### ISSUE TITLE
V2: capture page

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1074]
The capture page will be the same as current `tree` page, actually, we will copy and migrate the tree page to capture page.

* Migrate the current `[treeid].js` to `[captureid].js`
* Change the API from `/trees/{id}` to `/v2/captures/{id}` 
* Prerequirsites: https://github.com/Greenstand/treetracker-query-api/issues/235

**Comment by jeremydthomas** [comment]
@dadiorchen  Are you literally saying to copy what is in [treeid].js and pasting it into [captureid].js?

**Comment by dadiorchen** [comment]
Yes, but, the api is different: /query/trees/xxx -> /query/v2/captures/xxx

**Comment by jeremydthomas** [comment]
@dadiorchen Ok, thats what I was doing except I was changing all the mentions of trees to captures. apiPaths.js complains about using trees again as a duplicate entry.
