### ISSUE TITLE
Update typography input validation

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1081]
# Description
Our validation is not working intuitively/correct
For example the input field for letter spacing, the default value is `0` but when you remove it and re-enter `0` it gives a syntax error. This should not happen because `0` is a valid input
To check for valid inputs we use regular expressions

## To Reproduce
- Visit: http://localhost:3000/admin/theme
- Go to the Typography section
- Dropdown style for H2
- Letterspacing remove the 0 and re-enter 0 

### Validation location
- the rules [/src/models/themePlaygroundOptions.js](https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/models/themePlaygroundOptions.js#L199)
- the check logic [/src/components/playground/TypographyInput.js](https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/components/playground/TypographyInput.js#L86)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by Harshalyadav** [comment]
I'm getting this error
 "Module not found: Can't resolve 'react-best-gradient-color-picker'"
on  http://localhost:3000/admin/theme page.

**Comment by RubenSmn** [comment]
Have you tried running `npm install`?

**Comment by khalatevarun** [comment]
Hey @RubenSmn, the letter-spacing input expects to add 'em' after input. So '0em' works too. I don't think there is any issue to be fixed here.

**Comment by RubenSmn** [comment]
@khalatevarun yes but a valid value should also be 0

**Comment by khalatevarun** [comment]
yes its just that it expects 'em 'at the end. Do you mean for 0 it should ignore the case?

**Comment by RubenSmn** [comment]
Yes for 0 it should also pass

**Comment by khalatevarun** [comment]
got it, thanks for clarifying
