### ISSUE TITLE
Change FontFamily input to dropdown

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1082]
# Description
Currently we have a textfield as an input for the Font Family, we want to change this to a dropdown to reduce errors, like typos.
The dropdown should contains all the default fonts like, Arial, Monospace, etc. On top of the default fonts we want to add the custom loaded fonts by the user.

The theme playground can be found at http://localhost:3000/admin/theme
The Font Family input is under the Typography section

### Short
- change font family input to a dropdown
- add all default fonts like, Arial, Monospace, etc.
- add all the custom fonts loaded by the user on top of the defaults

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by DonBarbaro** [comment]
Hi, can u assign it to me? I can work on this

**Comment by RubenSmn** [comment]
@DonBarbaro yes, go ahead!

**Comment by DonBarbaro** [comment]
@RubenSmn where can I find this textfield?

**Comment by RubenSmn** [comment]
Sorry, you can find the textfield here: [/src/components/playground/TypographyInput.js](https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/components/playground/TypographyInput.js#L148-L173)

**Comment by DonBarbaro** [comment]
hello @RubenSmn  I checked project and I couldnt find that textfiel.... Can u send me URL? Or way where it is?

**Comment by RubenSmn** [comment]
@DonBarbaro the code for the input can be found here https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/components/playground/TypographyInput.js#L148-L173

The input itself on the page can be found on http://localhost:3000/admin/theme under the Typography section

**Comment by DonBarbaro** [comment]
which UI component should I use? MUI has no dropdown component, do you have some chatting app so I can message you there for some more info?

**Comment by DonBarbaro** [comment]
update, I found Select menu, can I use that?

**Comment by RubenSmn** [comment]
@DonBarbaro if you have an email I can add you to our slack. I think the Select component will work just fine.

**Comment by DonBarbaro** [comment]
Hi @RubenSmn I already changed textfield to select menu, but I am not sure about this. "On top of the default fonts we want to add the custom loaded fonts by the user." Can you explain, how it should works? When I choose custom fonts from FONTS, they also appear in TYPOGRAPHY, you want those custom loaded fonts to be on the top of select/dropdown menu? Or you want to choose those fonts from TYPOGRAPHY section. I hope you understand me 😄 Thanks

**Comment by RubenSmn** [comment]
@DonBarbaro Yes so in the TYPOGRAPHY section/tab we want the FontFamily input for all the `style for h1` `style for h2` etc to be the select menu. I could have been more clear on the "On top of" part, what I mean this is:

The user is able to "import" custom fonts from the google font api, this happens in the FONTS section/tab. Those fonts are currently selectable by clicking the `plus` icon next to the FontFamily inputs. In the code there is [this line](https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/components/playground/TypographyInput.js#L123) those fonts contain all the loaded fonts by the user. So the select menu should have all the default fonts like "Arial", "Helvitica", "Times New Roman" etc. In _addition_ to all the default fonts the select menu should also have those loaded fonts by the user, preferably at the top of the select menu.

Note that the inputs in the FONTS section/tab do **not** need to change!

I hope this will help you move forward, if it is not clear or you have more questions please ask away!

**Comment by DonBarbaro** [comment]
Hi @RubenSmn I asked for Pull Request, everything is done. I hope everithing is good.

**Comment by RubenSmn** [comment]
Hi @DonBarbaro I noticed that you opened a PR in your own repository. This way we can't merge it, you should open it against the Greenstand repo. If you have any trouble, this is a great resource on how to do it https://www.dataschool.io/how-to-contribute-on-github/amp/

**Comment by RubenSmn** [comment]
Hmm weird, could you go back to before you pulled the latest version and resolved the conflicts. If you open a PR I can take a look and try resolving the conflicts from here @DonBarbaro .

**Comment by DonBarbaro** [comment]
Open PR in my repo?

**Comment by RubenSmn** [comment]
An PR from you repo to the Greenstand repo

**Comment by DonBarbaro** [comment]
but how can I open when I cant commit and push

**Comment by RubenSmn** [comment]
I can "merge" your PR if everything works :)

**Comment by DonBarbaro** [comment]
I open PL, can u check it, is it good, or need some changes? let me know
