### ISSUE TITLE
Theme type button should be fixed on top

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1083]
# Description
The theme type button on the theme playground hides when you scroll down the list of colors.
This is something we don't want. The user should always be able to see this button when editing the colors.

## Screenshot
Top|After a little scroll
:-:|:-:
![image](https://user-images.githubusercontent.com/31519867/194856720-ba63cf6a-4559-4b4b-884f-9e6cb9fdcc0f.png)|![image](https://user-images.githubusercontent.com/31519867/194856916-1a3c6b00-a6ba-4880-8acb-c226d5077510.png)

### Button location
- [/src/pages/admin/theme.js](https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/pages/admin/theme.js#L474)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by Harshalyadav** [comment]
could you send me localhost URL link?

**Comment by RubenSmn** [comment]
@Harshalyadav sorry I forgot to add this, http://localhost:3000/admin/theme
