### ISSUE TITLE
A bug for the dark theme

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1091]
Sometimes the theme get messy, like below:

![Image](https://user-images.githubusercontent.com/5744708/194979708-05200c14-00d6-459b-a548-0f6ad9ea0add.png)

To reproduce:
* Open the map
* Change to dark theme
* Close the map
* Open it in a new tab

**Comment by ojafero** [comment]
I'm looking into it.
