### ISSUE TITLE
The wallet page support the wallet name

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1093]
Now we just support wallet id: https://prod-k8s.treetracker.org/web-map-beta/demo/wallets/8de4ce55-f17c-41fe-9cc7-c21a47872405
We need to support the wallet by name: https://prod-k8s.treetracker.org/web-map-beta/demo/wallets/dadiorchen

**Comment by dadiorchen** [comment]
We can use the api to fetch wallet by name: https://prod-k8s.treetracker.org/query/wallets/dadiorchen

**Comment by rj564zi** [comment]
I am interested in your issue. Give me the opportunity to resolve it by assigning the issue.

**Comment by dadiorchen** [comment]
@rj564zi oh, that's wonderful! yes, please try it, and if you got any problem, please let me know
