### ISSUE TITLE
When using the config table usersids do not get linked

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-web-map-client#1094]
Users appear in the map but are not linked. see screenshot 
![Screenshot 2022-10-11 at 14 54 25](https://user-images.githubusercontent.com/3283800/195083103-e764e6b9-3891-44f5-aee8-dda905207d20.png)

**Comment by dadiorchen** [comment]
This has solved by https://github.com/Greenstand/treetracker-query-api/pull/241
