### ISSUE TITLE
MaterialUI theme

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#110]
Create the MaterialUI theme according to the design: https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=2497%3A11584

To set default: spacing, color, font, and so on. A reference: https://github.com/Greenstand/treetracker-wallet-web/pull/89

**Comment by sibteali786** [comment]
The provided link is not working to figma design is not working

**Comment by dadiorchen** [comment]
Sorry for the bad link and thanks for the reminder! Can you help to check it again?
