### ISSUE TITLE
The tree page with org context support mapname

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1100]
https://prod-k8s.treetracker.org/web-map-beta/demo/organizations/1332/trees/1642140 we should be able to open this page by another path: https://prod-k8s.treetracker.org/web-map-beta/demo/organizations/bosque-la-tigra/trees/1642140, here the `bosque-la-tigra` is the mapname of this organization, please refer to this issue  #1098

**Comment by cowfish813** [comment]
Hi @dadiorchen, I'd like to help work on this!
