### ISSUE TITLE
Make this icon's color consistent with others

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1101]
The other icon is in grey, but this one is in pink somehow

![Image](https://user-images.githubusercontent.com/5744708/195234283-7da0ed3e-a563-432d-b685-34d3b575dfa3.png)

https://prod-k8s.treetracker.org/web-map-beta/demo/organizations/1332/trees/1642140?bounds=-84.59631443023683,10.302336948330922,-84.58225965499878,10.316122603832673

**Comment by Aksa12** [comment]
Hey, I would like to work on this issue

**Comment by dadiorchen** [comment]
@Aksa12 thank you!
