### ISSUE TITLE
Prefere planter profiles with information attached

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-web-map-client#1103]
In this case 
https://prod-k8s.treetracker.org/web-map-beta/demo/organizations/952?bounds=-93.33984375000001,-56.26776108757583,42.5390625,66.51326044311188
there are 10 planters with additional information attached (currently through webmap.config extra-planter) but they are not showing in the list. The list of planters should be ordered by quality or availability of data.

**Comment by dadiorchen** [comment]
I will design a way to handle this

**Comment by dadiorchen** [comment]
Duplicated issue
