### ISSUE TITLE
The numbers on small map is wrong

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1108]
On this page: https://prod-k8s.treetracker.org/web-map-beta/demo/wallets/8de4ce55-f17c-41fe-9cc7-c21a47872405?bounds=-74.70703125000001,-46.679594465640186,40.42968750000001,52.482780222078226

There are three continents get trees for this wallet, but just one number on the small map 

![Image](https://user-images.githubusercontent.com/5744708/195310469-8d39d4a9-eea0-4828-b961-d739d8e5e34c.png)

**Comment by dpdiliberto** [comment]
@dadiorchen I'm interested in taking a look at this, but curious how you suggest reproducing this locally. I opened a wallet `http://localhost:3001/wallets/eecdf253-05b6-419a-8425-416a3e5fc9a0?bounds=21.4453125,-27.215556209029675,148.00781250000003,64.0914075226231`, and tried replacing it with your wallet ID `http://localhost:3001/wallets/8de4ce55-f17c-41fe-9cc7-c21a47872405?bounds=21.4453125,-27.215556209029675,148.00781250000003,64.0914075226231` but ended up with a 500 error.

**Comment by dadiorchen** [comment]
@dpdiliberto thanks for helping us, you are connecting the dev env, please follow this to connect to prod: https://github.com/Greenstand/treetracker-web-map-client#how-to-connect-to-production-data-locally

**Comment by dadiorchen** [comment]
@dpdiliberto if you want to join our community for better discussion, please give me you email so I can invite you

**Comment by SuokN** [comment]
I think the problem is not in the client, request to the server 
https://prod-k8s.treetracker.org/query/wallets/8de4ce55-f17c-41fe-9cc7-c21a47872405/token-region-count 
return :
{"walletStatistics":[{"continent":"Africa","token_count":"167"},{"continent":null,"token_count":"0"}]}
