### ISSUE TITLE
Upgrade Cypress and set up component tool

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#111]
Upgrade Cypress to the newest version, in the newest version, don't need to install react component/unit test separately. Set up the env to run the component test conveniently. 

Reference: https://github.com/Greenstand/treetracker-wallet-web

**Comment by vishal5251** [comment]
I'll work on it.

**Comment by dadiorchen** [comment]
Thanks @vishal5251 !
