### ISSUE TITLE
Distorted layout on this case

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1118]
These two icon cards should align horizontally

![Image](https://user-images.githubusercontent.com/5744708/196109699-26c55265-ec7c-4430-a3f6-1b0d91d32478.png)

**Comment by dadiorchen** [comment]
@RubenSmn can you check this: https://prod-k8s.treetracker.org/web-map-beta/demo/organizations/1341?bounds=38.16238403320313,-5.547646857881998,39.0618896484375,-4.65444868180161

I think I have deployed your fix for this?

**Comment by dadiorchen** [comment]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/5744708/197316991-a63f4c64-83f2-4f8d-865a-f6d701686425.png">

**Comment by RubenSmn** [comment]
Wow that is weird, I just tested it on Chromium and it works just fine. Then I tested it on Firefox and it looks like the image you posted.

**Comment by RubenSmn** [comment]
Seems like the style from the container holding the cards does not appear in the build version

**Comment by RubenSmn** [comment]
I think it has something to do with the production building the code, no clue what the issue could be.

These display just fine
- https://dev-k8s.treetracker.org/web-map-beta/demo/wallets/eecdf253-05b6-419a-8425-416a3e5fc9a0
- https://dev-k8s.treetracker.org/web-map-beta/demo/planters/940
