### ISSUE TITLE
Add map and display coordinate information on dashboard

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1122]
# Description
Some information about this issue: for the Customizable Web Map need to change the start/initial location for the `/` and `/top` pages.

On the Map Settings tab on the dashboard, which can be found at http://localhost:3000/admin/global, we want to have the actual map on the page.

Things needed:
- map to move/zoom to get to the wanted start location
- display the lat, lon, zoom level

Since I am not an expert on UI design, here is a mock to guide you in the right way

![map-settings-v0](https://user-images.githubusercontent.com/31519867/196443514-fd93ce12-18fa-4676-9ced-24dfe3354567.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by Lz-01** [comment]
please assign this issue to me

**Comment by RubenSmn** [comment]
Sure @Lz-01 go ahead!
