### ISSUE TITLE
Make the selected tree stand out from others

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1124]
The selected tree icon (in the center of the map view) is not so easy to recognize if there are too many trees, we need to refine the icon to stand out from the background.

To check the online map: visit: https://prod-k8s.treetracker.org/web-map-beta/demo/trees/1017648?bounds=36.63305282592774,-3.2141741710175165,36.64850234985352,-3.1986202884940123
You can find it is hard to recognize the selected tree in all the tree icons.

The design Figma file is here: https://www.figma.com/file/kF69K6r81GxoV8eGCgtOFY/Greenstand-Webmap-(Copy)?node-id=11034%3A36450

![Image](https://user-images.githubusercontent.com/5744708/196582722-edde6fa6-0fe0-4a19-9538-9a1f6bd4c74a.png)

**Comment by jeremydthomas** [comment]
Are you thinking a different color when selected? Lets say that orange color in the secondary colors? That should stick out like a sore thumb.

**Comment by khalatevarun** [comment]
Agreed! Orange or dark orange would be easy to identify
