### ISSUE TITLE
We need to customize the menu and logo

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1125]
The administrator should be able to customize the logo and menu on the top:

![Image](https://user-images.githubusercontent.com/5744708/196880618-1ad92919-7a90-4140-8a41-29ebd0723bc3.png)

https://prod-k8s.treetracker.org/web-map-beta/demo/organizations/freetown?bounds=-13.590087890625002,6.888253787244411,-9.992065429687502,10.433793243184432

**Comment by dadiorchen** [comment]
@RubenSmn I have discussed with @sebastiangaertner , we need be able to set up the logo and menu area for our partners.
But one consideration in the future is that that would be standalone permission to give to admin users, not all the organization would have this permission by default

**Comment by RubenSmn** [comment]
Awesome @dadiorchen, I will divide this issue into smalller tasks in a bit!
