### ISSUE TITLE
Rename the `tree planted` to `tree captures collected`

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-web-map-client#1126]
We need to rename the words: `tree planted` to `tree captures collected`

below is the original words from Seba:

-------------

See attached. These are "tree captures collected" not trees planted. in this case it counts 1.2 Million but the amount of trees is 360.000 

We have to rename this and only move back to that claim once we have moved to actual trees. 
![Screenshot 2022-10-20 at 15 53 08](https://user-images.githubusercontent.com/3283800/196954368-be7b8058-8a4d-4aea-a00e-cc0579c8c150.png)

**Comment by sebastiangaertner** [comment]
Also the sub organizations should be listed here and statistics of planters should include total amount of planters.

**Comment by dadiorchen** [comment]
>Also the sub organizations should be listed here and statistics of planters should include total amount of planters.

That's a big change, I will put it into the next release, and split it into fine-described issues.

**Comment by khalatevarun** [comment]
this change needs to be done only for organisation pages?
@dadiorchen @sebastiangaertner

**Comment by sebastiangaertner** [comment]
Also the country leaderboard should show "tree captures"

**Comment by khalatevarun** [comment]
@dadiorchen please review

**Comment by dadiorchen** [comment]
@khalatevarun can you do it again for the country leader board ? thanks, and also: the [planterid].js page
