### ISSUE TITLE
Add input to enter link for logo

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1128]
# Desciption

The organization needs to be able to add a custom logo in the **navbar**. We need an input for this on the dashboard, for now the option to just enter a link is fine. There needs to be an `Save` button aswell to eventually save the data to the database.

### Short
- input for an image link
- button to eventually save

Dashboard can be found at http://localhost:3000/admin/global

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by ojafero** [comment]
I'm working on it.

**Comment by RubenSmn** [comment]
Thanks @ojafero pleas open a PR when you made any progress!
