### ISSUE TITLE
Add section to customize navbar items

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1129]
# Description

The organization needs to be able to change the links on the `Navbar`. The way we intend to this is in a similar way we did on the Theme Playground. We want the to create a list of dropdowns. Each dropdown represents one navbar item. The user will be able to change the `title` and the `url`.

We intend to keep things simple and would like to store the data like this
```json
[
  {
    "title": "Greenstand",
    "url": "/"
  },
  {
    "title": "Partnerships",
    "url": "/partnerships"
  }
]

```

![localhost_3000_top (1)](https://user-images.githubusercontent.com/31519867/196970911-09b8f5ba-665c-45af-a074-6e1b68e90b9d.png)

### Short
- list of dropdowns for every navbar item
- dropdown with 2 inputs
- input for `title`
- input for `url`

Dashboard can be found at http://localhost:3000/admin/global

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by RubenSmn** [comment]
The "theme playground" can be found at http://localhost:3000/admin/theme

**Comment by ojafero** [comment]
I'm working on it.
