### ISSUE TITLE
Add test to see if theme page renders

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1139]
# Description
We had some issues in the past with fixes breaking some features. We want to prevent this from happening so wee need to test if the theme page renders. 

The code of the page is located at `/src/pages/admin/theme.js`. A simple test to see if it renders should be good enough for now.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by khalatevarun** [comment]
Hey @RubenSmn, would like to try solving this issue but I am completely new to testing. Can you suggest any resources?

**Comment by RubenSmn** [comment]
@khalatevarun yes I can, we are using Cypress to test the components/integrations, all our test files for Cypress are written like `filename.cy.js`. When I first came into this project I was not that familiar with testing either. Personally I just went through some `.cy.js` files to see how other people had setup the tests. And googled along the way when I needed to know something.

I do can recommend the [Cypress](https://docs.cypress.io/guides/overview/why-cypress) docs on how to start. They get you familiar with the framework really quick.

Some test files from our project
- [src/components/ImpactSection.cy.js](https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/components/ImpactSection.cy.js) really basic check for rendering
- [src/components/Timeline.cy.js](https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/components/Timeline.cy.js) testing for different devices/urls
- [src/components/Share.cy.js](https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/components/Share.cy.js) testing some interaction

To start the component(unit) tests you can run `npm run cyu`
To start integration/e2e test you can run `npm run cy`
