### ISSUE TITLE
Add `Home` link to mobile navigation

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1151]
# Description

Add a `Home` link on the mobile navigation. On the desktop version it is somewhat clear that you can click on the `Greenstand` text to go to the home page. On mobile this is not the case.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by ojafero** [comment]
I'm on it.

**Comment by RubenSmn** [comment]
After a discussion in #1152 we decided against this change.
