### ISSUE TITLE
Add button to reset Typography inputs to their default value

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1161]
# Description

Currently we can only reset the `Typography` inputs by resetting the whole theme back to the default Greenstand theme.
We want to be able to reset the individual as well. This functionality is already working with the `Palette` inputs.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by Lz-01** [comment]
Can you please assign this issue to me

**Comment by RubenSmn** [comment]
Sure @Lz-01, please open a Pull Request if you made any progress
