### ISSUE TITLE
Update `lng` to `lon` for consistancy

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1162]
# Description
Currently we are using both `lon` and `lng` in our code.
For consistancy we should update `lng` to `lon` since it is the most commonly used.

Reason: all the entities (trees) are using `lon` for coordinates.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by RubenSmn** [comment]
Prerequisite: https://github.com/Greenstand/treetracker-web-map-core/issues/127

**Comment by keyy123** [comment]
I would like to tackle this issue! @RubenSmn

**Comment by RubenSmn** [comment]
Hmm that is weird, so you can't make a PR?

PS before your changes get merged this requires for [this](https://github.com/Greenstand/treetracker-web-map-api/pull/353) to be merged :wink:

**Comment by keyy123** [comment]
🤣 That's comedy. Alright, I will wait until the changes are pushed into web-map API @RubenSmn!

**Comment by dadiorchen** [comment]
This is too difficult to change, let's close it for the time being
