### ISSUE TITLE
Wrong number on the small map

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1171]
https://prod-k8s.treetracker.org/web-map-beta/demo/organizations/178?bounds=-13.765869140625002,6.68643125265198,-9.810791015625,10.628216112538693

![Image](https://user-images.githubusercontent.com/5744708/200106714-cda60540-7cbe-46ec-a135-6f6ddea9a98d.png)

**Comment by mushtaq96** [comment]
Hi @dadiorchen I would like to look into this bug, could you please assign it to me?

**Comment by dadiorchen** [comment]
Yes, thank you!

**Comment by dadiorchen** [comment]
@mushtaq96 for this issue, because we don't have a API to statistic the count by continents, so it is fine to just give the total number to the first continent, Africa for this case, because at this stage, most of our org are planting tree just in a single continent, we have no org that cross continents.

**Comment by mushtaq96** [comment]
Hello @dadiorchen , thanks for sharing that info.
