### ISSUE TITLE
Wrong date on this page

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1172]
https://prod-k8s.treetracker.org/web-map-beta/demo/organizations/178?bounds=-13.765869140625002,6.68643125265198,-9.810791015625,10.628216112538693

![Image](https://user-images.githubusercontent.com/5744708/200106756-6274c4d6-c7ee-43c2-a237-2b90f6a61f31.png)

**Comment by dadiorchen** [comment]
@sebastiangaertner for the creation time, I think we can put `created_at` in the `extra_organization` in the config table, so we can fill the date there, @sebastiangaertner what do you think?

**Comment by RubenSmn** [comment]
Maybe an `established` field on the organization table itself?

**Comment by dadiorchen** [comment]
Yes, the situation is that we are lacking of this date for organization, it would be solved in the next version of the admin panel, but for now, I think we can do an ad-hoc by setting the data in `web-map-config`

**Comment by janet-yu** [comment]
Hello, I'm interested in taking on this issue! Is this ready to be worked on? Or is there something that needs to be done first related to the `web-map-config` that was mentioned?

**Comment by janet-yu** [comment]
Okay! I haven't explored the db yet, would I follow the steps to set up the local db in the docs [here](https://github.com/janet-yu/treetracker-api)?

**Comment by dadiorchen** [comment]
Guys, I have solved this problem.
@sebastiangaertner Please note, because the stakeholder is not in place, so we can use webmap config to set it manually, just putting a `created_at` field into the extra-organization will work, I found an easy way to change the json data:
```
-- update column data that is a json object
UPDATE webmap.config 
set data = data::jsonb || '{"created_at": "2022-05-26 06:47:14"}'
WHERE id = '4d814518-ea7b-43dd-980c-fe29ec0f943a';
```
