### ISSUE TITLE
Add indication for `custom` fonts in dropdown

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1174]
# Description

On the `Typography` section in the theme editor which can be found at http://localhost:3000/admin/theme we want to have some indication for the "custom" fonts.

When you click on a dropdown you can select the `FontFamily`. This will have another dropdown with all the "default" fonts like `Arial`, `Helvetica`. But also the "custom" fonts like `Lato` and `Montserrat`. See the screenshot below.

We would like to have some indication if it is a "custom" font. The icon we're using for the `Fonts` tab would be perfect. 

![image](https://user-images.githubusercontent.com/31519867/200532536-965e42e5-bc4d-442f-83d7-2cf7d7495eba.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by ojafero** [comment]
I can work on it.
