### ISSUE TITLE
features wallet logo not showing up (defined in web.map.config)

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-web-map-client#1180]
Looking at 

https://prod-k8s.treetracker.org/web-map-beta/demo/wallets/2aa0d3c1-5f0b-4fb3-9728-3bf5ed81d49a the logo shows up

on the overview (featured wallets) https://prod-k8s.treetracker.org/web-map-beta/demo/top the logo defined in the config file does not show up.

**Comment by dadiorchen** [comment]
Duplicated issue with #1218
