### ISSUE TITLE
The timeline filter is gone when clicking `expand` button

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1193]
<img width="209" alt="image" src="https://user-images.githubusercontent.com/5744708/202387842-31707db3-c5d7-4f61-921a-9cc8688c9d8f.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by keyy123** [comment]
Hi @dadiorchen , I would like to tackle this issue. I am reading the code base but can you point me to other resources as well for this issue? I would sincerely appreciate it.

**Comment by RubenSmn** [comment]
Fixed by  #1237
