### ISSUE TITLE
When switching between fullscreen and normal screen we need to remember the timeline filter settings

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1194]
---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by ojafero** [comment]
I'm on it.

**Comment by dadiorchen** [comment]
@ojafero thank you!

**Comment by dadiorchen** [comment]
@ojafero let's dicuss here:

quote jafer's words on slack:

>For this issue https://github.com/Greenstand/treetracker-web-map-client/issues/1194, there is more than one way to ensure date is saved.
Store in React Context
Store in Browser: Local Storage or Session Storage
I don't think react context is a good approach because the Timeline component is used across different Layout components so I would have to keep the state at a high enough parent. This will result in unnecessary renders.
If we only need to remember settings between screens, storing it in a session storage would be a good approach because data will automatically be deleted from the user's browser when the user closes the tab. Also, considering the fact that only the Timeline component needs the data.

**Comment by dadiorchen** [comment]
@ojafero what's session storage? Is it in the localstorage?  how do we delete it after closing tab?

In this case, I think context re-rerender is acceptable because the frequency of this is low

@RubenSmn can you give some input? And I remember we did some states persistent in some way right? like the customizable web map?

**Comment by RubenSmn** [comment]
I agree with @ojafero I don't think React context is the way to go here. When a user changes the timeline we save it to the context and that re-renders all the child components. Which are quite a lot components since the context provider should wrapper around the app itself to support the "normal" and "embed" layout.

Session storage can be a good approach if we can create some kind of hook for it, the same we did for the localstorage.

**Comment by ojafero** [comment]
@dadiorchen Session storage is another type of web storage where we can store key value pairs. The data is stored in the browser, and is automatically cleared by the browser. We don't have to do anything. Data that is stored in local storage is kept seperate from data stored in session storage.

I was planning on creating a hook for it.

**Comment by dadiorchen** [comment]
@ojafero thanks for the explaination.
