### ISSUE TITLE
Footer takes a lot of space on mobile devices

### ISSUE THREAD

**Issue by akssshh** [Greenstand/treetracker-web-map-client#1195]
---
On small devices, the footer takes up a lot of space.

![Screenshot 2022-11-17 at 1 44 51 PM](https://user-images.githubusercontent.com/91525166/202392621-fc218a35-a70f-4c41-b39b-834122234f09.png)

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
@gogoiakash2311 thanks for reporting this, can you tell me what's the page/url for this error?

**Comment by gogoiakash2311** [comment]
https://greenstand.org/
