### ISSUE TITLE
Country leader board on mobile broken css 

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-web-map-client#1197]
See screenshot ![Screenshot_20221118-122610_Chrome.jpg](https://user-images.githubusercontent.com/3283800/202668764-576e95a0-16f5-4f60-9daa-ca61fbed52ec.jpg)

**Comment by RubenSmn** [comment]
Maybe we can do something like we did [here](https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/components/TreeSpeciesCard.js#L14-L16) by formatting the count to a `317K` or `1.1M`
