### ISSUE TITLE
Component for featured tree.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#121]
Build a good component of the slider for the featured tree. 

https://www.loom.com/share/96334f0089f94eeeb068a80f72d8d8e3

---
Some hints for building components:
* Design resource: https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=2497%3A11584
* A tutorial of how to use the Cypress component tool to build components: 
  https://github.com/Greenstand/treetracker-wallet-web#how-to-build-a-component
* We are using MaterialUI to build the app: https://material-ui.com/
* When you are ready to raise PR for the component, please attach the screenshot of the component for review.
* Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
* Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
* To know more about our organization, visit our [website](https://greenstand.org).

**Comment by YassinHussein** [comment]
I would like to work on this
