### ISSUE TITLE
Featured wallet not showing logo from config Table

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-web-map-client#1218]
See the screenhsots attached. 
in the detail view the logo that is stored in the json on webmap.config is showing 
![Screenshot 2022-11-28 at 07 06 02](https://user-images.githubusercontent.com/3283800/204192171-ac931b64-50f3-4a3b-aa00-c37407e1da02.png)

in the overview "featured wallet" list the logo is not showing. 
![Screenshot 2022-11-28 at 07 06 43](https://user-images.githubusercontent.com/3283800/204192166-5c3572ec-20ff-4d4e-98d2-f15da948d9b8.png)

**Comment by dadiorchen** [comment]
@sebastiangaertner I have solved this
