### ISSUE TITLE
Bug: dark mode embed version incorrect

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1236]
## Description
The dark mode in the embed version is not working. This is similar to this issue #1091 which was fixed by #1153

Step to reproduce
- on the top page
- set the theme mode to `dark`
- go to any detail page
- click the `embed` button

![image](https://user-images.githubusercontent.com/31519867/205377854-14c3355d-023c-4c62-abfb-c9d4e9f2d2f5.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by RubenSmn** [comment]
@jeremydthomas would you like to have a look?

**Comment by jeremydthomas** [comment]
Sure, I'll look at it.
