### ISSUE TITLE
Change the name of the web map client

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1248]
Currently, the name of the app is Greenstand, it is inaccurate, it should be: Treetracker by greenstand
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/5744708/205537323-c855f0fc-d1c6-438d-baaf-dc3d9bc2a362.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by khalatevarun** [comment]
Hey @dadiorchen , would like to pick this up.

**Comment by dadiorchen** [comment]
@khalatevarun sorry, please ignore this one, we have done this
