### ISSUE TITLE
Implement simple overlay notification

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-web-map-client#1249]
The webmap.config would be the best place to have global announcements. A simple pop up panel with a configurable message to announce downtimes, upgrades or other important messages.

**Comment by RubenSmn** [comment]
For this we need a custom component that will help us display the information. We would like to use the [MUI Snackbar](https://mui.com/material-ui/react-snackbar/) as a base for this component.
- The component should be accessible on all pages.
- Good mobile support

**Comment by dadiorchen** [comment]
@RubenSmn just for dicussion, I was thinking of the notification component, a pain point of mui style is the declarative way to display a message box, IMO, you need to control the workflow of show/hide, and another example is the process way to do it as the antd do, https://ant.design/ you just call a function, and the lib will take over and do all the stuff, what do you think

**Comment by keyy123** [comment]
Where specifically is the webmap.config file in the web-map-client repo that @sebastiangaertner mentioned? I have read @RubenSmn  and @dadiorchen suggestions for the components and decided to use antd library due to their simplicity in implementing notifications with dynamic text.  

Note: I hope everyone had a happy holiday.

**Comment by andrewsu31098** [comment]
@keyy123 webMapConfig is stored in the localstorage as "config". I'm assuming that's what he's referring to. See Navbar.js:66.

**Comment by RubenSmn** [comment]
@keyy123 yes for now you can just use the localstorage as a "dev" database. The idea is that in the future we can add some messages to the database, retrieve them and show them with the notification system

**Comment by dadiorchen** [comment]
webmap.config is a temporarily solution, we need to design this feature seriously somewhere.
