### ISSUE TITLE
The number of tree is wrong again

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1250]
<img width="888" alt="image" src="https://user-images.githubusercontent.com/5744708/205565714-0f58d769-d196-40bc-9787-35edc36d0720.png">

https://beta-map.treetracker.org/planters/3953?bounds=36.62678718566895,-3.2159523546263147,36.642236709594734,-3.200398499152652

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by TilteD24** [comment]
I would like to work on this issue !

**Comment by dadiorchen** [comment]
@TilteD24 thank you! yea, go ahead

**Comment by TilteD24** [comment]
What should be the correct number of trees here ?

**Comment by dadiorchen** [comment]
I am not sure 280 is the case, but the 20 seems the length of the result array from API, that's wrong, we need to display the `total` from API

**Comment by dadiorchen** [comment]
@TilteD24 please ignore this issue, it's just a simple case, we have solved it
