### ISSUE TITLE
Bug: home page buttons have hard-coded color values

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1257]
# Description

On the `home` [page](http://localhost:3000/) the "Learn more" and "Let's Find a Tree" buttons have hard-coded color values.
Please update these color values with the according colors from the `theme` which can be found [here](https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/context/themeContext.js#L93)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by TilteD24** [comment]
I would like to work on this issue

**Comment by RubenSmn** [comment]
Awesome @TilteD24 go ahead, open a PR if you made any progress!

**Comment by khalatevarun** [comment]
Hey @RubenSmn, there is no value that can override ```MuiBox-root&:hover``` , can't really replace with color from theme.
Correct me if I am wrong.
![image](https://user-images.githubusercontent.com/68511458/206479597-f27e8ab1-e970-485c-87b6-a098ffe9e2f6.png)

**Comment by andrewsu31098** [comment]
Hello @RubenSmn. I would like to contribute. May I be added to the slack? My email is avsu@uci.edu. Also would be really helpful to see the [css-and-materialui-guideline](https://app.gitbook.com/o/-MXNadx4i6aOZ12XcStA/s/-MWfUniHAtkV1kYf898m/css-and-materialui-guideline) as well.
