### ISSUE TITLE
Give suggestion on SEO and social media sharing and set up Open Graph

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1260]
Please help us improve the SEO or social media sharing spreading on the internet for the web map client, set up like: Open Graph (https://ogp.me/) to utilize social media and search engines to promote the site.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by keyy123** [comment]
@dadiorchen I would like to take on this challenge! 😁👌

**Comment by keyy123** [comment]
I have some questions @dadiorchen. How many social media channels do we want to prepare greenstand for? Facebook, Twitter, Add Structured Data, and Mobile Optimizations. 

P.S. It has been a while. I went off to learn SEO technique to complete the ticket and I am almost done.

**Comment by keyy123** [comment]
Suggestions:

1. We need static assets (images for both Facebook and Twitter opengraph data) * Current Step*
  -  FB: 1200 x 630px (large cards) 
  - Twitter: 1200px X 628px (large cards) || 800px X 320px (Website Ad Cards) || 800px X 200px (Lead Generation Ad Cards)
   
  - Note: All Images should have the Greenstand Logo, for branding purposes, with a simple Call To Action (i.e., Learn more). 

2. Add structured data - *this will affect how the search results look on google*
       - Schema.org || Google it - We need to determine how it should look like as a google search research
       
3. Identify SEO niches for green stands' tree tracker application. * I have some data but need more feedback *
        - Identify what areas competing companies are aiming for and they don't focus on (competitive edge)
        
        - Identify content that people find engaging in general 


Optional Steps:
   * Accelarated Mobile Pages 
   
   * Mobile Optimizations
   
   * Pinterest Rich Cards

**Comment by dadiorchen** [comment]
@keyy123 this is awesome, please go ahead and give us your solution, don't hesitate to raise PR, we will discover and test the result along the way.
