### ISSUE TITLE
Bug: featured slider button can't return back to start in Firefox

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1279]
# Description

When clicking the buttons to "scroll" in the featured sliders you can't go back the last "scroll"

To reproduce
- visit http://localhost:3000/organizations/178
- click the expand icon on the map to go the embed version
- click **2** times the right button on the slider
- click **2** times the left button on the slider

You'll see that it does not go back to the start

**NOTE:** it does work on Chrome / Chromium

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by ojafero** [comment]
I'm looking into it.
