### ISSUE TITLE
Embed version layout hired planters not responsive

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1282]
# Description

The hired planters section is not responsive for the embed version.

To reproduce
- visit http://localhost:3000/organizations/178?embed=true
- click `hired planters`

See the image below

![image](https://user-images.githubusercontent.com/31519867/207089718-f52dcc28-058e-4789-888d-030c8354efcc.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by ojafero** [comment]
I'm on it.
