### ISSUE TITLE
Bug: initial slider position incorrect on Firefox

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1304]
# Description
The initial position of the sliders are incorrect.

![image](https://user-images.githubusercontent.com/31519867/208917386-0efb82d9-e015-4cbd-a47d-9a4c778165d2.png)

To reproduce
- visit: https://beta-map.treetracker.org/top

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by ojafero** [comment]
@RubenSmn Could you elaborate on the problem?

I'm using Firefox and I see the first card when I go on that link.

<img width="707"  src="https://user-images.githubusercontent.com/53157755/208987108-8af301d5-583b-4744-a140-dc76cd1bb7c7.png">

**Comment by RubenSmn** [comment]
Hmm after some closer investigation I think its maybe because of the devtools if have open on the right of my browser. Could you see if you have any problem then @ojafero

**Comment by andrewsu31098** [comment]
Hi. @RubenSmn. Initial slider position looks correct to me as well.
![s](https://user-images.githubusercontent.com/48111116/209025716-3fd7867e-20b1-4072-a6cc-15f8b6a960b5.PNG)

I notice the left nav button on sliders doesn't respond to clicks. Specifically on Firefox (works on Chrome)
![left](https://user-images.githubusercontent.com/48111116/209025694-a6a73ed5-7998-4e11-b183-0d08ad34aec3.PNG)

**Comment by RubenSmn** [comment]
Thanks @andrewsu31098 for looking into this. Yeah I think the start has something to do with the devtools being open. Can't seem to find the issue when they are closed.

That issue should have been resolved #1279 by @ojafero

**Comment by ojafero** [comment]
@RubenSmn I don't see any problem.

@andrewsu31098 That has been fixed. The changes just haven't been deployed to production yet.

**Comment by RubenSmn** [comment]
I'll close this since it is not a "real" bug
