### ISSUE TITLE
Bug: planter images rotated incorrect on organization pages

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1306]
# Description

The planter images are rotated incorrect on the organization pages

![image](https://user-images.githubusercontent.com/31519867/208920633-8c7dd065-5e80-494c-9cbf-21a0c6ccd953.png)

To reproduce
- visit: https://beta-map.treetracker.org/organizations/1333
- click on hired planters
- scroll through and see that many are rotated incorrect

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by RubenSmn** [comment]
After further investigation, this is related to the `PlanterQuote` component. Which uses the regular MUI `Avatar` component instead of our custom `ProfileAvatar` component. You can find an implementation of the `ProfileAvatar` [here](https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/pages/planters/%5Bplanterid%5D.js#L213-L216)

**Comment by salindae25** [comment]
@RubenSmn I would like to work on this.

**Comment by RubenSmn** [comment]
Awesome @salindae25

**Comment by salindae25** [comment]
@RubenSmn we can not directly use the `ProfileAvatar` component here. Since we have to position the Image.
There are two options;
 - add image_rotation as a transformation to the existing `Avatar` component.
 - Modify the `ProfileAvatar` component so that we can override the default `ProfileAvatar` style.
 
Note:- I noticed even after we add `image_rotation` to style, some images are rotated incorrectly. i.e data seem to be incorrect.

**Comment by RubenSmn** [comment]
@salindae25 yes I see, I think we should  add the `sx` prop to the `ProfileAvatar` to override the default style.

As for the `image_rotation` some values are indeed `null` which is something we need to handle in the backend, no need to worry :smile:
