### ISSUE TITLE
Bug: planter image has no rotation value

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1307]
# Description

The planter has no `image_rotation` value in this case https://beta-map.treetracker.org/planters/649

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by RubenSmn** [comment]
@dadiorchen maybe this need to be configured in the admin panel?

**Comment by dadiorchen** [comment]
@RubenSmn I have reported to them, it's also good you open issues in their repo directly: https://github.com/Greenstand/treetracker-admin-client

**Comment by RubenSmn** [comment]
@dadiorchen I'll do that in the future 👍, I did not know where exactly to open it

**Comment by RubenSmn** [comment]
Will be fixed by https://github.com/Greenstand/treetracker-admin-client/issues/987
