### ISSUE TITLE
Import aliases not followed throughout the codebase

### ISSUE THREAD

**Issue by khalatevarun** [Greenstand/treetracker-web-map-client#1313]
---
 Problem: Import aliases not followed throughout the codebase #1313
 
![image](https://user-images.githubusercontent.com/68511458/209148067-35ffdcf0-b6fc-4f2e-8f99-28b6491e7993.png)

**Comment by khalatevarun** [comment]
@dadiorchen @RubenSmn I have written a codemod to solve this issue, will raise a PR in a while

**Comment by dadiorchen** [comment]
@khalatevarun it is so nice to see you again, and happy Christmas!

**Comment by khalatevarun** [comment]
wish you the same! :) @dadiorchen
