### ISSUE TITLE
Running `npm i` with node 18 results in "Unsupported engine" error

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1321]
# Description

If you have `node` version `^18` you will get an error when running `npm i`

```js
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: client@2.0.0-beta.215
npm ERR! notsup Not compatible with your version of node/npm: client@2.0.0-beta.215
npm ERR! notsup Required: {"node":"^16"}
npm ERR! notsup Actual:   {"npm":"9.2.0"}
```

To reproduce
- have `node` version 18
- try to run `npm i`

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
Yea, maybe it's time to consider upgrading to 18

**Comment by RubenSmn** [comment]
@dadiorchen I did a "quick fix" with changing the `engines.node` value in the `package.json` to `"^16 || ^18"`
