### ISSUE TITLE
Please replace this icon

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1331]
# Description

<img width="804" alt="image" src="https://user-images.githubusercontent.com/5744708/209526868-8463b698-dc93-4eab-8420-373606a9f098.png">

To reproduce

* Go to: https://beta-map.treetracker.org/trees/3197592
* The planting organization's icon is an outline of a man, please replace it with the default greenstand logo icon

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by Revati2103** [comment]
I would like to be assigned to this one please .
