### ISSUE TITLE
Initial view of this planter is wrong

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1332]
# Description

https://beta-map.treetracker.org/planters/6822 

Can not see any icons on the initial view

To reproduce

[comment]: # 'To reproduce'

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by SuokN** [comment]
And i think the reproducibility of the error only depends on the width of your browser, which is why @jeremydthomas doesn't reproduce it in https://github.com/Greenstand/treetracker-web-map-client/issues/1325.

**Comment by jeremydthomas** [comment]
I agree with the width part, Ive been trying to figure this one out and sometimes it works and sometimes it doesnt. Also when there is a bounds, sometimes it works and sometimes it doesnt.

**Comment by SuokN** [comment]
@dadiorchen  Ok, I will do it

**Comment by dadiorchen** [comment]
@SuokN are you in the community? What's your name over there?

**Comment by dadiorchen** [comment]
@SuokN do you think this is the same problem? https://beta-map.treetracker.org/wallets/f3d90452-12c6-4c23-8d2f-6cfa2ddc203b

**Comment by SuokN** [comment]
I think so, in new version this initial view is ok.
I am in community Natasha Kazovskaya

**Comment by dadiorchen** [comment]
@SuokN did you raise a PR for this? The new version?

**Comment by dadiorchen** [comment]
I mean for the web map client

**Comment by SuokN** [comment]
yes, it is in the last version of web-map-core

**Comment by dadiorchen** [comment]
@SuokN can you raise a PR to install the new one in the web map client?

**Comment by SuokN** [comment]
ok
