### ISSUE TITLE
Organization name is spelled wrong

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1333]
# Description

The organization name is spelled wrong

![image](https://user-images.githubusercontent.com/31519867/209550832-88021945-9059-440c-b368-ed32d44f01c5.png)

To reproduce

- visit: https://beta-map.treetracker.org/organizations/fcctrees

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by tarunsamanta2k20** [comment]
I would like to contribute to this issue. Please assign it to me.

**Comment by tarunsamanta2k20** [comment]
this issue is a backend task.

**Comment by tarunsamanta2k20** [comment]
To be precise, sql queries  task.

**Comment by dadiorchen** [comment]
I have solved this problem, will be shown tomorrow ( one day cache expiration)
