### ISSUE TITLE
Remove extra "organization" word in breadcrumbs

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1334]
# Description

Remove the extra "**organization**" word in the breadcrumbs. There is no need for the extra word.

![image](https://user-images.githubusercontent.com/31519867/209551010-2e3b7f44-332b-4747-a09d-0f19fa0f4197.png)

To reproduce

- visit: https://beta-map.treetracker.org/organizations/178

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue. Please assign it to me.
