### ISSUE TITLE
The nearest tree feature is broken

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1340]
# Description

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/5744708/210027412-b9a3b4c0-a722-4fad-881d-5570e67d61fa.png">

: https://prod-k8s.treetracker.org/webmap/nearest?zoom_level=16&lat=-16.404670666666668&lon=undefined

To reproduce

[comment]: # 'To reproduce'

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by SuokN** [comment]
I think this bug is in the map core. It happens because of the changing lng to lon (#1162).

**Comment by dadiorchen** [comment]
@SuokN you are right, I just withdrawed a PR from core, it should solve this
