### ISSUE TITLE
Wrong color on the map

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1354]
On the fullscreen version, the logo text: greenstand on the bottom right corner is wrong, should be white color rather black

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5744708/213636758-37be255b-3644-4614-98e9-99d993a38f33.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by SamEarth79** [comment]
Hi
I believe the reason the logo has black text is, the [png](https://github.com/Greenstand/treetracker-web-map-client/blob/ac8fd3861cf0fdba069ef31c0d4a3257af3d8625/public/images/greenstand_logo_full.png) used has a black text in it. 
Adding to this this png has been placed in this [file](https://github.com/Greenstand/treetracker-web-map-client/blob/cae4d350091de7040d6113a0c726ccfe07d504b9/src/components/LayoutEmbed.js) 

Further, I briefed the figma design and was able to find the logo in this [page](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=953%3A0) above MacBook Pro - 7 page.

If you can give the access to edit the figma design, I can edit it myself and get everything done. Or I'm happy to just modify the code if you add another image with white text.

samarthmm.work@gmail.com

**Comment by BurakAy** [comment]
I haven't been able to replicate this. The element in your screenshot has an opaque black background whereas the element I'm seeing has a white background (screenshot attached)
![fs_map_greenstand_logo_color](https://user-images.githubusercontent.com/14030652/213744166-19f4cf0a-3b00-47bc-8cf6-dc4b6d76bc36.png)

Steps to replicate?

**Comment by BurakAy** [comment]
> I haven't been able to replicate this. The element in your screenshot has an opaque black background whereas the element I'm seeing has a white background (screenshot attached) ![fs_map_greenstand_logo_color](https://user-images.githubusercontent.com/14030652/213744166-19f4cf0a-3b00-47bc-8cf6-dc4b6d76bc36.png)
> 
> Steps to replicate?

I just noticed that there is a 'dark mode' switch in the main nav which needs to be enabled before going full screen in order to replicate the issue.

**Comment by dadiorchen** [comment]
Hi, guys, the design file is here: https://www.figma.com/file/l9GrplCZEyRF44uRHSpoIY/Web-Map?node-id=305%3A17&t=GgJ1aqSeS4FRZxoz-4

Feel free to copy this design and create a new one, I guess we can do it for Greenstand logo with white text and transparent background right?

**Comment by jeremydthomas** [comment]
> > I haven't been able to replicate this. The element in your screenshot has an opaque black background whereas the element I'm seeing has a white background (screenshot attached)...
> > 
> > Steps to replicate?
> 
> I just noticed that there is a 'dark mode' button in the header which needs to be enabled before going full screen in order to replicate the issue. 
> 
> 

That is the dark mode color, was going to say that, but you beat me to it. I would think that you should be able to disable dark mode for just that picture. Just going by what I remember from previous times I've been in the code. I could be totally wrong though. 

Sorry for editing your post, I meant to quote reply 🤣

**Comment by dadiorchen** [comment]
This issue is open to contributors

**Comment by lichenqin1** [comment]
@dadiorchen I'd like to solve this issue, please assign it to me.

**Comment by dadiorchen** [comment]
Done
