### ISSUE TITLE
Upgrade from node14 to 18 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1364]
# Description

We ran into error like this: 

```
[semantic-release]: node version >=18 is required. Found v14.21.2.
```
Please help us upgrade the node version to 18, and test if anything is good.

To reproduce

[comment]: # 'To reproduce'

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by keyy123** [comment]
Ok

**Comment by keyy123** [comment]
@dadiorchen, How can I specifically reproduce the error?
