### ISSUE TITLE
Safari problem: home picture is missing

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1367]
# Description
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/5744708/215375774-414de43b-19a0-474c-9736-76b7aabad5c2.png">

[comment]: open safari on macos and visit: https://beta-map.treetracker.org

To reproduce

[comment]: # 'To reproduce'

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by rsmith-github** [comment]
Hi there, It seems like there is no bug on my side. I am using Safari on macOS!

<img width="1403" alt="Screenshot 2023-01-31 at 03 42 45" src="https://user-images.githubusercontent.com/92221802/215657538-27ba6c70-c1f6-4461-9582-a64b29fce4fd.png">

**Comment by dadiorchen** [comment]
Yea, me too, a colleague of mine reported this, I am thinking it might be a temporary problem with the API side, so browser -> client -> API -> error -> client shows it 
I think this is way we need something like sentry or others to collect message like this.

**Comment by dadiorchen** [comment]
Also, the server side error log is collected by Loki on Grafana, so @sebastiangaertner I think next time, we can report the problem with the time, so we can check the log of that moment.
