### ISSUE TITLE
TokenId link is broken on breadcrumbs

### ISSUE THREAD

**Issue by khalatevarun** [Greenstand/treetracker-web-map-client#1374]
**Describe the bug**
On clicking on tokenId the website throws a client exception error.

**To Reproduce**
https://beta-map.treetracker.org/tokens/00b97042-4d22-4804-a6ae-ccc1380139ae?bounds=-13.204514980316164,8.450002058725486,-13.183915615081789,8.46850958560705

https://user-images.githubusercontent.com/68511458/215565824-d9a28335-c27a-44f5-884b-9abd6ac253a0.mp4

**Expected behavior**

**Screenshots**

\*\* Node.js version
(The node version on your computer to run the project)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khalatevarun** [comment]
Should be fixed by #1609

**Comment by dadiorchen** [comment]
@khalatevarun thank you!
