### ISSUE TITLE
Set up the logo for web map client

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1376]
Please set the logo on the banner, following the design here:

<img width="887" alt="image" src="https://user-images.githubusercontent.com/5744708/215928155-13c57f9f-1226-46a7-8ca7-e8c92b94290a.png">
https://www.figma.com/file/LykDBRyuHY668vbGVkYaps/Greenstand-Webmap-(Copy)-(Copy)-(Copy)?node-id=2497%3A11570&t=j1Lif0cLx2tHeRcQ-4

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by Rengkat** [comment]
should i go ahead and do this?

**Comment by shyamtawli** [comment]
Hey @dadiorchen Please assign me, I want to work on this.

**Comment by dadiorchen** [comment]
@Rengkat yes, please go

**Comment by dadiorchen** [comment]
@Rengkat @shyamtawli could you guys leave the email so we can invite you to your community, there are a lot happening over there :D
