### ISSUE TITLE
Verified tree shows "not verified"

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-web-map-client#1379]
This tree https://beta-map.treetracker.org/trees/3065762 is approved and verified but shows not verified in the Tree info panel. see screenshots 
![Screenshot 2023-02-01 at 08 09 31](https://user-images.githubusercontent.com/3283800/215957577-6e1ea6d8-c91a-4ee6-8255-e1f7c8d40b74.png)
![Screenshot 2023-02-01 at 08 09 40](https://user-images.githubusercontent.com/3283800/215957598-4cf14149-a973-4f2d-841f-fb10ba771a88.png)
![Screenshot 2023-02-01 at 08 11 16](https://user-images.githubusercontent.com/3283800/215957599-929d48bd-b13a-4861-94ec-1d36ee1cc473.png)

**Comment by MadhuMPandurangi** [comment]
Hi @sebastiangaertner I'm interested. Can you please assign me this
I'm taking it as my college project. I went to the website and found the project interesting. It'd be helpful for me in my academics too.
thank you

**Comment by dadiorchen** [comment]
@MadhuMPandurangi thank for being interested in our project, we have done a quick fix for this because it is a bit urgent for us, so, can you take another one?
