### ISSUE TITLE
Getting a TypeError when running npm start 

### ISSUE THREAD

**Issue by jwgatt** [Greenstand/treetracker-web-map-client#138]
Web-map-client wont compile

Run npm start in the root folder

![image](https://user-images.githubusercontent.com/79326421/134180663-459d72f7-e7c0-4e40-bc0e-31d62a9aad8f.png)

**Expected behavior**
I expected the client to run locally on my machine.

Ubuntu 20.04
Linux
Chromium 93.0 / Firefox 92.0

**Comment by dadiorchen** [comment]
This is about, .env settings, https://github.com/Greenstand/treetracker-web-map-client/blob/web-map-site/.env
the third config failed to load. Don't know why

**Comment by jwgatt** [comment]
Deleted the repo, re-cloned it from source and it works fine now.
