### ISSUE TITLE
The UI/UX design for register & login & user profile

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1382]
Design the UX/UI for users: register, login, and profile settings.

**Comment by theVJagrawal** [comment]
Hey @dadiorchen i want to work on this issue, so could you please assign me this

**Comment by dadiorchen** [comment]
Cool

**Comment by dadiorchen** [comment]
If you want please give me your email so I can invite you into our community on slack

**Comment by theVJagrawal** [comment]
hey @dadiorchen thanks for your reply, this is my email thevjagrawal@gmail.com
and could you please give more information about the issue

**Comment by buiminh1995** [comment]
Would you like something like this?
![LoginPageGreenstand](https://user-images.githubusercontent.com/29977238/217940444-00a6ffe4-e553-4444-8279-ef18cbe490ec.png)

**Comment by dadiorchen** [comment]
@buiminh1995 this is great, let's discuss more on slack!

**Comment by buiminh1995** [comment]
ok:)

**Comment by dadiorchen** [comment]
This issue is to vague and lack of details, and to big, I will explain this and split into smaller issues.
