### ISSUE TITLE
Web map client can register and login

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1384]
We have deployed our keycloak (oauth solution) on cloud, now we need the web map client to connect to it, and be able to let user register and login to the site.

https://dev-k8s.treetracker.org/auth/ (please connect @dadiorchen for details)

The UI design is not ready yet for this, so please go forward first and implement it without too much serious UI

**Comment by shubhamku044** [comment]
Hey, can I take this issue?

**Comment by jeremydthomas** [comment]
sure @shubhamku044

**Comment by khalatevarun** [comment]
true @RubenSmn

**Comment by dadiorchen** [comment]
@RubenSmn I think it is fine, it is pretty clear in terms of the requirement.

**Comment by dadiorchen** [comment]
@shubhamku044 This is a example, a static page to login via keycloak

**Comment by shubhamku044** [comment]
> @shubhamku044 This is a example, a static page to login via keycloak
> 
> https://github.com/Greenstand/treetracker-auth/blob/main/tools/client/website/index.html

Okay sure, I will look into it.
