### ISSUE TITLE
Remove impact component from all pages

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1402]
Because we can not implement this soon, please remove this selection from all pages:

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/5744708/222307310-46977a7e-d11d-4216-a5f9-4a6630f6b797.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by pierrelstan** [comment]
Hi @dadiorchen, I want to take this one.

**Comment by pierrelstan** [comment]
ok, I will do that.

**Comment by RubenSmn** [comment]
Resolved by #1510
