### ISSUE TITLE
Refactor the deployment folder

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1443]
Currently, we use separate folders to deploy app to different channel, we need a better way to avoid duplication, just like we do on the overlay-base folder using kustomize

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
The goal is to use a unified folder to handle all channels:
```
deployment
deployment-next
deployment-main
deployment-beta
deployment-alpha
```

To just use `deployment` + some variables.

**Comment by Gaunish** [comment]
I would like to be assigned this issue.
Thank you!

**Comment by dadiorchen** [comment]
@Gaunish waiting for you for a long time :D did you join our community already? may I ask what's your name on it?

**Comment by dadiorchen** [comment]
Let me know if you need any assistance.

**Comment by Gaunish** [comment]
> @Gaunish waiting for you for a long time :D did you join our community already? may I ask what's your name on it?

@dadiorchen Sorry for delays! I have joined the community with name Gaunish. Looking forward to talking with you :D

**Comment by emmanue** [comment]
Done.

**Comment by dadiorchen** [comment]
@emmanue where can I find the change of this?

**Comment by emmanue** [comment]
@dadiorchen you can find it on the beta branch. We can discuss this further during the meeting.
