### ISSUE TITLE
Disable map bounds on admin dashboard

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1469]
# Description

Disable the map bounds for the /admin pages. There is no need to display the bounds since we have inputs for them.

To reproduce
- visit: https://next-dev.treetracker.org/admin/global
- click on the map tab
- move the map

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by muhon9** [comment]
@RubenSmn bounds in the address bar, right?

**Comment by RubenSmn** [comment]
Yes correct @muhon9

**Comment by RubenSmn** [comment]
@muhon9 how are you doing on this task?

**Comment by RubenSmn** [comment]
@muhon9 no worries. That is great! The best thing is to open a PR so we can review and improve if needed
