### ISSUE TITLE
Navbar not displaying

### ISSUE THREAD

**Issue by pierrelstan** [Greenstand/treetracker-web-map-client#1471]
The navbar is not displaying, returning server error, and "useConfigContext" is not defined.

The Navbar is expected to be displayed in a specific format that adheres to the project's design specifications and functionality requirements.

![homepage](https://user-images.githubusercontent.com/23443242/225063715-7a3daecb-2024-47e4-9072-da4b8d15af18.png)

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
I think @RubenSmn has solved this

**Comment by RubenSmn** [comment]
This is solved by https://github.com/Greenstand/treetracker-web-map-client/pull/1474
