### ISSUE TITLE
Page error when clicking a link here

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1486]
<img width="874" alt="image" src="https://user-images.githubusercontent.com/5744708/226225305-a081f306-1d36-4c3e-83ed-d105dc761bad.png">

when clicking tree#319323, the app crashed!

https://beta-map.treetracker.org/trees/319323?bounds=-13.233633041381838,8.429073900016808,-13.202733993530275,8.446011787398255

**Comment by Khemendra-Bhardwaj** [comment]
Can you guide me which code file I have to modify

**Comment by dadiorchen** [comment]
You can join our community, we will guide you, can you send me you email ?

**Comment by dadiorchen** [comment]
This issue can not reproduce anymore
