### ISSUE TITLE
Improve Organization species planted section

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1496]
# Description

We can improve the **Species of trees planted** section by updating the elements. Currently the "list" is all made out of divs. We can improve this by using `ul` and `li` tags.

Check [here for the code](https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/pages/organizations/%5Borganizationid%5D.js#L336-L360).

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by Harshalyadav** [comment]
I'm not getting any data on the organization page in **Species of trees planted**.

**Comment by RubenSmn** [comment]
Hmm not sure, you could `npm run build` and then `npm run start` to locally run with the real data. [Here is a PR](https://github.com/Greenstand/treetracker-web-map-client/pull/1534) that has implemented this enhancement on a different page.

**Comment by Harshalyadav** [comment]
Ok, I try.

**Comment by RubenSmn** [comment]
Fixed by #1559
