### ISSUE TITLE
Improve Wallet species planted and token section

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1497]
# Description

We can improve the **Species of trees planted** section by updating the elements. Currently the "list" is all made out of divs. We can improve this by using `ul` and `li` tags. There is also a "list" for the tokens which should also be structured as a real list.

Check [here for the code](https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/pages/wallets/%5Bwalletid%5D.js#L314-L344).

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by pratham-yuxo** [comment]
I can work on this issue , you can assign this to me and can you tell me in which file this " Species of trees planted " section is?

**Comment by RubenSmn** [comment]
Yeah great @pratham-yuxo the file is in `src/pages/wallets/walletid.js`
