### ISSUE TITLE
Add `time` elements on token page

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1499]
# Description

The token page has multiple places where we display a date.

- Under the title
- When created
- Transaction history

Add a [time elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time) for the date.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by Ashwani2022** [comment]
Hay, I would like to work on that, assign it to me if possible.
-I am not able to find token page ,What is the path to the  file?
Thanks .

**Comment by RubenSmn** [comment]
Ye awesome @Ashwani2022 the file is at `src/pages/tokens/[tokenid].js`

**Comment by Ashwani2022** [comment]
Hi @RubenSmn 

I think I have solved the issue  
Here is the PR: https://github.com/Greenstand/treetracker-web-map-client/pull/1527
This is my first open Source contribution.
Can you please have a look?
Thanks,

**Comment by Ashwani2022** [comment]
Hi @RubenSmn

I have done the changes as suggested .
Here is the PR: https://github.com/Greenstand/treetracker-web-map-client/pull/1538
Can you please have a look?
Thanks,
