### ISSUE TITLE
Add `time` elements on organization page

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1501]
# Description

The organization page has some text where of the date since the organization was registered.
Add a [time element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time) for the date.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by pratham-yuxo** [comment]
can you tell me in which sections we have to change this. I don't know why but the site is not loading at this moment, and you can assign this to me.

**Comment by pratham-yuxo** [comment]
> # Description
> The organization page has some text where of the date since the organization was registered. Add a [time element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time) for the date.
> 
> Some hints:
> 
> * Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
> * For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
> * Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
> * To know more about our organization, visit our [website](https://greenstand.org).
> * If you want to join the slack community (some resources need the community member's permission), please leave your email address.
> * More issues in this project: https://github.com/orgs/Greenstand/projects/26

can you tell me in which sections we have to change this. I don't know why but the site is not loading at this moment, and you can assign this to me.

**Comment by RubenSmn** [comment]
@pratham-yuxo the whole organization page, everywhere there is a timestamp used we need to add the `time` element. Is there any error when the app is not working? If you're getting somekind of request timeout from a config api you can disable this feature in the `.env.development` its called something like this `...CONFIG_DISABLED=true`

**Comment by pratham-yuxo** [comment]
can you assign this to me?

**Comment by pratham-yuxo** [comment]
Is organization page is a part of this repo? Because my local host loaded like this and I am unable to find time stamps in this.

![Screenshot (290)](https://user-images.githubusercontent.com/111678040/232314937-dfca33be-88ca-4938-b0de-d674b9ef6784.png)
After clicking on Let's find a tree, I was getting a 500 error.

**Comment by RubenSmn** [comment]
@pratham-yuxo it looks like our services are having some issues. If it helps for now we have the deployed version running here: https://beta-map.treetracker.org/organizations/178

The code for this page is in `src/pages/organizations/[organizationid].js`

**Comment by pratham-yuxo** [comment]
> @pratham-yuxo the whole organization page, everywhere there is a timestamp used we need to add the `time` element. Is there any error when the app is not working? If you're getting somekind of request timeout from a config api you can disable this feature in the `.env.development` its called something like this `...CONFIG_DISABLED=true` and you can add the true part

After doing this website is running locally, but still localhost/500 is giving me error. I want to see my changes but its giving a unhandled runtime error.

Looks like an api call is failing.
![Screenshot (291)](https://user-images.githubusercontent.com/111678040/232405630-bafc0e5a-0894-47fb-b64e-8f368379476a.png)

**Comment by dadiorchen** [comment]
@pratham-yuxo are you in the Slack community? We encountered some cloud problem and working on it, so if you are in the #webmap channel on Slack, you will get updates for how things going on

**Comment by pratham-yuxo** [comment]
Thanks for telling me. I will join the slack channel now.

**Comment by RubenSmn** [comment]
I've invited you @pratham-yuxo

**Comment by pratham-yuxo** [comment]
look at this, Info component is like this
`              <Info
                iconURI={CalendarIcon}
                info={`Organization since ${moment(
                  organization?.created_at,
                ).format('MMMM DD, YYYY')}`}
              />`
but in mobile it is like this at some place,
`                <Info
                  iconURI={CalendarIcon}
                  info={`Organization since ${moment().format(
                    'MMMM DD, YYYY',
                  )}`}
                />`
There is no argument in moment(). I'm going to make time element at the info component. So, I have to pass some props.
I want to ask that why there is no argument. Is it a mistake or there is a reason.

**Comment by RubenSmn** [comment]
@pratham-yuxo this is a great finding! If you want you can make a PR to fix it 💪

**Comment by pratham-yuxo** [comment]
> @pratham-yuxo this is a great finding! It is a bug, if you want you can make a PR to fix it 💪

So, should I make a separate issue for this.

**Comment by RubenSmn** [comment]
Yes please
