### ISSUE TITLE
Improve the About the Organization section

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1502]
# Description

The "About the Organization" section can be improved by wrapping the content, including its title, in a [article element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article)

The code can be found in [`src/pages/organizations`](https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/pages/organizations/%5Borganizationid%5D.js)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by Harshalyadav** [comment]
@RubenSmn, Can you tell me more about wrapping the content and title in a article element.

**Comment by RubenSmn** [comment]
@Harshalyadav  thanks for looking into this. We have organization pages where we display some information about the organization. Currently we're not using semantic HTML to display the content instead we just use divs. To improve the SEO we should wrap / surround the about section in a proper `article` tag.

If you have more questions, I'm happy to answer them.

**Comment by Harshalyadav** [comment]
@RubenSmn, Thank you. If I will have any questions then I will ask you.
