### ISSUE TITLE
Restrict robots access to admin pages

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1505]
# Description

Restrict robots access to the **/admin** pages.
We don't want robots crawling the admin pages. There is no useful information there.
The [robots.txt can be found here](https://github.com/Greenstand/treetracker-web-map-client/blob/beta/public/robots.txt)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by Harshalyadav** [comment]
@RubenSmn, can you help me? husky rejected my commit, so what should I do?

**Comment by RubenSmn** [comment]
@Harshalyadav Can you share your error message?

Also if you want to leave your email, I can invite you for our Slack channel!

**Comment by Harshalyadav** [comment]
@RubenSmn, My email ID:-  harshalyadavkt@gmail.com

**Comment by dadiorchen** [comment]
@Harshalyadav yes, raise question in your channels, there are people who can help

**Comment by RubenSmn** [comment]
@dadiorchen there was a issue with the commit message, it was not following the conventional commit format.
