### ISSUE TITLE
The photo of planter is missing

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1509]
https://beta-map.treetracker.org/planters/8843?bounds=46.35099649429322,-15.723825719803592,46.3587212562561,-15.716327922881064

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/5744708/230245614-46464908-d2d4-46a9-8d71-4a20cd761647.png">

If there isn't a photo for the planter, we should display a default picture here rather than a blank
---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by 7pixel-cl** [comment]
Hello, I was looking for Open Source projects to contribute to, and I loved this one! May I take this issue?

**Comment by dadiorchen** [comment]
@7pixel-cl sure, thank you! please take it and raise pull request

**Comment by Adarsreg** [comment]
Could u please tell me where the styles are defined for the box component(inside which the image is rendered) in Profile Cover?

**Comment by dadiorchen** [comment]
@Adarsreg You need to folk and search the code, basically, we use MUI to build component.
