### ISSUE TITLE
Should show the map view correctly

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#151]
Now the home page didn't show the map view correctly, check screenshot below: 

Actually, the leaflet map view is bigger than what we are seeing, cuz we can not see the zoom control panel, which I guess is out of the browser window.

![image](https://user-images.githubusercontent.com/5744708/134764280-923618ad-9ad9-4d85-83ca-f208252cfbfd.png)

---
Some hints:
* Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
* Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
* To know more about our organization, visit our [website](https://greenstand.org).

**Comment by danp2392** [comment]
Hello, I would like to contribute to this issue please

I think there are two issues here?
1. The header and left info bar do not show on the live website
2. The map is out of bounds 

Is this correct?

**Comment by dadiorchen** [comment]
Yes, I guess the major problem is that the leaflet map object is set inappropriate, so it doesn't fit the current map view on the right, if you use devtool to inspect the map object in the browser, you will find it is bigger than the map container( the right half of the screen)

Please read the readme for more info, and if you use discord, you can find me here https://discord.gg/wUZPnnMB and chat with me for details.

**Comment by danp2392** [comment]
Can you assign this issue to me

Thanks

**Comment by dadiorchen** [comment]
So glad you can help us!

**Comment by danp2392** [comment]
Thanks, I have messaged you on discord :)
