### ISSUE TITLE
Web map integrate keycloak

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1514]

**Comment by RubenSmn** [comment]
I think [Auth.js](https://authjs.dev/) can be a great library to use for this. It can integrate with [Keycloak](https://next-auth.js.org/providers/keycloak) and provides auth on both server and client.

**Comment by dadiorchen** [comment]
@RubenSmn This is more like a Keycloak competitor, in Node.js, because we have tested the workflow to integrate with the client, so IMO it is fine to direct use the Keycloak client to do the integration.

**Comment by dadiorchen** [comment]
Transfer to https://github.com/Greenstand/treetracker-web-map-client/issues/1673
