### ISSUE TITLE
arguments not passed properly in mobile view

### ISSUE THREAD

**Issue by pratham-yuxo** [Greenstand/treetracker-web-map-client#1517]
### Description

In [organizatioid].js file, in desktop view info component is used like this :
![Screenshot (292)](https://user-images.githubusercontent.com/111678040/233476161-e9d71c2e-7c83-49fa-ad79-4c98fe10e681.png)

Here arguments while calling moment function is passed correctly but in mobile view it is like this: 
![Screenshot (293)](https://user-images.githubusercontent.com/111678040/233476174-e666f625-11b0-491f-8ed8-adc3ad47ca0f.png)
here, moment function is formatting the given date.

### Additional Information
What are your thoughts on this? If you have any suggestions you can tell me.
I want to work on this issue.

**Comment by sebastiangaertner** [comment]
I think we do not use the American date formatting. YYYY MMMM DD rather. 
DD Mon, YYYY

**Comment by pratham-yuxo** [comment]
> We do not use the American date formatting. YYYY MMMM DD rather. DD Mon, YYYY

I am not sure about that, that piece of code was taken from here https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/pages/organizations/%5Borganizationid%5D.js

**Comment by dadiorchen** [comment]
@pratham-yuxo I think we should simple pass in the same date as desktop

**Comment by pratham-yuxo** [comment]
> @pratham-yuxo I think we should simple pass in the same date as desktop

So, can I fix this issue by passing the same argument as in desktop.

**Comment by dadiorchen** [comment]
@pratham-yuxo yes, please
