### ISSUE TITLE
The cluster highlight icon is displaying incorrectly

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#152]
**Describe the bug**
The cluster highlight icon is displaying incorrectly, it might be because of some CSS problem.

**To Reproduce**

https://user-images.githubusercontent.com/5744708/134825876-03c80a97-1e18-44ae-aefb-b57b021f3c90.mov

**Comment by danp2392** [comment]
Hi, I would like to take a look at this issue.

**Comment by dadiorchen** [comment]
@danp2392 this issue just jumps out when we switch to the new site version(next.js), so for a reference, you can check out the `master` branch, where the highlight icon is working correctly.

Another thing, our tile server on dev env is breaking for some reason, our devops team is working on it.

**Comment by danp2392** [comment]
Yes I notice that the tile does not work on local host?
![image](https://user-images.githubusercontent.com/23002612/135239190-7fa5f9f6-5e07-46b0-92a7-eff18da70675.png)

**Comment by dadiorchen** [comment]
@danp2392 our cloud engineering team is tuning the kubenates, so the dev env was temporarily down, you can switch to test env for a work around:
![Uploading Screen Shot 2021-09-30 at 10.08.54 AM.png…]()

**Comment by danp2392** [comment]
Thanks, I will take a look at it

**Comment by dadiorchen** [comment]
@danp2392 are you in our community on slack?

**Comment by danp2392** [comment]
No, can you add me?

**Comment by dadiorchen** [comment]
Sure, please send me your email by dadiorchen@outlook.com or just leave it here. I will add you

**Comment by danp2392** [comment]
I sent you an email
Thanks

**Comment by danp2392** [comment]
Hello,

I have added the CSS code to make the clusters highlight
![image](https://user-images.githubusercontent.com/23002612/135671109-3ddc0577-1ce4-4a7b-82ff-3c42c050d5ea.png)

![image](https://user-images.githubusercontent.com/23002612/135671238-9fc2590a-6023-4002-9cc4-3e23bcc2905a.png)

Is this ok to commit?

**Comment by dadiorchen** [comment]
finished!
