### ISSUE TITLE
Search component on web map to search by city name

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1525]
Implement the search component to be able search by typing city name, as shown below UI design:

https://www.figma.com/file/kF69K6r81GxoV8eGCgtOFY/Greenstand-Webmap-(Copy)?node-id=8807-32240&t=aqFUa8pTvlmdRqkL-4

<img width="847" alt="image" src="https://user-images.githubusercontent.com/5744708/233924742-f487e24b-6751-4e4c-8905-4427bc457b67.png">

Because this is the first milestone of search service: https://github.com/orgs/Greenstand/projects/57/views/2 so let's make this component simple and focus on testing the search API: 
* Just display the component on the `full-screen` mode, not normal mode and mobile device.
* Just search by city name
* When clicking the city name listed below, simply fly to that location on map.

**Comment by muhon9** [comment]
@dadiorchen where can I find the APIs?

**Comment by dadiorchen** [comment]
@muhon9 the api is in progress, we are considering use raw Solr API at this stage, I will add you into the search channel to keep updated. So, for now, we don't have a API for you, if you can try to set up some Solr locally or remotely, that would be fantastic, but if not, our cloud team member is working on it.

**Comment by Mohmn** [comment]
@dadiorchen I THINK I HAD already implmented this component

**Comment by dadiorchen** [comment]
@Mohmn sorry for the chaos, @muhon9 please hold on this, I will go through all the things and re-org the issues here
