### ISSUE TITLE
rerouting wallet.treetracker to map.treetracker

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-web-map-client#1535]
https://wallet.treetracker.org/?wallet=forest.smoothie.secretspot

has to be 

https://map.treetracker.org/wallets/forest.smoothie.secretspot

Correct?

**Comment by dadiorchen** [comment]
Yes, do you need an auto-redirect for this, when people visit `?wallet=xxx` then redirect to `/wallets/xxx` ? What's the impact if we don't have this redirect?

**Comment by dadiorchen** [comment]
@emmanue we can assign this to someone

**Comment by dadiorchen** [comment]
@emmanue awosome!
