### ISSUE TITLE
Created-time component

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#155]
* File location: components/common/ folder
* Props: javascript Date object.
* Output, see UI below (in the red rectangle):
<img width="1440" alt="Screen Shot 2021-09-27 at 11 49 40 AM" src="https://user-images.githubusercontent.com/5744708/134842945-3de009c6-a52b-4127-9133-59e46eb9c565.png">

---
Some hints for building components:
* Design resource: https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=2497%3A11584
* A tutorial of how to use the Cypress component tool to build components: 
  https://github.com/Greenstand/treetracker-wallet-web#how-to-build-a-component
* We are using MaterialUI to build the app: https://material-ui.com/
* When you are ready to raise PR for the component, please attach the screenshot of the component for review.
* Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
* Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
* To know more about our organization, visit our [website](https://greenstand.org).

**Comment by markusiq** [comment]
Hello, can i work on this please?

**Comment by markusiq** [comment]
can you please assign me to this issue ?

**Comment by dadiorchen** [comment]
@markusiq sure!  Are you in the slack communitiy? If you want please leave you email!

**Comment by markusiq** [comment]
sure! my mail: mark.berty.berta@gmail.com

**Comment by dadiorchen** [comment]
finished!
