### ISSUE TITLE
Merge beta (recent changes) to main

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1551]
As this PR shown: https://github.com/Greenstand/treetracker-web-map-client/pull/1548 there are difference between beta and main, this is because we commit some newest code to beta, now we need to merge the beta to main.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by Harshalyadav** [comment]
@dadiorchen has the default branch changed?

**Comment by dadiorchen** [comment]
@Harshalyadav yes, but please hold on this PR, we will merge all those difference so your PR will be clear when we done that

**Comment by Harshalyadav** [comment]
ok
