### ISSUE TITLE
Design the login/authorization page

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1552]
We are going to customize the Keycloak login and social media authorization page to fit our UI style and logo and brand.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5744708/236754723-ade7ed0b-b83a-4702-a82d-69a757430333.png">

The requirements:
* Please go here https://dev-k8s.treetracker.org/test-client/ to try the things, we must follow the Keycloak login UX, which means the element and functionalities on the page are fixed and can not be changed, we just change the appearance of the page. (please message me on Slack for password) we will rewrite all the HTML + CSS and images, so as long as you respect the UX, we can do anything with HTML + CSS.
* Please design for Desktop and Mobile 
* This UI will be implemented by our antive app (android, IOS, React Native), please also take this in consideration.

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/5744708/236756259-5c3e4b28-2520-4a5f-ab82-a73ebdbb6526.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by Prasad-mutnale** [comment]
@dadiorchen I want to work on this issue. i can do a responsive login page please assign me this issue

**Comment by dadiorchen** [comment]
@Prasad-mutnale @pierrelstan is working on this, how about another design work, like this: https://github.com/Greenstand/treetracker-web-map-client/issues/1179
