### ISSUE TITLE
Make sure trees.uuid is lowercase

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1555]
- [x] fixing to disallow uppercase uuid
- [x] update all existing uppercase uuid to lowercase

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by Kpoke** [comment]
This has been resolved, we can close the issue

**Comment by dadiorchen** [comment]
Not yet, I didn't update all data yet

**Comment by dadiorchen** [comment]
I have deleted all those duplicated tree with upper case
