### ISSUE TITLE
When update the url with `bounds`, we should remain all other existing ones (parameters)

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1556]
Check the video:
https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202023-05-10%20at%203.29.45%20PM.mp4

**Describe the bug**

**To Reproduce**
(we recommend record a screenshot to show the case, like using http://loom.com to record)

**Expected behavior**

**Screenshots**

\*\* Node.js version
(The node version on your computer to run the project)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khalatevarun** [comment]
@dadiorchen do you mean that when the URL updates, it should not remove the bounds

**Comment by dadiorchen** [comment]
Not the bounds param, take a look this:
<img width="1378" alt="image" src="https://github.com/Greenstand/treetracker-web-map-client/assets/5744708/211bc3ac-8e13-49ac-af12-e1f292a58473">


The `tree_id=xxxx` shouldn't be removed if user move the map

**Comment by khalatevarun** [comment]
I have found the issue, but i am not able to reproduce it on local since the data for wallet is not present, it throws an error saying data not found

Could you please help me figure this out?
Am I missing something here?

**Comment by dadiorchen** [comment]
@khalatevarun thank for taking time to look at this, the URL: https://map.treetracker.org/wallets/tendry@bondy.earth?tree_id=5413738
So to reproduce it locally, you need to change the settings of .env to point to the prod data, by following this: https://github.com/Greenstand/treetracker-web-map-client/tree/main#misc

**Comment by henlam1** [comment]
@dadiorchen Hi! I found a solution. If this issue is still open, Id like to make a PR

**Comment by dadiorchen** [comment]
@henlam1 thank you! I will look into your PR
