### ISSUE TITLE
Location component

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#156]
* File location: components/common/ folder
* Props: coordinates, lat & lon
* Output, see UI below (in the red rectangle):
<img width="1440" alt="Screen Shot 2021-09-27 at 11 54 13 AM" src="https://user-images.githubusercontent.com/5744708/134843226-e5bb7cb1-1990-4b65-8e0d-a125d6fe21d8.png">
* API: will use the API created by #153 please mock the API if it is not ready yet.

---
Some hints for building components:
* Design resource: https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=2497%3A11584
* A tutorial of how to use the Cypress component tool to build components: 
  https://github.com/Greenstand/treetracker-wallet-web#how-to-build-a-component
* We are using MaterialUI to build the app: https://material-ui.com/
* When you are ready to raise PR for the component, please attach the screenshot of the component for review.
* Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
* Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
* To know more about our organization, visit our [website](https://greenstand.org).

**Comment by ozer619** [comment]
Hi, I'm new to opensource and react but I would like to work on this issue.

**Comment by ozer619** [comment]
I am getting this error when I tried to do npm install:
notsup Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})

**Comment by dadiorchen** [comment]
Oh, that's weird, what's the OS you are using? How about delete package-lock.json then try again? You can open a issue on this if there still is problem

**Comment by ozer619** [comment]
@dadiorchen I'm currently using the latest stable version of ubuntu also after deleting the lock file I get this error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: client@1.14.0
npm ERR! Found: eslint@6.6.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^6.6.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.16.0 || ^6.8.0 || ^7.2.0" from eslint-config-airbnb-base@14.2.0
npm ERR! node_modules/eslint-config-airbnb-base
npm ERR!   dev eslint-config-airbnb-base@"^14.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-27T10_10_17_305Z-debug.log
```

**Comment by ozer619** [comment]
Is it some problem from my side?

**Comment by dadiorchen** [comment]
Thanks!

**Comment by ozer619** [comment]
**Describe the bug**
The project crashes when we execute npm install on Ubuntu 20.04.3 LTS .

**To Reproduce**
Steps to reproduce the behavior:
(we recommend record a screenshot to show the case, like using http://loom.com to record)


**Expected behavior**
Should install all the dependencies but gives this error:
```
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-28T04_53_28_997Z-debug.log
```
After deleting the package-lock.json and re-executing npm install:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: client@1.14.0
npm ERR! Found: eslint@6.6.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^6.6.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.16.0 || ^6.8.0 || ^7.2.0" from eslint-config-airbnb-base@14.2.0
npm ERR! node_modules/eslint-config-airbnb-base
npm ERR!   dev eslint-config-airbnb-base@"^14.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/ozer/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ozer/.npm/_logs/2021-09-28T04_56_20_898Z-debug.log
```



** Node.js version
v16.9.1

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS

**Comment by dadiorchen** [comment]
@ozer619 I send you an invitation by your gmail so you might be able to do it in the future, and I opened this issue for you, I will take some time to run it in my ubuntu docker later, we will help you figure it out! And it's also necessary to make it working on ubuntu, our prod env is using it.

**Comment by ozer619** [comment]
Thanks!! @dadiorchen I'm really looking forward to contributing to this repo.

**Comment by ojafero** [comment]
Are you still working on this ozer619?

**Comment by ozer619** [comment]
Hi @ojafero I'm really really sorry I almost forgot about this Pr can you give me some time maybe 1 or 2 days I wanna try it out lowering my npm version and working on it .

**Comment by ozer619** [comment]
Thanks @QuaidBartolomei I will be working on this issue now can someone assign me this issue?
