### ISSUE TITLE
Uset Auth.js to do the login/registration

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1561]
We are using Keycloak as the oAuth solution for user/auth, so we can use https://authjs.dev/ to do the integration with Keycloak on our web map client.

- https://authjs.dev/reference/core/providers_keycloak

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by nileshkr17** [comment]
Hi @dadiorchen , I am Nilesh. 
I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. 
Thank you!

**Comment by jeremydthomas** [comment]
> Hi @dadiorchen , I am Nilesh. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you!

Have fun

**Comment by dadiorchen** [comment]
@nileshkr17 are you in the Slack? If you are, we have discussion here: https://greenstand.slack.com/archives/C0390C0PC3V/p1683961491316599 if you are not you can send me your email so I can invite you.

**Comment by nileshkr17** [comment]
> @nileshkr17 are you in the Slack? If you are, we have discussion here: https://greenstand.slack.com/archives/C0390C0PC3V/p1683961491316599 if you are not you can send me your email so I can invite you.

iamnileshsum@gmail.com
