### ISSUE TITLE
website link is not working!

### ISSUE THREAD

**Issue by Iamdivyak** [Greenstand/treetracker-web-map-client#1562]
**Website is not working**
it says "upstream connect error or disconnect/reset before headers. reset reason: connection failure"

<img width="954" alt="image" src="https://github.com/Greenstand/treetracker-web-map-client/assets/102896170/b958b8d9-95ff-4a34-b49c-af59327be926">

\*\* Node.js version
latest

**Desktop (please complete the following information):**

- windows
- Browser - chrome
- Version - new

**Comment by dadiorchen** [comment]
@Iamdivyak can you help us test it again?

**Comment by Iamdivyak** [comment]
yes it's working fine now
<img width="948" alt="image" src="https://github.com/Greenstand/treetracker-web-map-client/assets/102896170/8740998e-18d2-48db-a64c-b305145942b2">

**Comment by dadiorchen** [comment]
Thank you for helping us test it
