### ISSUE TITLE
The layout of the home page crashed

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1574]
<img width="1440" alt="image" src="https://github.com/Greenstand/treetracker-web-map-client/assets/5744708/2cebafd2-a8a0-49b7-ba7d-5eb20ca066c0">

https://map.treetracker.org/

**Comment by muhon9** [comment]
Loads perfectly on Chrome and Firefox but crashed on Safari

**Comment by dadiorchen** [comment]
For me, I crashed on Chrome too.

Does anyone know what happened?
