### ISSUE TITLE
Set up next.js to do not redirect to `/500` when encountering 500 error

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1580]
The `404` page is fine, as shown below:
<img width="1436" alt="image" src="https://github.com/Greenstand/treetracker-web-map-client/assets/5744708/7be4807d-c651-426f-ae47-bb6c81babcc5">

But the `500` page will cause the redirection:
<img width="1034" alt="image" src="https://github.com/Greenstand/treetracker-web-map-client/assets/5744708/19e8df51-a7ef-4316-b611-e6a631da3fd8">
We need to show the 500 but remain on the original URL

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by muhon9** [comment]
@dadiorchen I am checking this issue

**Comment by jeremydthomas** [comment]
> @dadiorchen I am checking this issue

assigned

**Comment by dadiorchen** [comment]
@jeremydthomas thank you, I'm trying to push the v2 and merged you and others code, there are really progress has been made by you gays, thank you for your contribution: https://github.com/orgs/Greenstand/projects/62/views/1

**Comment by jeremydthomas** [comment]
@dadiorchen you are welcome, wish I could be active again, but I've been working 90 hour weeks for the past few weeks with no end in sight. I'll try to pick up a few easy things here and there that doesn't take much thinking. I'm just too tired too think too much lately.

**Comment by dadiorchen** [comment]
:D take a rest, no worries, I will maintain this project board, just take the thing you can cover for now, maybe a little task, or just give people some guiding is priceless for Greenstand too

**Comment by dadiorchen** [comment]
This issue is open for contributors

**Comment by aayushgauba** [comment]
@dadiorchen I would like to give this a try thanks

**Comment by dadiorchen** [comment]
@aayushgauba thank you!
