### ISSUE TITLE
Use `UUIDTag` for the capture id on `/top` page's featured capture card

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1581]
Please use our `UUIDTag` to shorten the id here:

<img width="1146" alt="image" src="https://github.com/Greenstand/treetracker-web-map-client/assets/5744708/6ec51946-275a-46e8-b192-3d4f287aa9a7">

---
some hints:
- What's our `v2` feature for web map: https://docs.greenstand.org/web-map/v2-web-map
- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines check out our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the Slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
And also here:
http://localhost:3000/v2/captures/0c2d6e3a-d02a-4edf-bcdc-893e1f7a4817?bounds=-122.51961708068849,38.358820555449086,-122.50416755676271,38.37103506452526
<img width="739" alt="image" src="https://github.com/Greenstand/treetracker-web-map-client/assets/5744708/7f63d1bb-7d0d-4f2f-abdc-ad0201b9c27c">

**Comment by khalatevarun** [comment]
Hey @dadiorchen ,
I check running the project on local, the three ids are coming shorter
I am on beta branch
![image](https://github.com/Greenstand/treetracker-web-map-client/assets/68511458/711f0e6b-b311-4d2f-931b-fbfcbbae123f)

**Comment by dadiorchen** [comment]
@khalatevarun please note, this is our v2 project, check out this:  https://docs.greenstand.org/web-map/v2-web-map

**Comment by dadiorchen** [comment]
I checked it again, it works on my side, did you remove your `.env.local` to make sure you are using the default settings for this v2?

Here is my log:
```
wait  - compiling /v2/captures/[captureid] (client and server)...
event - compiled client and server successfully in 6.7s (13080 modules)
Web Map Client version 2.3.0-v2.5
Web Map Client version 2.3.0-v2.5
url: https://dev-k8s.treetracker.org/query/v2/captures/0c2d6e3a-d02a-4edf-bcdc-893e1f7a4817 took: 1609
url: https://dev-k8s.treetracker.org/query/v2/growers/93a026d2-a511-404f-958c-a0a36892af0f took: 2450
url: https://dev-k8s.treetracker.org/query/v2/countries?lat=38.364922414&lon=-122.511893968 took: 1437
load org from planting_orgniazation_id
url: https://dev-k8s.treetracker.org/stakeholder/stakeholders/8b2628b3-733b-4962-943d-95ebea918c9d took: 1536
!!!! render the _app
webmap config {
  navbar: {
    logoUrl: 'http://localhost:3000/images/greenstand_logo.svg',
    items: [ [Object], [Object], [Object], [Object], [Object] ]
  },
  map: { initialLocation: { lat: '', lon: '', zoom: '' } }
}
app: isDesktop:  true


...
```
