### ISSUE TITLE
Wrong default image on this page

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1582]
On this page:
http://localhost:3000/v2/captures/0c2d6e3a-d02a-4edf-bcdc-893e1f7a4817?bounds=-122.51961708068849,38.358820555449086,-122.50416755676271,38.37103506452526
The second default image (with Greenstand logo) is wrong, please replace it with the first one (above it)
<img width="723" alt="image" src="https://github.com/Greenstand/treetracker-web-map-client/assets/5744708/00fb7546-bd7e-48e3-9be5-235fa7d34830">

---
some hints:
- What's our `v2` feature for web map: https://docs.greenstand.org/web-map/v2-web-map
- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines check out our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the Slack community (some resources need the community member's permission), please leave your email address.

**Comment by Aryan123-rgb** [comment]
Hii, I am interested in working this issue. Please assign it to me :)

**Comment by dadiorchen** [comment]
Yes, please :)

**Comment by Aryan123-rgb** [comment]
Sorry I am unable to find the desired webpage, the link mentioned on top of this page is directing to 500 page .Can you please help me out here .

**Comment by DevFaisal** [comment]
is it still open ?

**Comment by dadiorchen** [comment]
@Aryan123-rgb did you checkout the `v2` branch, read the guide here: https://docs.greenstand.org/web-map/v2-web-map

@DevFaisal you can take other issues here: https://github.com/orgs/Greenstand/projects/62/views/1

**Comment by Aryan123-rgb** [comment]
@dadiorchen I checked the v2 branch , the page is not loading 
![Treetracker by Greenstand - Google Chrome 19-05-2023 15_49_22](https://github.com/Greenstand/treetracker-web-map-client/assets/118872531/7dab10eb-f1b5-48db-9c3f-88bfcbd4f6c7)

**Comment by dadiorchen** [comment]
@Aryan123-rgb you don't need to change the host by /etc/hosts, did you do that? You just need to visit: http://localhost:3000

**Comment by Aryan123-rgb** [comment]
> @Aryan123-rgb you don't need to change the host by /etc/hosts, did you do that? You just need to visit: http://localhost:3000 

Nope I didn't changed the host page, I navigated through local host 3000 and found the v2 branch there

**Comment by Aryan123-rgb** [comment]
> > @Aryan123-rgb you don't need to change the host by /etc/hosts, did you do that? You just need to visit: http://localhost:3000 
> 
 Nope I didn't changed the host page, I navigated through local host 3000 and found the v2 branch there. In the navbar there is a section of treetracker. On clicking treetracker the show menu shows v2 section and inside the v2 section I saw this page

**Comment by Aryan123-rgb** [comment]
> @Aryan123-rgb you don't need to change the host by /etc/hosts, did you do that? You just need to visit: http://localhost:3000 

If you can just help me find the path of the mentioned page, I will be able to do the rest :)

**Comment by dadiorchen** [comment]
Yea, the steps could be:
1. Clone the repo
2. Checkout v2
3. npm run dev
4. visit the URL above: http://localhost:3000/v2/captures/0c2d6e3a-d02a-4edf-bcdc-893e1f7a4817?bounds=-122.51961708068849,38.358820555449086,-122.50416755676271,38.37103506452526

**Comment by dadiorchen** [comment]
This issue is open for everyone

**Comment by rishav2404** [comment]
I want to do with this.

**Comment by dadiorchen** [comment]
Please note, this is on v2

**Comment by rishav2404** [comment]
May I ask you how to run this code ?
This is not running on my device and throwing the error  that the "userAgentFromString" on line 215 in App.js is not a function.

**Comment by rishav2404** [comment]
I have fixed some launching problems in the files and now the App is running. I want to ask you how to push and where to push it ?

**Comment by dadiorchen** [comment]
Do you mean push/commit code? You should fold the repo and open new PR against v2 branch.

**Comment by MohitBansal321** [comment]
```
<InformationCard1
            entityName={`${grower.first_name} ${grower.last_name}`}
            entityType="Grower"
            buttonText="Meet the Grower"
            cardImageSrc={grower?.image_url || imagePlaceholder}
            rotation={grower?.image_rotation}
            // TODO: this wont work until growers page is completed
            link={`/grower-accounts/${grower.id}?keyword=${nextExtraKeyword}${
              isEmbed ? '&embed=true' : ''
            }`}
          />
```
as you see there if grower image is present then it display otherwise it display white image of greenstand logo which mention in your above image
@dadiorchen

**Comment by dadiorchen** [comment]
But the background in my comment is in dark? what's the case in your side?

**Comment by MohitBansal321** [comment]
no it is in white
