### ISSUE TITLE
The css layout can not be loaded on this page.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1583]
https://map.treetracker.org/organizations/178
<img width="1419" alt="image" src="https://github.com/Greenstand/treetracker-web-map-client/assets/5744708/a1c42c33-80d2-472d-a2aa-061381ae575e">

Browser: Chrome
OS: macos

Please help us analyze the problem.

**Comment by muhon9** [comment]
It seems good from my device 
<img width="1437" alt="image" src="https://github.com/Greenstand/treetracker-web-map-client/assets/79197160/a317ec94-2460-4922-8539-b4f451c78027">

**Comment by Technobromo** [comment]
I would like to contribute further let me know the details of your mac os and browser version for inspection.

**Comment by dadiorchen** [comment]
Thank you @Technobromo , my:
* Chrome: Version 113.0.5672.126 
* Macos: 10.15.7 

I have also received report from macos + Safari (maybe some old version)

**Comment by dadiorchen** [comment]
I disabled cache but still get the wrong thing:

![Uploading image.png…]()

**Comment by ankan945** [comment]
assign it to me

**Comment by dadiorchen** [comment]
@ankan945 sorry, I have found the reason for this, it is because of the customizable feature we are working on which is still in progress but we accidentally deployed it. @ankan945 thank you, might you like to try some other issues in the list?

**Comment by dadiorchen** [comment]
@Technobromo @ankan945 if you want to join our community to work with a lot of people comes from the whole world, please let me know
