### ISSUE TITLE
Add `tree-matched` badge on the `/captures/{id}` page

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1586]
UX: to the right of the `token not issued` badge, add a new badge, which:
* If the `capture` object's `tree_id` is not null, then the badge shows: `tree matched` with primary `green` color, and by clicking the badge, the page jumps to: `/trees/{tree_id}`
* If the `tree_id` is null, then the badge shows: `waiting for tree match` in grey color

http://localhost:3000/v2/captures/0c2d6e3a-d02a-4edf-bcdc-893e1f7a4817

<img width="566" alt="image" src="https://github.com/Greenstand/treetracker-web-map-client/assets/5744708/cf3ee2af-8ddc-44f1-a5f1-dfaffc1a9855">

---
some hints:
- Dev guides for `v2` feature: https://docs.greenstand.org/web-map/v2-web-map
- If you want to join the Slack community (some resources need the community member's permission), please leave your email address.

**Comment by pujxn** [comment]
Hey, I'd love to work on this, could you please assign it to me? @dadiorchen

**Comment by dadiorchen** [comment]
Yes,please take it

Dadior Chen

在 2023年5月20日，17:12，pujan parikh ***@***.***> 写道：

﻿

Hey, I'd love to work on this, could you please assign it to me? @dadiorchen<https://github.com/dadiorchen>

**Comment by pujxn** [comment]
hi, i've been struggling with this a bit- i've forked the repo, and checked out master. i see in the readme that it mentions the production site is still pulling from master, however, when i try to run the local version, it just shows me a world map, and nothing else that's on the prod site? not sure what i'm getting wrong here.

**Comment by dadiorchen** [comment]
@pujxn did you check out the `v2` ? as shown here:  https://docs.greenstand.org/web-map/v2-web-map

It is fine if the local dev is different with production env, because we connect to different DB for local dev, which means the dev DB.

BTW, if you want to join the community, please send me you email address.

**Comment by pujxn** [comment]
oh, i see- thanks @dadiorchen 

sure, my email is pujan.parikh2209@gmail.com

**Comment by dadiorchen** [comment]
@khalatevarun I have merged your work from main to v2, can you take a look if it is okay?

**Comment by khalatevarun** [comment]
changes seems to look good @dadiorchen

**Comment by dadiorchen** [comment]
But this one is about new badged `tree-matched` ? I just merged your code to v2

**Comment by khalatevarun** [comment]
You can check the v2 branch code in captureid file, changes are already done @dadiorchen

**Comment by dadiorchen** [comment]
@khalatevarun you are right!
