### ISSUE TITLE
Add the capture list on `/trees/{id}` page

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1587]
Please help us add the capture list of the current tree on this page:

<img width="1436" alt="image" src="https://github.com/Greenstand/treetracker-web-map-client/assets/5744708/6ca3fc17-f0c4-4725-bfd3-5da675f1ff30">

UX:
* Put it under the tree picture and above the planter card
* Reuse the component on the `/top` page for the image list, like the image below:
* Change the text to: `Captures match to this tree`
* By clicking the capture, jump to the capture page, which is: `/v2/captures/{capture_id}`
<img width="737" alt="image" src="https://github.com/Greenstand/treetracker-web-map-client/assets/5744708/d282fe78-1e5b-45c0-9353-d4e19667a3cd">

---
some hints:
- Please read this before you start: https://docs.greenstand.org/web-map/v2-web-map
- If you want to join the Slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
@manishhansal thank you, please, and note this issue is working on v2, please read the guide first

**Comment by manishhansal** [comment]
> @manishhansal thank you, please, and note this issue is working on v2, please read the guide first

Okay

**Comment by dadiorchen** [comment]
This issue is open for everyone

**Comment by khalatevarun** [comment]
Hey @dadiorchen would like to take this up

**Comment by dadiorchen** [comment]
@khalatevarun this one is important, thank you!

**Comment by khalatevarun** [comment]
Hey @dadiorchen , i am v2 branch but not able to load data for any tree page.
I am able to open the captures/[capturid] page but on clicking on the "tree matched" it is redirection to tree page with 404 not found error

**Comment by dadiorchen** [comment]
@khalatevarun we need to change the logic for the tree page, previously, we use `/trees/{id}` to fetch tree data, in `v2` we should use `/v2/trees/{id}`, basically, for the v2, we need always to request the query API v2, which means: dev-k8s.treetracker.org/query/v2/...

**Comment by dadiorchen** [comment]
Let me know if you still can not fix the problem

**Comment by khalatevarun** [comment]
still getting 404 here :(

**Comment by dadiorchen** [comment]
@khalatevarun push your code maybe I can take a look

**Comment by dadiorchen** [comment]
@khalatevarun did you solve the problem? If not, can you push your code to your branch and let me take a look?

**Comment by khalatevarun** [comment]
@dadiorchen i could not even start solving, since I am not able to open a tree page
I am v2 branch
I copy pasted env production into env development

Thats all I did

**Comment by dadiorchen** [comment]
@aayushgauba it might be also good to let you know about this discussion.

@khalatevarun I think the `.env.production` is problematic for v2, in the `v2` branch the `.env.development` is the correct one for dev/test, there are some v2-specific settings:
```
NEXT_PUBLIC_API=https://dev-k8s.treetracker.org/query/v2
NEXT_PUBLIC_API_V2=https://dev-k8s.treetracker.org/
NEXT_PUBLIC_TILE_SERVER_URL=https://{s}.treetracker.org/tiles/
NEXT_PUBLIC_TILE_SERVER_SUBDOMAINS=dev-k8s
NEXT_PUBLIC_TILE_SERVER_WEBMAP_API=https://dev-k8s.treetracker.org/webmap/
NEXT_PUBLIC_IMAGE_API=https://dev-k8s.treetracker.org/images
NEXT_PUBLIC_API_NEW=http://127.0.0.1:4010/mock
NEXT_PUBLIC_BASE=
NEXT_PUBLIC_CONFIG_API=
NEXT_PUBLIC_COUNTRY_LEADER_BOARD_DISABLED=false
NEXT_PUBLIC_SERVER_CONFIG_DISABLED=true
```

There is a reason for the necessity of `NEXT_PUBLIC_API_V2` but I forgot the details.

**Comment by dadiorchen** [comment]
basically, for `v2` we use `/query/v2` as the server api

**Comment by dadiorchen** [comment]
@aayushgauba what's the status of this issue?

**Comment by aayushgauba** [comment]
@dadiorchen working on it

**Comment by DylanJG01** [comment]
@dadiorchen https://github.com/Greenstand/treetracker-web-map-client/pull/1730 resolves this issue.

**Comment by dadiorchen** [comment]
@DylanJG01 I guess your comment doesn't follow the rule of github, so the issue didn't get closed automatically, like this: fixed: #xxx
