### ISSUE TITLE
BUG: Grower list in org map is showing more growers (hired planters) than there are (some are shown 3 times)

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-web-map-client#1589]
Looking at https://map.treetracker.org/organizations/1787
They have 4 growers registered but the list shows grower 8514 three times.

**Comment by aayushgauba** [comment]
Assign me on this one. I would like to give this a try

**Comment by jeremydthomas** [comment]
> Assign me on this one. I would like to give this a try

Done

**Comment by dadiorchen** [comment]
Thank you guys we have solved this issue by: https://github.com/Greenstand/treetracker-query-api/pull/336
