### ISSUE TITLE
rename the `integration` under `Cypress` to `tests`

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#159]
![image](https://user-images.githubusercontent.com/5744708/134867106-01a57445-b2d7-42fd-901b-079fdc62ee9e.png)

**Comment by dadiorchen** [comment]
The default folder for Cypress to find all tests is `integration` could we find a settings for this to change it to another folder name?

**Comment by mrtillman** [comment]
@dadiorchen - hey I will work on this one. thanks.
