### ISSUE TITLE
A CI problem: `npm ci` can not run successfully 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1590]
We received report of failing CI action here: https://github.com/Greenstand/treetracker-web-map-client/actions/runs/5030293553/jobs/9043998889

But recently we didn't update the package-lock.json file, and if we download the `main` branch and run `npm ci` it works.

**Comment by GTRekter** [comment]
I've investigated the issue, and it seems to be related to the environment configurations. I ran the same command on both branches, and it failed when triggered from a GitHub Codespace. Here are the details of my setup:
```
@GTRekter ➜ /workspaces/treetracker-web-map-client (main) $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
@GTRekter ➜ /workspaces/treetracker-web-map-client (main) $ node --version
v19.9.0
@GTRekter ➜ /workspaces/treetracker-web-map-client (main) $ npm ci
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
...
```
However, when I ran the same command on my local machine, it worked fine. Both environments use the same NPM and Node versions, and I cleared the cache before running npm ci.

**Comment by dadiorchen** [comment]
@GTRekter thank you for helping us! This is because of wrong settings for npm, details are here: https://github.com/cypress-io/github-action/issues/922 basically, the node version and config for npm makes the npm ci behavior differently in envs.

**Comment by dadiorchen** [comment]
I will close this issue because after regenerate the lock file, everything is fine now.

**Comment by dadiorchen** [comment]
@GTRekter if you want please help us on other issues
https://github.com/Greenstand/treetracker-web-map-client/issues?q=is%3Aissue+is%3Aopen+label%3Adevops
https://github.com/orgs/Greenstand/projects/41/views/1
