### ISSUE TITLE
The app crash on a tree icon clicking (mobile version)

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1617]
To reproduce, open the devtool and switch to mobile device, open URL: https://map.treetracker.org/trees/32454?bounds=36.647193431854255,-1.1317327736449243,36.65607690811158,-1.1140550473449335 then click any tree icon on the map.

Check this video:
https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202023-05-30%20at%2010.22.56%20AM.mp4

<img width="652" alt="image" src="https://github.com/Greenstand/treetracker-web-map-client/assets/5744708/40f4a350-939e-43d0-aa64-2b2c2824144c">

The desktop version is fine, having no issue if clicking tree icons.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it.

**Comment by dadiorchen** [comment]
@tarunsamanta2k20 great, feel free to raise questions!

**Comment by tarunsamanta2k20** [comment]
@dadiorchen it is throwing 500.


`Status
500
Internal Server Error
VersionHTTP/1.1
Transferred273 B (21 B size)
Referrer Policystrict-origin-when-cross-origin
Request PriorityHighest`

**Comment by tarunsamanta2k20** [comment]
@dadiorchen it it not throwing on all icons clicks. some icons are working though.

**Comment by dadiorchen** [comment]
@tarunsamanta2k20 you are trying on the https://map.treetracker.org right? To debug it easily, you can run it locally, and connecting to the real data, so you will get the same result and print the next.js log on your computer, in this way, you can check what's happening.

Here is the guide to set it up: https://github.com/Greenstand/treetracker-web-map-client#how-to-connect-to-production-data-locally

**Comment by tarunsamanta2k20** [comment]
@dadiorchen I am getting error cannot find nearest location. Although it is obvious. But is there any method of getting location in your app.

**Comment by tarunsamanta2k20** [comment]
@dadiorchen looking like that for your provided bounds.

![image](https://github.com/Greenstand/treetracker-web-map-client/assets/55488549/266f591d-0e82-4e2d-839d-6322f6c964e9)

**Comment by dadiorchen** [comment]
@tarunsamanta2k20 this is the best PR for May, thank you!

**Comment by dadiorchen** [comment]
If you want to join our community, please send me your email.

**Comment by tarunsamanta2k20** [comment]
> If you want to join our community, please send me your email.

tarunsamanta77@gmail.com

**Comment by tarunsamanta2k20** [comment]
@dadiorchen please add me as an organization member.

**Comment by dadiorchen** [comment]
Thank you guys, this got solved
