### ISSUE TITLE
ImagePullBackOff in beta branch

### ISSUE THREAD

**Issue by emmanue** [Greenstand/treetracker-web-map-client#1618]
# Description
Fails to pull correct image
[comment]: # 'Description of the issue'
Failed to pull image "greenstand/treetracker-web-map-client:main": rpc error: code = NotFound desc = failed to pull and unpack image
To reproduce

[comment]: # 'To reproduce'

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by emmanue** [comment]
@dadiorchen  yes exactly. The wrong image is being pulled.

**Comment by emmanue** [comment]
Done.

**Comment by dadiorchen** [comment]
Awesome, what happened?

**Comment by emmanue** [comment]
A wrong image tag was used to deploy to the prod env by mistake for the beta branch.
