### ISSUE TITLE
Web map client, deploy the `main` branch  to `dev.treetracker.org`

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1620]
Currently, it is still the old (v1) version of the map. 
We are close to it, the app has been deployed to dev env on the k8s, just we need to set up the domain and set the router maybe good enough to finish this one.

**Comment by aayushgauba** [comment]
@dadiorchen I would like to work on this one. Thanks

**Comment by dadiorchen** [comment]
@emmanue thank you for making some many progress!
