### ISSUE TITLE
Create a slider input

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#1635]
# Description

With the new way of generating inputs made possible by #1619 we can improve our inputs. We would like to add a [slider input](https://mui.com/material-ui/react-slider/). 

It should at least have the following customization options:

- min
- max
- step
- unit

The config object for rendering the inputs can be found at [`src/models/themePlaygroundOptions.js`](https://github.com/Greenstand/treetracker-web-map-client/blob/61a9e2df258a9194b0c9df208e3c08686731bb1e/src/models/themePlaygroundOptions.js).
The place where the inputs are being rendered is [`src/components/playground/PropInput.js`](https://github.com/Greenstand/treetracker-web-map-client/blob/61a9e2df258a9194b0c9df208e3c08686731bb1e/src/components/playground/PropInput.js)

For building this I would recommend to first test the slider on one of the `fontSize` properties in the typography section.

NOTE: when working on this you should, checkout from the `cwm` branch, something like:

```sh
git checkout cwm
git checkout -b feat/cwm/slider-input
```

Feel free to ask any questions

The theme editor can be found on http://localhost:3000/admin/theme

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by khalatevarun** [comment]
@RubenSmn would like to pick this up!

**Comment by RubenSmn** [comment]
Awesome @khalatevarun let me know if you have any questions, and open a pr for feedback 👍

**Comment by RubenSmn** [comment]
Solved by #1653
