### ISSUE TITLE
Can not run the project on ubuntu!

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#164]
**Describe the bug**
The project crashes when we execute npm install on Ubuntu 20.04.3 LTS .

**To Reproduce**
(we recommend record a screenshot to show the case, like using http://loom.com to record)

**Expected behavior**
Should install all the dependencies but gives this error:
```
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-28T04_53_28_997Z-debug.log
```
After deleting the package-lock.json and re-executing npm install:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: client@1.14.0
npm ERR! Found: eslint@6.6.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^6.6.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.16.0 || ^6.8.0 || ^7.2.0" from eslint-config-airbnb-base@14.2.0
npm ERR! node_modules/eslint-config-airbnb-base
npm ERR!   dev eslint-config-airbnb-base@"^14.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/ozer/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ozer/.npm/_logs/2021-09-28T04_56_20_898Z-debug.log
```

** Node.js version
v16.9.1

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS

**Comment by QuaidBartolomei** [comment]
This same error occurs on Ubuntu v16.04 LTS as well with npm v14 and v16. Switching to npm v12 seems to get around the issue. I will continue working on this to get npm v16 able to install the dependencies without the package-lock

**Comment by QuaidBartolomei** [comment]
The problem was with the existing yarn.lock file. The project installs fine with node 16 after deleting node_modules/, package-lock.json and yarn.lock. Is the yarn.lock file being used? If not we should delete it.

**Comment by dadiorchen** [comment]
@QuaidBartolomei thanks, can you raise a PR for this? you can simply delete the old one, and upload the new one, we will align with yours.
