### ISSUE TITLE
Can not visit trees/id directly

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#165]
http://localhost:3000/trees/1

It's working to jump to this page by home page ---click--> top page ---click---> trees/1 , but can not open it directly in the browser, this is because in this way, the map context still isn't ready when try to manipulate the map object.

**Comment by dadiorchen** [comment]
![image](https://user-images.githubusercontent.com/5744708/135198206-d159a414-b38b-4fa4-9764-813be6171b32.png)

**Comment by jamalvarez** [comment]
@dadiorchen  I have created a PR for this: #167  

Might be too simplistic? is there any concern with map object being updated and causing that code to be executed more than needed?

**Comment by dadiorchen** [comment]
I will applause simplicity rather than complain about it :D , please see my comment on the PR
