### ISSUE TITLE
Fix integration test: `top.cy.js`

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1667]
On the `v2` feature, the integration test: top.cy.js is broken, to reproduce it:
1. Checkout `v2` branch
2. `npm i`
3. `npm run cy`
4. On dashboard, choose e2e test, choose integration `top.cy.js` 
5. You can see the error message

---
some hints:
- Please read this before you start: https://docs.greenstand.org/web-map/v2-web-map
- If you want to join the Slack community (some resources need the community member's permission), please leave your email address.

**Comment by itsajay1029** [comment]
Can you assign this issue to me and explain on what needs to be done ? @dadiorchen ?

**Comment by dadiorchen** [comment]
@itsajay1029 thank you! this one is interesting, please be aware that we are using nock to mock the data, so I feel that this is basically we are missing some mock code, please read the readme about how does our integration test work.

**Comment by itsajay1029** [comment]
> @itsajay1029 thank you! this one is interesting, please be aware that we are using nock to mock the data, so I feel that this is basically we are missing some mock code, please read the readme about how does our integration test work.

Sure I will read them . Can you assign this to me ?

**Comment by dadiorchen** [comment]
Yes, it's yours now: @itsajay1029
