### ISSUE TITLE
Deploy `v2` to test env: `alpha-test.treetracker.org` 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1676]
Help us set up the Github Action and k8s settings (about domain) to deploy `v2` branch to domain: `alpha-test.treetracker.org`, we have done the deployment: `main` branch to `map.treetracker.org` so for this task, we just need to duplicate the workflow and change some settings. 

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by emmanue** [comment]
Done.
