### ISSUE TITLE
remove certain tags from the Tree info and rename Tree info to "Capture info"

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-web-map-client#1679]
Looking at this screenshot we no longer have the following pieces of information. Therefore those infopanels should be removed. 

GPS Accuracy
Morphology

see screenshot
![Screenshot 2023-07-04 at 20 13 45](https://github.com/Greenstand/treetracker-web-map-client/assets/3283800/bef5d792-99ef-4ecc-9a81-94858db9b900)

**Comment by sebastiangaertner** [comment]
@dadiorchen it would also be great to talk about the tags. There will be tags that are used by an organization during verification that are public and some are private. I think we need to extend the schema, admin panel and web map to show both.

**Comment by Ewan88** [comment]
#1680

**Comment by dadiorchen** [comment]
This could be a project board crossing repos and teams

**Comment by MohitBansal321** [comment]
Is this issue resolved?

**Comment by dadiorchen** [comment]
Yes
