### ISSUE TITLE
500 error on a wallet page

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1684]
500 error shows up on this: https://map.treetracker.org/wallets/%E3%82%B3%E3%83%BC%E3%83%92%E3%83%BC

This is our first Japanese wallet.

<img width="1419" alt="image" src="https://github.com/Greenstand/treetracker-web-map-client/assets/5744708/f309d575-9929-4478-ad27-3f484d782db0">

**Comment by dadiorchen** [comment]
@henlam1 we got a terrible error on this page, can you help us fix it?

**Comment by henlam1** [comment]
@dadiorchen I will try my best to look into this issue. Is this related to the pull request I made recently?

**Comment by henlam1** [comment]
I am also confused about the problem. Can you help me understand what the URL is trying to query and what's the desired output?

**Comment by dadiorchen** [comment]
by requesting that url locally I mean

**Comment by khalatevarun** [comment]
Hey @dadiorchen, i found the issue, please have a look at the PR

**Comment by dadiorchen** [comment]
@khalatevarun @henlam1 thank you! It seems good, let me merge and deploy it
