### ISSUE TITLE
Embed web map for mobile view

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1701]
If user accesses https://map.treetracker.org/trees/1017648?embed=true with mobile, as shown below, because the parameter: `embed=true` we should hide the head (the banner with logo and menu icon)

<img width="370" alt="image" src="https://github.com/Greenstand/treetracker-web-map-client/assets/5744708/b8ea11ce-4e4b-4187-8251-b82ec32a9fc9">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by shivm29** [comment]
Hey @dadiorchen ! I think i can help.. Please assign this to me.

**Comment by dadiorchen** [comment]
It's yours now :)

**Comment by ratishjain12** [comment]
@dadiorchen so basically you want to hide nav header section when embed = true?

**Comment by dadiorchen** [comment]
Yes! Please let me know if you need anything

**Comment by ratishjain12** [comment]
Ok I am working on it will let you know
