### ISSUE TITLE
Fix integration test for `v2` branch

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1724]
The interaction tests for v2 are broken, majorly, this is because we changed to query v2 api, so we need to fix them by giving good mock data.

To run the int test: `npm run cy`, you can first checkout `main` and run it to check how it run successfully, then try to fix the broken ones in `v2`.

**Comment by DylanJG01** [comment]
I will try to take this on.

**Comment by dadiorchen** [comment]
This is fixed by @DylanJG01 's PR
