### ISSUE TITLE
Set the theme for component building tool.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#173]
`npm run cyu` to build the component, but the theme of MatieralUI is missing, we need to find a convenient way to create the case for component building, to include the theme in the cy.js

As we discussed in this thread: https://github.com/Greenstand/treetracker-web-map-client/pull/171#issue-1011855945
---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).

**Comment by cpaule1811** [comment]
So we can just mount the ThemeProvider in every component test but perhaps there is a better way.

**Comment by QuaidBartolomei** [comment]
After doing some searching I found the recommended solution on the @cypress/react github page: [https://github.com/cypress-io/cypress/blob/master/npm/react/docs/providers-and-composition.md](https://github.com/cypress-io/cypress/blob/master/npm/react/docs/providers-and-composition.md)

Basically they suggest replacing the `mount()` function with a custom function like this:
```jsx
export function mountWithTheme(element) {
  mount(<ThemeProvider theme={appTheme}>{element}</ThemeProvider>);
}
```
