### ISSUE TITLE
Use 3rd part action to handle the semantic release

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1762]
Currently, we are using self-managed action to handle the semantic release, majorly, we need to handle this case:
* Multiple branch can working on different feature, and push code to that branch
* The branches can have some channel to distribute, like alpha, beta, which is defined in the semantic release rc file: `.releaserc`

So now we need to try to find some 3rd part lib can handle this and give a stronger support. Here are some candidates:

https://github.com/codfish/semantic-release-action
https://github.com/cycjimmy/semantic-release-action

The goal is setting 3rd part action to do the semantic release, satifys the two points mentioned above.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by RingoTC** [comment]
I can do it. Please assign it to me.

**Comment by dadiorchen** [comment]
Or to try the new 3rd part action, we can start from an easier case: the query API, so to deploy the query API using the 3rd part action, and deploy to different channel.
