### ISSUE TITLE
Move capture page path from: `/v2/captures/{id}` to `/captures/{id}`

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1768]
http://localhost:3000/v2/captures/0c2d6e3a-d02a-4edf-bcdc-893e1f7a4817?bounds=-122.51961708068849,38.3588710328682,-122.50416755676271,38.370950949611135

this is current capture page, we need move the path to `/captures/{id}`, also, please write cypress integration test to cover this page.

---
some hints:
- Please read this before you start: https://docs.greenstand.org/web-map/v2-web-map
- If you want to join the Slack community (some resources need the community member's permission), please leave your email address.

**Comment by MrunalKashid02** [comment]
I know react but want to learn nextjs please can take these issue that I can try to resolve

**Comment by MrunalKashid02** [comment]
Can You add me to the slack my mail id is kashidmrunal0302@gmail.com

**Comment by MrunalKashid02** [comment]
Can you please add me to slack channel @dadiorchen

**Comment by MrunalKashid02** [comment]
Hey What I exactly me to do can you explain detail

**Comment by diveshdp** [comment]
hi, can i  take this issue?
