### ISSUE TITLE
Deploying to prod seems doing `npm build`

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#1782]
# Description

[comment]: # 'Description of the issue'

To reproduce

[comment]: # 'To reproduce'

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by Mohmn** [comment]
i probably missed to update the main DOCKER file
![Screenshot from 2024-06-05 23-02-28](https://github.com/Greenstand/treetracker-web-map-client/assets/37132584/6418ba27-fedd-4301-8560-d101d6d8ce7a)
![Screenshot from 2024-06-05 23-02-13](https://github.com/Greenstand/treetracker-web-map-client/assets/37132584/2b38e376-845d-4a97-9fa6-5ece1345456e)
