### ISSUE TITLE
Can we turn off some / all of the place names supplied by google maps layer?

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-web-map-client#18]

**Comment by mrtillman** [comment]
@dadiorchen - hey, I would like to do this one.

**Comment by mrtillman** [comment]
@dadiorchen - here is another demo, this time using the Leaflet library: https://curious-birth.surge.sh/main.html

so, I think it is possible to remove the place names, but I am having a very hard time getting this to work in the Treetracker app. the Treetracker code is not written like the Leaflet sample code, and the Treetracker app doesn't behave the same way.

I've also been researching [Leaflet.GridLayer.GoogleMutant](https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant), which appears to work the way we need, but I can't figure out why this won't work for Treetracker.

**Comment by dadiorchen** [comment]
Great! You made some real progress I think, just catch me on the slack we can co-work on this, and don't hesitate to raise new PR even though it doesn't work, so I can fetch your code and try it locally, you can create new PR with `draft` status, it's for code review that is still in progress, and also a good way to co-work and discussion!
