### ISSUE TITLE
Link passing Href to a tag

### ISSUE THREAD

**Issue by cpaule1811** [Greenstand/treetracker-web-map-client#181]
Next Link component won't always generate html a tag as child. This is needed for web crawlers to pick up the website for better SEO. 

The current code

<Link href="/" passHref>
         <Button className={classes.buttonStyle} variant="text" component="a">
            Contact Us
        </Button>
</Link>

![without a tag](https://user-images.githubusercontent.com/80873472/136471010-25d56be2-61ba-41ff-b0bc-13cb39b1aad2.PNG)

This code fixes it by using component props with any Mui component that is wrapped in a Next link component

<Link href="/" passHref>
         <Button className={classes.buttonStyle} variant="text" component="a">
            Contact Us
        </Button>
</Link>

![with a tag](https://user-images.githubusercontent.com/80873472/136471119-4f42d1e9-46d0-43e8-92f1-ac970920cd85.PNG)

@QuaidBartolomei mentioned another potential solution where we use custom Link components from Mui which I think by default is an anchor tag so that should work to I believe.

**Comment by QuaidBartolomei** [comment]
Here is a Link component used in Material-UI's with-nextjs example: [https://github.com/mui-org/material-ui/blob/v4.x/examples/nextjs/src/Link.js](https://github.com/mui-org/material-ui/blob/v4.x/examples/nextjs/src/Link.js). 

I tested it out and it uses an anchor tag, I will submit a pr with it implemented.
