### ISSUE TITLE
Upgrade the node.js to 16

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#182]
Set the project to use node.js v16 by default. and test it works well in aspects:
* the app: npm start
* the cypress integration: npm run cy
* the cypress component tool: npm run cyu
* the test: npm test (there might be some broken tests now, it's fine, just make sure jest can run on the 16)

ref: https://github.com/Greenstand/treetracker-admin-api/pull/595
---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).

**Comment by QuaidBartolomei** [comment]
I have not encountered any issues while using Node@16.11.0. We can add this to package.json to produce a warning when using `npm install` with incorrect Node version
```
	"engines": {
		"node": "^16"
	},
```
