### ISSUE TITLE
Weird Korean words on the map

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#199]
Don't know if it's machine-specific or browser-area-specific problem.

My computer is MacOS, Chrome, and the area is China but the system language is English.

The URL: https://map.treetracker.org/?&bounds=-25.091743469238285,-11.844166983148572,101.47075653076173,22.777764255287394

<img width="1440" alt="Screen Shot 2021-10-14 at 10 44 43 AM" src="https://user-images.githubusercontent.com/5744708/137242045-9f251514-e8a1-4b87-a037-36a3ca2a4558.png">

**Comment by dadiorchen** [comment]
Please checkout the `master` branch to work with

**Comment by dadiorchen** [comment]
@mrtillman did you encounter a problem like this?

**Comment by QuaidBartolomei** [comment]
@dadiorchen We discussed this in the team meeting, the issue came from using a proxy/vpn.
