### ISSUE TITLE
Update URL with bounding box so that current location of the map can be shared

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-web-map-client#20]
Similar to google maps, the URL of the treetracker map should contain the bounding box information for the location currently shown.  This should change as the user navigates in the map.  The user should be able to copy and paste this URL in order to share the current map view: when a URL with a bounding box query parameter is accessed, the map should move to the location of this bounding box.

For example, on maps.google.com we have: https://www.google.com/maps/@37.8508569,-122.2524834,17.11z

**Comment by deepwinter** [comment]
we found some issues with this PR.  query parameters are not retained in the URL when present.

**Comment by deepwinter** [comment]
this PR follows google maps, which was indeed our spec.. but upon review I see that @ also has a special meaning in our platform, the wallet handles, so we have to think differently about how we update the location in the URL.  

Some ideas for URLs, not sure which is best
https://dev.treetracker.org/@zaven,3.882756877719757,0.17578125,2z
https://dev.treetracker.org?map_name=freetown&location=3.882756877719757,0.17578125,2z

**Comment by deepwinter** [comment]
https://dev.treetracker.org/@zaven?focus=3.882756877719757,0.17578125,2z

**Comment by dadiorchen** [comment]
I think in our case, the easiest way is to just rewrite the path with the parameter we are using, so it's easy for us to get them from the path and then setting the map in correct state then request the server. 
like, this is the code we generate the request for server:

https://github.com/Greenstand/treetracker-web-map-client/blob/a9a02cc6c3b5bb921c7d39157686d0e64f572f28/src/map.js#L186-L205


So, if we can fetch the parameter and put then in the path, the next, when we open the app with the same url/parameters, we just need to pass then to the map object and request the server. Something like:

http://treetracker.org/?map_name=freetown&bounds=x,x,x,x

An extra thing that needs to do is to move the map to the bounds by the client.

**Comment by Maxfrank** [comment]
> I think in our case, the easiest way is to just rewrite the path with the parameter we are using, so it's easy for us to get them from the path and then setting the map in correct state then request the server.
> like, this is the code we generate the request for server:
> 
> https://github.com/Greenstand/treetracker-web-map-client/blob/a9a02cc6c3b5bb921c7d39157686d0e64f572f28/src/map.js#L186-L205
> 
> So, if we can fetch the parameter and put then in the path, the next, when we open the app with the same url/parameters, we just need to pass then to the map object and request the server. Something like:
> 
> http://treetracker.org/?map_name=freetown&bounds=x,x,x,x
> 
> An extra thing that needs to do is to move the map to the bounds by the client.

@dadiorchen Thanks for the suggestion, but there is some potential problem reusing bounds query param. When we get bounds information from URL, we cannot use it directly in mapOptions (needs zoom level and center info) in initializationn period, therefore we can only use map.fitBounds() later on to move the map position. But at the same time, we already started to track current bounds and rewrite the bound query param, therefore there would be some potential conflicts with reading and writing.
Currently use a new query param "focus=" in PR https://github.com/Greenstand/treetracker-web-map-client/pull/32, let me know you have some other thoughts, thanks.

**Comment by dadiorchen** [comment]
@Maxfrank sounds reasonable. Please hold on to this PR for a while, cause I am refactoring the workflow to fit the new cluster tile layer, and I will keep your idea in mind, and let's see how to figure it out when I reach the point.
In your code, did you reserve the filter like map_name=freetown in the URL?

**Comment by Maxfrank** [comment]
@dadiorchen Yes, all other filters are reserved and not influenced
