### ISSUE TITLE
Format the lat/lon coordinates value.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#201]
Can we change the format of the Lon and Lat as well. Its way too long. We should really just need 6 digits since that is already 10cm accuracy. No need to show more than that.

Note:
* Please create a util function for reuse.
* Please work on the branch: `master`

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by danp2392** [comment]
Sorry I have been busy, happy for someone else to take a look
