### ISSUE TITLE
Move the current timeline feature to the new filter component

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#212]
We already have the function of timeline, check the code in `master`, now we need to move the component of the timeline (on the bottom left corner) to the filter component and also move the logic into the new place.

The prerequisite of this issue: #211 

<img width="1440" alt="Screen Shot 2021-10-19 at 4 42 49 PM" src="https://user-images.githubusercontent.com/5744708/137876575-a34e40b4-9f97-4e7b-884f-4022b9d91d3c.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
Checkout the `master` there is the previous version of timeline:

![Uploading Screen Shot 2021-11-15 at 4.41.16 PM.png…]()

**Comment by dadiorchen** [comment]
You can directly try it on: map.treetracker.org

**Comment by pierrelstan** [comment]
I want to work on this one @dadiorchen

**Comment by dadiorchen** [comment]
@pierrelstan this has been finished, I will close it.
