### ISSUE TITLE
Implement the /trees/:treeId page.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#217]
Now we have had the integration test skeleton for the /trees/:treeId page: https://github.com/Greenstand/treetracker-web-map-client/blob/web-map-site/cypress/tests/integration/trees/%5Btreeid%5D.cy.js
Now we need to implement details of this page to follow our design, please work on the test above and implement all the details on this page.

![image](https://user-images.githubusercontent.com/5744708/138016762-5de554b6-0a6d-4556-a367-f680e7087353.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by QuaidBartolomei** [comment]
I already developed this page a bit while I was making the test cases, I'll submit a draft pr and finish it later unless someone else wants to take over.
