### ISSUE TITLE
Tree Icon can not highlight

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#228]
But the cluster icon does.

https://user-images.githubusercontent.com/5744708/138585518-b6201be9-648c-42bc-a50f-b0ea78404836.mp4

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
Hi, @akash5100 what can I do for you? How can we get you started? Are you in our slack channel?

**Comment by akash5100** [comment]
> Hi, @akash5100 what can I do for you? How can we get you started? Are you in our slack channel?

I am not currently on your slack channel but I wish I could join.

**Comment by dadiorchen** [comment]
@akash5100 I have sent you an invitation by the gmail you leave on your profile, can you confirm it?
