### ISSUE TITLE
Cypress will not run new component test files (no tests found)

### ISSUE THREAD

**Issue by QuaidBartolomei** [Greenstand/treetracker-web-map-client#229]
Currently if I try to make a new component test file (or duplicate an existing one) Cypress component tests (`cyu`) will say "No tests found" for that file.

If I delete my .next/ folder and restart cypress-ct the tests will work like normal but this must be done any time a new test file is created.

This seems to be an issue with the Cypress package and a fix is awaiting merge: https://github.com/cypress-io/cypress/issues/17920

**Comment by dadiorchen** [comment]
@QuaidBartolomei can we close this one now?

**Comment by QuaidBartolomei** [comment]
@dadiorchen Not yet, the issue of Cypress not working as intended still exists and we have `npm run cyux` as a workaround. We can close this after the cypress issue is patched.
