### ISSUE TITLE
Might be a next.js wrongdoing.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#253]
When the first time to visit the home page, and click the `find tree` button, the page will get refreshed rather then go forward to the link.

https://user-images.githubusercontent.com/5744708/140245554-83c68f81-b062-44f3-81cc-e601ac1b31ef.mov

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by echai-11** [comment]
I would like to work on this task.

**Comment by QuaidBartolomei** [comment]
This issue was fixed by the new setup with mui5 from this PR #287
