### ISSUE TITLE
Some problem when auto-refreshing the page by next.js dev mode.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#255]
When modifying js file, next.js will automatically reresh the web page, but sometimes it show error:
![image](https://user-images.githubusercontent.com/5744708/140249439-83c3bcb4-f26d-463d-9a92-00cb00e10884.png)

This is related to the map object mounting to the DOM, maybe we need a better way to mount the map object to the DOM

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by LahiaOmar** [comment]
Hey @dadiorchen, I would like to start working/fixing this bug
