### ISSUE TITLE
feature request; jump straight to tree view with single click

### ISSUE THREAD

**Issue by jwgatt** [Greenstand/treetracker-web-map-client#259]
It would be great to be able to jump from any zoom level straight to the single tree view/ground level on the map, as I find myself scrolling a lot when there should be a shortcut available. This would be a UX improvement in my opinion.

**Comment by dadiorchen** [comment]
By clicking where? If you updated newest data, and run the mock server, on the /top page, if you click the featured tree, you will be able to jump the single tree ground level.
