### ISSUE TITLE
Error thrown on clicking tree icon 

### ISSUE THREAD

**Issue by jwgatt** [Greenstand/treetracker-web-map-client#261]
I'm getting this error on clicking the tree icon in dev mode running the mock server.

It might be due to this;
> Note: _document.js is only rendered on the server side and not on the client side. so event handlers like onClick is not going to work.
https://stackoverflow.com/questions/51040669/next-js-use-of-app-js-and-document-js

![Screenshot from 2021-11-04 10-45-13](https://user-images.githubusercontent.com/79326421/140292375-d7d0a6a3-2247-4b1a-bbe1-ec0dcb336e1a.png)

**Comment by echai-11** [comment]
I am working on this bug.
