### ISSUE TITLE
Broken cypress test routes

### ISSUE THREAD

**Issue by VWRoli** [Greenstand/treetracker-web-map-client#267]
**Describe the bug**
TreeAge and Filter tests are broken, after the PR #263. I moved the common folder which broke some file routes.

**To Reproduce**
Start `npm run cyu`, will get a message 'Cannot GET /__cypress/src/index.html'.

**Expected behavior**
Tests should run as before.

**Screenshots**

![Screenshot from 2021-11-08 09-23-16](https://user-images.githubusercontent.com/31432331/140708281-494b95c1-f46f-4ffa-87bd-db4309344464.png)

\*\* Node.js version
16.11.0

**Desktop (please complete the following information):**

- OS: Ubuntu Linux
- Browser Brave, Chrome
- Version 95

**Comment by dadiorchen** [comment]
@YassinHussein is this written by you? did you check the test in cypress when you code?

**Comment by VWRoli** [comment]
> @YassinHussein is this written by you? did you check the test in cypress when you code?

No, it was me, I did #263. I broke the routes.

**Comment by YassinHussein** [comment]
@dadiorchen 
Sorry for the late reply.. Two weeks ago, a military coup took place in Sudan and the internet service was cut off so far

**Comment by dadiorchen** [comment]
@YassinHussein terrible! I hope you are well, and no worries on the things on Greenstand, so glad to see you back to us, you did a great job for us!
