### ISSUE TITLE
Repair jest and tests written by Jest

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#273]
We have some legacy tests written by Jest, (might be under the models folder), we need clean and repair these tests, the goal is: `npm test` could run and pass, because we will push forward to cover all those models with Jest test, and integrate these test into our CI

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by JulienMaurice** [comment]
Hello,
Could I do it ?

It seem that this is just an .env variable problem. The tests are waiting for `REACT_APP_API` but could take `NEXT_PUBLIC_API` to be validated.

**Comment by dadiorchen** [comment]
@JulienMaurice hey, sorry for the delay and missed your message, another developer has solved this problem, I'm so glad you are interested in our project, do you want to take a look at other issues? Actually, these three repo of us is aiming the same app:
https://github.com/Greenstand/treetracker-wallet-web
https://github.com/Greenstand/treetracker-web-map-core
https://github.com/Greenstand/treetracker-web-map-client
