### ISSUE TITLE
Write Jest test to cover requestAPI function

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#275]
https://github.com/Greenstand/treetracker-web-map-client/blob/4e6f680d124ae6d74c92bd501eda627919b32f26/src/models/utils.js#L46-L62

Write test in utils.test.js to cover the `requestAPI` function. Please note, there is a bug in the function, if the the request failed, like, receiving 404, for example, the server response with: code:404, json body: {msg: "some error message"}, the function will still successfully respond with the json body, this is a wrong behavior, the correct behavior should be: throw an error from this function.

It would be great if we can also write test code to cover this bug.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by LahiaOmar** [comment]
Hi @dadiorchen, I will try to work on this issue.

**Comment by dadiorchen** [comment]
Finished
