### ISSUE TITLE
Map view div with problem

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#279]
The div of the map container seems to be wrong, the map view on the half of the right can not show the whole map, part of the map is hidden by the div.

![image](https://user-images.githubusercontent.com/5744708/141267763-9f5e8d11-5c1c-4648-a399-2c0ac91d8292.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by bstetzer32** [comment]
Can I work on this one?

**Comment by dadiorchen** [comment]
It's yours, thanks!
