### ISSUE TITLE
UI/UX problem: who to deal with case like this:

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#280]
On the organization page, we are showing an org called: 180earth like this:
<img width="1440" alt="Screen Shot 2021-11-11 at 4 58 35 PM" src="https://user-images.githubusercontent.com/5744708/141268840-089f3626-9818-4afe-8253-d8206f188834.png">

How could we deal with a case like this, to make the logo showing more nice and neat?

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
For now, we can just put a white background behind it. If the logo itself is white, then we can change the background color to whatever color the organization uses.
![image](https://user-images.githubusercontent.com/5744708/142966485-afaddc9c-7c17-40df-874e-d932bed8abb3.png)

Lets make sure to give at least 16 pixels of padding for logo inside the circle

**Comment by pratikmdhr** [comment]
> 

Can I work on this??

**Comment by dadiorchen** [comment]
@pratikmdhr sure!

**Comment by pratikmdhr** [comment]
> @pratikmdhr sure!

Thanks!
