### ISSUE TITLE
Mobile version of home/index page.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#281]
Need to make the home page being able to fit a mobile devices.

![image](https://user-images.githubusercontent.com/5744708/141269863-0e0b9e3f-9805-44c7-83d3-c3b7f65f2f9a.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by lpizzinidev** [comment]
Hi @dadiorchen 🤚 Can I work on this issue?

**Comment by dadiorchen** [comment]
@lpizzinidev sorry for the delay, yes, please! do you want to join our slack community? if true, please give me you email, I will invite you.

**Comment by dadiorchen** [comment]
Anyone want to take this issue?
