### ISSUE TITLE
Font problem

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#291]
Can not find why the font in this page is different with the UI design file:

<img width="1438" alt="Screen Shot 2021-11-23 at 5 17 43 PM" src="https://user-images.githubusercontent.com/5744708/142998765-b3e7a7f3-fb30-424f-b78e-683d4a0204bd.png">
<img width="1438" alt="Screen Shot 2021-11-23 at 5 17 28 PM" src="https://user-images.githubusercontent.com/5744708/142998776-2d7c535d-f444-4804-985c-ed7f2081f9db.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
I copied the css style in Figma directly

**Comment by aphive** [comment]
Could be something with your css. Is it only showing the diff in the tool or on the site as well? I was not able to locate the pages on the site that you show in the screenshots.

In your css file I did notice that h4 has a different `fontWeight` than the others but not sure exactly what the tool is using to format the two different headings:

```
h4: {
      fontFamily: 'Montserrat',
      fontSize: '20px',
      fontWeight: 400,
    },
```

**Comment by dadiorchen** [comment]
@aphive thanks, you can jump to the page directly by `http://localhost:3000/top`
 
I'm afraid there is another problem in the page, #294
