### ISSUE TITLE
Web Map needs to open with left panel active with general information on what the map is about

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-web-map-client#3]
The https://treetracker.org site should open up with the left panel active. We need UX UI help to define what to display there. A short introduction (if no cookies are present) of the project and what this is about. Maybe a bit of statistics ... Amount of total tree tracking events, mabye statistic by continent, once in continent by country, or markers such as how many FMNR trees, social impact counter etc. 
Planter of the months, last active tracking, etc

**Comment by dadiorchen** [comment]
Put this issue to the icebox, generally, we will have a good solution in the new web map site design.
