### ISSUE TITLE
A showcase/sandbox of typography in this system/theme. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#301]
This task is pretty simple, just put all our typography into the component tool/sandbox, `npm run cyu`, so brings convenience when we need to pick typography according to our UI design.

![image](https://user-images.githubusercontent.com/5744708/143520356-ede6182c-4a69-472d-acbe-a50e300af27c.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by VWRoli** [comment]
I will take this
