### ISSUE TITLE
Refine the UI/layout of the tree tag component

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#302]
<img width="1440" alt="Screen Shot 2021-11-26 at 11 32 27 AM" src="https://user-images.githubusercontent.com/5744708/143522718-4f7fbd51-f307-490d-849e-d9b6f0e31164.png">

The design: 

![image](https://user-images.githubusercontent.com/5744708/143522737-45d1d246-e8d0-4fee-a2a9-eee825379143.png)

I guess this is about making the component responsive.
---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by VWRoli** [comment]
Working on it
