### ISSUE TITLE
Remove the background for the planter photo

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#303]
This is to build a beautiful profile page for our planter:

![image](https://user-images.githubusercontent.com/5744708/143524200-a077b247-5056-4bc0-ae6d-5f8fa3844285.png)

Some online image services already support this feature:

https://cloudinary.com/documentation/cloudinary_ai_background_removal_addon

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by KaranChandekar** [comment]
Hey dadiorchen, I am interested in your project and I want to contribute in this. can you tell more about from where I have to remove planter background. I mean can you give me more information about it!

**Comment by dadiorchen** [comment]
sure, @KaranChandekar are you willing to join our Slack community, if true, please give me your email, I will invite you, and about this task you can check out website: https://map.treetracker.org/?&bounds=-13.20829153060913,8.423979653340414,-13.17739248275757,8.440917764040844
by clicking any tree icon, you will find the tree panel showing up with the planter photo, the goal is to try to remove the background of the photo, so we can put it into our new website (as shown above) to make a beautiful profile for our planter.

<img width="1440" alt="Screen Shot 2021-11-26 at 5 06 11 PM" src="https://user-images.githubusercontent.com/5744708/143555688-5c37a94a-2b1d-4d16-becf-b583934064dc.png">

**Comment by KaranChandekar** [comment]
Ok! I understand this is my email : karanchandekar431@gmail.com

**Comment by dhanushreddy291** [comment]
Can I too give it a try?
My Email is: 29dhanushreddy@gmail.com

**Comment by dadiorchen** [comment]
sure, guys, I have invited you all

**Comment by dadiorchen** [comment]
hi, guys, any progress, question, thoughts on this?

**Comment by dhanushreddy291** [comment]
Sorry I was not working on it, because of my University exams. I will work on it definitely as i finish them.

**Comment by dadiorchen** [comment]
@dhanushreddy291 thanks! And a suggestion, that establishes discussion as early as possible, create **darft** PR as early as possible, so we can align with each other and in a correct direction

**Comment by dadiorchen** [comment]
This issue is open for everyone for an experiment or trying.
