### ISSUE TITLE
FeaturedTreesSlider supports small size

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#308]
We will reuse the slider on this page, with a property `size=small` so we can show a smaller one here:
https://www.figma.com/proto/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=2497%3A11031&scaling=min-zoom&page-id=2497%3A9322&starting-point-node-id=2497%3A11031&show-proto-sidebar=1

<img width="1440" alt="Screen Shot 2021-11-26 at 4 07 55 PM" src="https://user-images.githubusercontent.com/5744708/143547997-1d77c92d-60f0-49d5-a395-54b03f6e97d9.png">

---

Some hints for building components:

- This kind of issue is about creating a new component, it might not need to mount it in the whole app, to know how to create a component separately, please check the tutorial below.
- Design resource: https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=2497%3A11584
- A tutorial of how to use the Cypress component tool to build components:
  https://github.com/Greenstand/treetracker-wallet-web#how-to-build-a-component
- We are using MaterialUI to build the app: https://material-ui.com/
- Please mount the component with `import { mountWithTheme as mount } from '../../models/test-utils';` to get our theme imported.
- Please use MaterialUI `theme.spacing(x)` as possible as we can, so the component is more responsive
- When you are ready to raise PR for the component, please attach the screenshot of the component for review.
- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by pratikmdhr** [comment]
I'd like to work on this one

**Comment by dadiorchen** [comment]
It's yours now
