### ISSUE TITLE
A reusable component for image

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#311]
We need a reusable component to apply to any image element in the system, the function is that:
* A taken on icon indicating when do we take this photo
* A maximum icon that we can click to open a window displaying the full size of the picture.
* A like icon that we need the work from #310 

<img width="1440" alt="Screen Shot 2021-11-26 at 5 19 55 PM" src="https://user-images.githubusercontent.com/5744708/143557777-84b49825-2f6e-4f93-9bd9-de5593004638.png">
<img width="1440" alt="Screen Shot 2021-11-26 at 5 20 10 PM" src="https://user-images.githubusercontent.com/5744708/143557781-300d38c2-5348-44b4-959d-139dfc77fefa.png">

---

Some hints for building components:

- This kind of issue is about creating a new component, it might not need to mount it in the whole app, to know how to create a component separately, please check the tutorial below.
- Design resource: https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=2497%3A11584
- A tutorial of how to use the Cypress component tool to build components:
  https://github.com/Greenstand/treetracker-wallet-web#how-to-build-a-component
- We are using MaterialUI to build the app: https://material-ui.com/
- Please mount the component with `import { mountWithTheme as mount } from '../../models/test-utils';` to get our theme imported.
- Please use MaterialUI `theme.spacing(x)` as possible as we can, so the component is more responsive
- When you are ready to raise PR for the component, please attach the screenshot of the component for review.
- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by pierrelstan** [comment]
I would like to work on this issue, my email to join the slack community: stanleypl75@gmail.com

**Comment by dadiorchen** [comment]
@pierrelstan thank you, it's yours

**Comment by QuaidBartolomei** [comment]
@dadiorchen can this issue be closed?

**Comment by dadiorchen** [comment]
Sure!
