### ISSUE TITLE
Show the zoom in/out button on the bottom right corner

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#332]
<img width="1440" alt="Screen Shot 2021-12-02 at 3 33 29 PM" src="https://user-images.githubusercontent.com/5744708/144377798-54cc0289-da50-4469-b75d-ee90df91de09.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by LahiaOmar** [comment]
Hi @dadiorchen, I'm working on it!

**Comment by dadiorchen** [comment]
Hi, Omar, thank you, a reminder, the zoom in/out is a configurable feature by leaflet, so this issue might be related to how to expose it from core and set it up by client.

**Comment by dadiorchen** [comment]
This issue is open for everone
