### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#333]
Add back button code, I thought this is just a normal `go back` action, and the code is in PageWrapper.js

<img width="1440" alt="Screen Shot 2021-12-02 at 3 39 58 PM" src="https://user-images.githubusercontent.com/5744708/144378748-1e8e12e7-a875-4b3f-9d63-ff09980ba8a1.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dagmawig** [comment]
Has this issue been completely solved? It looks like you have press back button twice for it to work.

**Comment by dadiorchen** [comment]
Oh, you also encountered the problem right? 
I mentioned it in another issue: https://github.com/Greenstand/treetracker-web-map-client/issues/367
I'm not sure they are the same, but there also are some problems with it on my computer.

**Comment by dadiorchen** [comment]
@dagmawig maybe you can help to check the back button code and try to fix it?
