### ISSUE TITLE
Set up cypress command to run e2e test

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#337]
Currently, `npm run cy` will integrate next.js dev env automatically, now we need a command to just simply run the cypress without running the next.js.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
@QuaidBartolomei do you have any suggestion, I guess this is about avoiding loading the mock plugin right?

**Comment by dadiorchen** [comment]
The case is that the e2e test will direct connect to a real service, like the dev env of the web map siet.

**Comment by QuaidBartolomei** [comment]
I will look into this, there may be a way to pass a separate config file.
