### ISSUE TITLE
Error/warning component

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#341]
We need to show some error/warning message when the user operating on the app, for example:

![image](https://user-images.githubusercontent.com/5744708/144573608-0b455ed1-d930-4a87-966e-2131ea532cc4.png)

When people click the `submit` and there are some violations like: the start date is after the end date, then we need to show some warning to the user. 

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by arcadioramos** [comment]
I'll take this issue :) currently working on it

**Comment by dadiorchen** [comment]
Thank you!

**Comment by dadiorchen** [comment]
@pierrelstan how's your work on the filter?

**Comment by dadiorchen** [comment]
@pierrelstan this is about a reusable component, not just for this filter component, just in case I missed something.

**Comment by arcadioramos** [comment]
I've currently done the issue which name should I use for the pr?

**Comment by arcadioramos** [comment]
![image](https://user-images.githubusercontent.com/43447257/146485755-828bf10e-2fb2-4dfd-993b-ba3b14418947.png)
Any idea of why is this happening?

**Comment by dadiorchen** [comment]
@arcadioramos check this : https://github.com/Greenstand/treetracker-web-map-client#commit-message-and-pr-title-format

We have rule for commit message

**Comment by arcadioramos** [comment]
Thank you @dadiorchen  !!!
