### ISSUE TITLE
New theme for the mobile version

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#344]
We need a new theme for the mobile version. So we can switch the spacing/typography/font size...  with minimal effort between desktop and mobile versions.  

considering this use case: 

The words: featured tree in the two version, we are able to use consistant variant, say, h3, then we got different font setting for both.

<img width="1440" alt="Screen Shot 2021-12-04 at 4 58 27 PM" src="https://user-images.githubusercontent.com/5744708/144703795-7db9f981-8549-4308-81e1-145c5c8fc11f.png">
<img width="1440" alt="Screen Shot 2021-12-04 at 4 58 51 PM" src="https://user-images.githubusercontent.com/5744708/144703798-51e1139c-19f3-4f23-8c83-dd4902fe2d79.png">

Maybe this issue is also including some sorting-out jobs to go through the existing theme and enhance it in terms of the typography and spacing, and so on.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
@VWRoli what do you think about this? and you mentioned that you are going to sort out the messy theme, right? maybe you can consider the mobile them at the same time? So we got a united solution in both.

I'm thinking if we can use the theme field like typography and also some global classes, so we can easily switch the style between desktop and mobile?

**Comment by dadiorchen** [comment]
Maybe is hard, this job also need support from designer to being able to give a neat unified style guideline

**Comment by VWRoli** [comment]
Well, I can certainly take a look at it and we will see.

**Comment by VWRoli** [comment]
@dadiorchen The font sizes are doable with an intermediate theme in the theme.js. I'm currently working on this one.
The margins and paddings are a different topic. They are not consistent across the design like the font sizes. I will see what can I come up with.

**Comment by dadiorchen** [comment]
Great!
