### ISSUE TITLE
improve the swipe able drawer for the mobile

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#345]
To make the drawer more comfortable for users and more beautiful (layout).

![image](https://user-images.githubusercontent.com/5744708/144703977-9c2ab0e7-1b6a-439a-b307-59545758dc99.png)

A video to explain this feature:
https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202021-12-04%20at%205.17.53%20PM.mp4

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by pierrelstan** [comment]
Can I work on this? @dadiorchen

**Comment by dadiorchen** [comment]
Great! I think this is a challenging one, go ahead!

**Comment by pierrelstan** [comment]
Thank you
