### ISSUE TITLE
Adapt tree slider to mobile device.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#346]
<img width="1440" alt="Screen Shot 2021-12-04 at 5 32 24 PM" src="https://user-images.githubusercontent.com/5744708/144704745-22617187-6066-49a6-96cb-0735e281b121.png">

Please add a new test in component unit test file, and paste a screenshot when creating PR.

---

Some hints for building components:

- This kind of issue is about creating a new component, it might not need to mount it in the whole app, to know how to create a component separately, please check the tutorial below.
- Design resource: https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=2497%3A11584
- A tutorial of how to use the Cypress component tool to build components:
  https://github.com/Greenstand/treetracker-wallet-web#how-to-build-a-component
- We are using MaterialUI to build the app: https://material-ui.com/
- Please mount the component with `import { mountWithTheme as mount } from '../../models/test-utils';` to get our theme imported.
- Please use MaterialUI `theme.spacing(x)` as possible as we can, so the component is more responsive
- When you are ready to raise PR for the component, please attach the screenshot of the component for review.
- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by wendyyuchensun** [comment]
Hi, just curious does this need to be a new component? It seems like it can be achieved by just adjusting CSS like https://github.com/wendyyuchensun/treetracker-web-map-client/commit/2c022668419d4a5fd97eb94a109fcb66f791b0fe .
![ezgif-2-9d94ce75cb95](https://user-images.githubusercontent.com/13805499/144866194-3c31ffa1-582d-4974-a5f7-11b096188ec2.gif)

**Comment by dadiorchen** [comment]
awsome!!! yes, our goal is to reuse the component as much as possible, and your solution looks pretty neat! Can you raise a PR for us? 
BTW, the image size is the same as the Figma design? I mean the mobile version.

**Comment by wendyyuchensun** [comment]
Yes, mobile image is `152px * 152px` .
https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=4355%3A15745
<img width="1440" alt="Screen Shot 2021-12-07 at 2 09 13 PM" src="https://user-images.githubusercontent.com/13805499/144976034-1a944c2b-d042-4175-8f75-7782f7fb66f8.png">
,

**Comment by wendyyuchensun** [comment]
Here is the PR: https://github.com/Greenstand/treetracker-web-map-client/pull/352
Let me know if any issue with it, thanks. :)
