### ISSUE TITLE
A github Action task: add integration test and component test (if possible) into the RP checking

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#357]
If new people created a PR, the action should run and check if the cypress integration test could be passed or not.
Also, consider if we can add the component test into this checking workflow, but not sure its possible or appropriate. 

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by QuaidBartolomei** [comment]
I am working on this and fixing tests that are currently broken / not passing
