### ISSUE TITLE
Can not run Github Action to deploy.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#365]
There are some problem with the npm installment on the CI cloud, it seems related to the installing of `treetracker-web-map-core` , I tried: 
`npm install --save git+https://github.com/Greenstand/treetracker-web-map-core.git`
and:
`npm install --save github:Greenstand/treetracker-web-map-core` 
but no luck..

![image](https://user-images.githubusercontent.com/5744708/146137777-7b959719-e9c6-4d31-b30a-343d8b4ab696.png)

Check this link for details:
https://github.com/Greenstand/treetracker-web-map-client/runs/4530551687?check_suite_focus=true

**Comment by Siddhant-K-code** [comment]
It's working Now

Updated Test: https://github.com/Greenstand/treetracker-web-map-client/actions/runs/1590895567
