### ISSUE TITLE
Back button on organization page doesn't work

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#367]
![image](https://user-images.githubusercontent.com/5744708/146139387-5fb5c7a6-a230-47f3-a1a4-9f9d3be772f9.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by arcadioramos** [comment]
I've been trying to reproduce the error but the button works for me, is there any way to reproduce the error?

**Comment by dadiorchen** [comment]
Maybe this just happens on my computer?

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202021-12-17%20at%2011.27.19%20AM.mp4

**Comment by arcadioramos** [comment]
Maybe, I tried the same and it worked for me, kinda weird :/

**Comment by VWRoli** [comment]
It actually works on your computer too @dadiorchen. Take a look at the URL. When the map loads fully, the URL changes from `/organizations/1` to `/organizations/1/?bounds=...`. When you click back it goes back to `/organizations/1`, if you click again soon the page goes back to the tree page, but if you wait the URL changes again to  `/organizations/1/?bounds=...`. So you just have to click a couple more times. 

I'm not saying it is optimal, just saying that nothing wrong with the code. Just `router.back()` will not be enough to go back needs a more advanced solution.

**Comment by dadiorchen** [comment]
Yes, I think to solve this problem, we need to ignore the bounds URL in the history stack, which means, when we update the URL with bounds, we don't push it into the browser history stack
