### ISSUE TITLE
The reviewer notification is not working

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#371]
It should be working but don't know why it's not 
the setting is here:

https://github.com/Greenstand/treetracker-web-map-client/blob/web-map-site/CODEOWNERS

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by VWRoli** [comment]
I get emails about review requests.

**Comment by dadiorchen** [comment]
I'm not sure, sometimes, I request you for review manually...

**Comment by VWRoli** [comment]
Ohh, I don't know that. So technically I should get a notification email every time someone makes a PR? In which case I don't.
