### ISSUE TITLE
Module not found error; @emotion/cache

### ISSUE THREAD

**Issue by jwgatt** [Greenstand/treetracker-web-map-client#376]
When I run `npm run dev:mock` the project fails to compile, throwing a module not found error. See the image below.
On removing @emotion/cache, it throws on the next imported module.

I'm running the most recent build.

![Screenshot from 2021-12-19 23-56-37](https://user-images.githubusercontent.com/79326421/146693932-fddcbc7b-129d-4609-b17b-71acac926988.png)

Anyone else having this issue?

**Comment by dadiorchen** [comment]
Did you re install packages after checking out the new code? `npm i`

**Comment by jwgatt** [comment]
> Did you re install packages after checking out the new code? `npm i`

Yes. I'll fork it from master again in case its something local on my machine.

**Comment by dadiorchen** [comment]
Just in case you forgot, we are on `web-map-site` branch

**Comment by jwgatt** [comment]
Npm wasn't able to install the dependencies properly and kept on failing, so I used yarn to install and now it runs fine.
