### ISSUE TITLE
Merge time and location component

### ISSUE THREAD

**Issue by VWRoli** [Greenstand/treetracker-web-map-client#380]
The time and location component is basically the same, it could be solved with one reusable DataTag component.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
I was thinking a function or component to handle the location translation, like: give a coordinate then get the location name, so I planed a location component, but it's find you merge them together, we can consider using a function (or hook) to do it, yea, maybe this is a better solution.

**Comment by VWRoli** [comment]
We can still use a function or a hook, even if they are the same component. I think so at least:D
