### ISSUE TITLE
The mobile drawer should have a fixed title area

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#406]
As shown in the picture, the red box area is fixed, which means, when you want to scroll the panel (the whole area in the drawer) you need to touch the area under the red box, and, the area in red box can not be scrolled, it will be always fixed on the top.

Also, if you touch and pan the red box, the drawer will be moved.

<img width="1440" alt="Screen Shot 2022-01-14 at 5 56 36 AM" src="https://user-images.githubusercontent.com/5744708/149415468-1dc095c6-48d9-4269-9474-15e2541dc778.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by VWRoli** [comment]
> Also, if you touch and pan the red box, the drawer will be moved.

I don't think this is solvable without some complex reorganization. 
My first thought to implement this is to create a `TitleArea` component, place it into the org/planter page. Give it the fixed style required. This can return the children components. But this way we can't move the drawer with this.

_app > LayoutMobile > Dawer > PageWrapper > orgPage
To be able to pull the drawer we need this `TitleArea` component inside the drawer but that's way up in the 'component tree'. 
The data that this `Title` area gets is dynamic. 

Probably not my best explanation, so if you don't understand something let me know.
@dadiorchen Did you have some idea for this or theory how can this be solved?

**Comment by dadiorchen** [comment]
Yes, I got your point, there might be some difficulty when we want to build a dynamic-title-area-drawer, right?
@pierrelstan has done something relevant, what do you think, if I understand it correctly, you are putting the title area on your specific page, right?

**Comment by VWRoli** [comment]
> Yes, I got your point, there might be some difficulty when we want to build a dynamic-title-area-drawer, right? 

Yes, exactly.

**Comment by QuaidBartolomei** [comment]
![image](https://user-images.githubusercontent.com/59486980/150073129-b3fa62f4-14c5-4ac0-80de-77d77fccba77.png)
 
This is the current drawer. Perhaps this red area could be made transparent (removed) while the drawer button could still overlap this area to help with touch inputs.

Another issue I noticed is that the drawer will initially snap downwards when I begin dragging it upwards. This causes the drawer to always be offset from the touch input.

**Comment by QuaidBartolomei** [comment]
@VWRoli Did you consider a context provider? The nested `TitleArea` component could manipulate the `Drawer` with `useContext`. A `MobileLayoutProvider` could have a `drawerHeight` state property and `setDrawerHeight` reducer. The Drawer component would use this context to manage its height and any nested component could implement the reducer to manipulate it.

**Comment by dadiorchen** [comment]
So the drawerHeight state will control the height of the drawer? do think it will impact the performance of the UI because your drawer position need to bind with a React state?
