### ISSUE TITLE
Title area for planter page on mobile version

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#407]
<img width="1440" alt="Screen Shot 2022-01-14 at 6 05 49 AM" src="https://user-images.githubusercontent.com/5744708/149416574-2a775299-2c8d-443d-a34d-c5a82e5e5451.png">

Prerequisites: #406  
---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by RubenSmn** [comment]
@dadiorchen looking at the state of the current beta, I think this issue has been resolved
