### ISSUE TITLE
The continents on the map shouldn't be click able, and the cursor shouldn't change to pointer when mouse hoving on them.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#421]
https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-01-17%20at%205.04.59%20PM.mp4

**Comment by VWRoli** [comment]
`This XML file does not appear to have any style information associated with it. The document tree is shown below.`

I get the above error when I try to click on the video @dadiorchen

**Comment by dadiorchen** [comment]
@VWRoli my falt, can you try it again?

**Comment by VWRoli** [comment]
How do we display the tooltip if it is not clickable?

**Comment by dadiorchen** [comment]
The tooltip is displaying consistently.

**Comment by dadiorchen** [comment]
I mean displaying directly

**Comment by VWRoli** [comment]
So the tooltip will be always be shown. 
We get a continent name and that's where the tooltip will be shown right?
The user can't interact with the map.
Can we get multiple continents? Will we show multiple tooltips above multiple continents?

**Comment by dadiorchen** [comment]
You are right, currently, the case of the mutiple continents is impossible, so don't worry about that.

**Comment by VWRoli** [comment]
Where do we get the continent from? Do we have an API call for that? @dadiorchen

**Comment by dadiorchen** [comment]
I planed to get the continent by this:
https://dev-k8s.treetracker.org/query/continents?lat=8&lon=10
response:
{
  name: "Asia",
  id: 'xxxx',
  centroid: {geojson}
}

Because we still don't have the centre point coordinates for the org, I will use the first tree's coordinates(lat/lon) in this org to fetch the data

**Comment by dadiorchen** [comment]
All the things are temporary, sorry about that
