### ISSUE TITLE
Refine the planter photo layout

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#425]
Now, it's:
* Too big
* Maybe rounded convert is better, please refer to the UI design in Figma.
* Maybe need to tweak image/background layout to fit into the photo frame, the original photo direction usually is 'portrait', but our design layout is 'landscape'. 

![image](https://user-images.githubusercontent.com/5744708/150293551-fa4cadaf-7626-4d54-a6f2-2571fab80f8f.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by jwgatt** [comment]
On it.

**Comment by jwgatt** [comment]
Do we want something like this?
![Screenshot from 2022-02-06 16-38-50](https://user-images.githubusercontent.com/79326421/152688671-ba7c3f2e-2043-449d-aa65-31b4d5a12474.png)

**Comment by jwgatt** [comment]
Something like this?

![Screenshot from 2022-02-06 22-05-42](https://user-images.githubusercontent.com/79326421/152701540-3d9e1c70-a8d0-4e6a-a976-b48daca7e0a4.png)

**Comment by jwgatt** [comment]
@dadiorchen Something like this?
![Screenshot from 2022-02-06 22-05-42](https://user-images.githubusercontent.com/79326421/152701687-62695fe6-1158-4a33-8496-65636ed568bd.png)

**Comment by dadiorchen** [comment]
Yes, this is good, I think a smaller corner radius is better.
