### ISSUE TITLE
Implement a simple search function and result list

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#428]
<img width="1440" alt="Screen Shot 2022-01-20 at 4 50 53 PM" src="https://user-images.githubusercontent.com/5744708/150305065-15c5b07b-c9ec-4478-bf01-306b42ba3d9b.png">

The search function is simple, just be able to search by id, and use API: /trees/[id] /planters/[id]  and /organizations/[id] to fetch the exact id of the data, and show it in the list, then, click the item could be able to jump to the page of that item.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
Please also adapt the mobile version: https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=5336%3A18414
But, if the adaption is too complicated, consider implementing it with a separate component.

**Comment by mayankdp** [comment]
Hello, I have an assignment on Software Development Methodology where I have to contribute to an open-source repository. I am very interested in working on this issue. So can I work on this issue?

**Comment by dadiorchen** [comment]
Sure, thanks, @mayankdp I have assign this issue to you, and if you want you can leave me your email I will invite you into the Slack community.

**Comment by mayankdp** [comment]
Awesome. Thank you very much. 
Here is my email: mpatel9.com@gmail.com

**Comment by dadiorchen** [comment]
@mayankdp do you get any progress on this?

**Comment by mayankdp** [comment]
I have started working on it. Sorry, I do not have anything to report yet.

**Comment by mayankdp** [comment]
Hii @dadiorchen 
I need help with this. Do you think we can chat over discord and any other platform?

**Comment by dadiorchen** [comment]
@mayankdp I unassigned you off this issue because I'm pushing the app and did some progress on this, so this feature should be partially solved, but don't worry, we still get a lot of things waiting for contribution, I invited your in the slack, you can reach me on it!
