### ISSUE TITLE
Embed version of the map.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#429]
Basically, the online version now: http://map.treetracker.org is an embed version, just a map container, wither banner, panel on the left, just a raw box, so it's easy to be embedded into other websites, mobile apps, and so on.

So this issue is about implementing the map box the same as the map.treetracker.org, but, with the new UI design. 

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by RubenSmn** [comment]
@dadiorchen is there any implementation from where I can start or is it a whole new component?
Which frames of the figma design should I use as a reference, my guess is `Macbook Pro - 226` and neighbours.

**Comment by dadiorchen** [comment]
@RubenSmn I'm not sure about the status of this one, so I put it into the icebox for the time being. instead of this one, are you interested to challenge these:
https://github.com/Greenstand/treetracker-web-map-client/issues/431
https://github.com/Greenstand/treetracker-web-map-client/issues/515
If you are interested, let me know and I can give you details
