### ISSUE TITLE
A dark style theme of the whole app

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#430]
Because we need to embed the map to other partners' websites/apps, we need to be able to switch to a dark style appearance. 

This is an example: https://www.treetown.finorx.com/map?tree_name=future-beautiful-green

![image](https://user-images.githubusercontent.com/5744708/150308356-6a824cb9-eeda-4e7f-a206-2ad5aef50471.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
@VWRoli do you think it's possible?

**Comment by VWRoli** [comment]
I don't see why not. MUI can handle themes so I think it's doable. Assign it to me, and I will take a look at it more deeply.

**Comment by dadiorchen** [comment]
Yes, I think this is a meaningful feature, we are going to provide a way to customize the UI. And if you run into any trouble in terms of the UI we can definitely get our designer involved to help.

**Comment by dadiorchen** [comment]
@VWRoli don't hesitate if you need the help from the designer on this, I will establish the connection for you

**Comment by VWRoli** [comment]
> @VWRoli don't hesitate if you need the help from the designer on this, I will establish the connection for you

Alright, thank you. I haven't even started yet. Don't know what I will need yet.

I had to finish a personal project, but I will definitely start working on it this weekend.

**Comment by dadiorchen** [comment]
:D no rush @VWRoli
