### ISSUE TITLE
A mechanism to modify the them in a preview sandbox

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#431]
We are going to provide the greenstand map to other partners, so they can embed the map to their products, like websites, and mobile apps.

So we plan to offer an online sandbox to let our partners customize the appearance of the map app. Kind of like we do when we want to custom the theme of our Twitter profile.

At this early stage, don't need to consider the data storage and permission, just implementing a client sandbox, is good enough.

![image](https://user-images.githubusercontent.com/5744708/150309781-86579be2-116f-4ac0-b144-c01039507fbd.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
This is a use case for this kind of feature:
https://www.treetown.finorx.com/map
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5744708/156274461-695bfcea-3574-4100-88c9-26588bb4da86.png">

**Comment by dadiorchen** [comment]
Eventually, we want to implement something similar to https://bareynol.github.io/mui-theme-creator/

**Comment by dadiorchen** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5744708/175754668-6a9db08e-11a5-4f8e-a018-421be5802a60.png">

**Comment by RubenSmn** [comment]
@dadiorchen I would like to work on this one, can you fill me in on the details? Is there a design in the figma?

**Comment by dadiorchen** [comment]
I have done some work on this PR, https://github.com/Greenstand/treetracker-web-map-client/pull/644 is about login to dashboard and edit the theme, and the way to switch theme via localstorage, and we also created a new microservice to handle the map config for this. 
So now we are going to do an experiment to implement a visualized way to set the theme, as you see in the picture above. 
The UI for this is not so important, we just open this feature for the operator of greenstand. so I want to go forward to implement the function first, then back to improve the UI.
Maybe we can arrange a quick call on slack, and explain and show to you furtherly.

**Comment by dadiorchen** [comment]
About the keycloak, is an user system, so the map client doesn't care about user management, the user login via keycloak, and the the authorization to visit the dashboard of web map
