### ISSUE TITLE
Need to remove this default CSS property

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#434]
The typography element will automatically add the letter-spacing, but we can not find it in the project, we need to set it to '0';

<img width="1440" alt="Screen Shot 2022-01-22 at 11 04 39 AM" src="https://user-images.githubusercontent.com/5744708/150622555-38a27e0d-b967-4404-9af2-3d851419d1d8.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by Krish-bhardwaj** [comment]
Hi i am a fresher looking for some opensource contribution can u help me out i want to contribute to your project and can u assign me this project :)

**Comment by dadiorchen** [comment]
:) @Krish-bhardwaj sure, thank you!

**Comment by codyconway77** [comment]
I found a fix. Don't want to step on any toes and take away the opportunity from Krish-bhardwaj. Would it be ok to open a PR with my fix in just in case the issue goes stale?

**Comment by Krish-bhardwaj** [comment]
@dadiorchen i have solved this issue ( i am in my very early stages of my contribution this is my second opensource contribution requested to merge my PR )

**Comment by codyconway77** [comment]
I believe this is the fix. Referenced the MUI docs at https://mui.com/customization/theme-components/#global-style-overrides
```
const theme = createTheme({
  components: {
    // Name of the component
    MuiButton: {
      styleOverrides: {
        // Name of the slot
        root: {
          // Some CSS
          fontSize: '1rem',
        },
      },
    },
  },
```

**Comment by codyconway77** [comment]
#435

**Comment by dadiorchen** [comment]
@dark-teal-coder thanks, it's intresting, I wonder where the original left-spacing is from?

**Comment by keyy123** [comment]
Is this issue still open? I don't mind giving it a try! 😁👌

**Comment by dadiorchen** [comment]
@keyy123 thank you for helping on this
