### ISSUE TITLE
The like button animation is slow

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#445]
https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-01-29%20at%205.44.53%20PM.mp4

It makes more sense to keep the like button showing, so this issue is about simply removing the animation, showing the button permanently.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by Aman-Mandal** [comment]
Can I work on this issue?

**Comment by dadiorchen** [comment]
Yes, @Aman-Mandal :)

**Comment by Aman-Mandal** [comment]
Thankyouu :) ..I ll try to do this as soon as possible.
