### ISSUE TITLE
Use the API to display country name.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#446]
Please use the query API: /countries?lat=x&lon=x to display the country name for planter page.

![image](https://user-images.githubusercontent.com/5744708/151656477-5bb28eda-d2bd-4b2e-b4fc-7fdfe5408645.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by jwgatt** [comment]
We want the country of the planter displayed in the url?

**Comment by stellarjaysoftware** [comment]
I'm working on this one.  Should have a draft PR submitted tonight (Sun).
