### ISSUE TITLE
Broken flags

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#449]
There are several flags broken, please fix them.

<img width="1440" alt="Screen Shot 2022-01-30 at 11 32 44 AM" src="https://user-images.githubusercontent.com/5744708/151685657-e4d50657-acea-4f86-b125-1c99c1eb75f2.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by VWRoli** [comment]
It's an API problem @dadiorchen. As I described it in the PR.

> Tanzania is not working because the official English name of the country is "Tanzania, United Republic of" so we can't convert it to an ISO code. The same goes for Congo.
The solution to this is to either the API should return the country ISO codes so we can use them and avoid conversion. Or the names should be the correct official English names.

**Comment by dadiorchen** [comment]
Get it, but I thought correcting the data in DB is kind of time-consuming, maybe we could have some workaround?

**Comment by VWRoli** [comment]
We can fix the names with some conditional statements for the wrong country names.
