### ISSUE TITLE
Grey area appears on top of the map when it first loads

### ISSUE THREAD

**Issue by pratikmdhr** [Greenstand/treetracker-web-map-client#454]
**Describe the bug**
A grey area appears on top when the map first loads

**To Reproduce**
Steps to reproduce the behaviour:
Visit https://map.treetracker.org, when the map first loads with browser zoom level set at 100%, grey bar appears on top of the map

**Screenshots**
![grey-bar](https://user-images.githubusercontent.com/52301822/152449465-3ea827d9-8bfb-4939-9787-59829bf605bb.png)

**Desktop:**
- OS: Ubuntu 20.04.3 LTS
- Browser: Firefox and Chrome
- Version Firefox 96.0 and Chrome 97.0.4692.99
- Screen: 1920 x 1080

**Comment by dadiorchen** [comment]
My computer is macOS 10.15.7 monitor resulution:  (2560 x 1600) 
Browser: Chrome, there isn't the grey blank area.

**Comment by pratikmdhr** [comment]
I have Windows 10 on my system, and the grey area doesn't appear on Chrome. So may be this is a Ubuntu Issue?

**Comment by pratikmdhr** [comment]
> My computer is macOS 10.15.7 monitor resulution: (2560 x 1600) Browser: Chrome, there isn't the grey blank area.

I just tested it on Windows 10, and the grey area doesn't appear on Chrome. So may be this is a Ubuntu Issue?

**Comment by pratikmdhr** [comment]
> > My computer is macOS 10.15.7 monitor resulution: (2560 x 1600) Browser: Chrome, there isn't the grey blank area.
> 
> I just tested it on Windows 10, and the grey area doesn't appear on Chrome. So may be this is a Ubuntu Issue?

Its actually showing up on Windows too, its the same device and monitor.. OS - Windows 10 Build 19042, Monitor 1920 X 1080, 
![image](https://user-images.githubusercontent.com/52301822/152887502-abba9ee2-384d-4a2b-b1e4-3eaf7f69a775.png)

**Comment by pratikmdhr** [comment]
> > My computer is macOS 10.15.7 monitor resulution: (2560 x 1600) Browser: Chrome, there isn't the grey blank area.
> 
> ~I just tested it on Windows 10, and the grey area doesn't appear on Chrome. So may be this is a Ubuntu Issue?~

Its actually showing up on windows too.. Its the same system i use for Ubuntu.. OS - Windows 10 Build 19042, 100 % Desktop Scaling 1920 X 1080. Browser - Chrome Version 98.0.4758.82 100% Zoom level 
![image](https://user-images.githubusercontent.com/52301822/152887930-48b3595a-e0ef-44c3-b650-f162b48661e1.png)

**Comment by pratikmdhr** [comment]
@dadiorchen, I think its related to the scaling of OS and size of the monitor. The grey area seems to disappear if Desktop scaling of 125% is used on windows.. Also tried it on Ubuntu (text scaling 1.25) and it goes away.. 
So i guess this issue is related to not just the resolution of screen, but also the size of the monitor.. I'm using a 24" monitor with 1080p resolution with 100% scaling, thats why i notice the issue.. If i were to use a smaller size display like a 14" laptop screen, my scaling will be 125% and the issue will not be there

**Comment by cnohall** [comment]
I'm getting the same issue:

![image](https://user-images.githubusercontent.com/36883813/157025213-24809cd0-8909-4cdc-bbbc-a06dbcb776b4.png)

OS - Windows 11 Build 22000.493,
Resolution: (1920 X 1080),
Desktop Scaling: 100 %,
Browser - Brave [Version 1.36.109 Chromium: 99.0.4844.51 (Official Build) (64-bit)]
Browser Zoom Level: 100%

It's the same for me as for @pratikmdhr, that when I use a laptop screen with 125% scaling the issue disappears.

**Comment by dadiorchen** [comment]
I red in document of the leaflet that we can set the maximum map view. I’m not sure if it is a solution

**Comment by dadiorchen** [comment]
@cnohall thanks for helping test

**Comment by dadiorchen** [comment]
![Uploading 8C64CAFC-E8A2-4C9E-95F2-2755632FC1E3.png…]()
This is from my pad

**Comment by dadiorchen** [comment]
![A443B4CD-D41B-4946-8E07-4A387A3549B0](https://user-images.githubusercontent.com/5744708/157151623-a79a9c27-e7ed-4827-9366-324ef362bb78.png)
