### ISSUE TITLE
A solution to share/reuse components crossing repositories.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#461]
For example, the share components, they are the same between wallet app and web map app, so we need to find a good solution to share the components crossing repos.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
@QuaidBartolomei can you send the link of the component lib platform you mentioned before?

**Comment by QuaidBartolomei** [comment]
Here's the one that I mentioned: https://bit.dev

each component is managed as a separate npm package. You can browse public components on the site.

v15 (known as bit harmony) is still in beta. I think the component management is much easier in this new version:
 https://harmony-docs.bit.dev/getting-started/installing-bit/
