### ISSUE TITLE
The tree icon should be in selected mode when open a single tree's page

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#466]
like this: http://localhost:3000/trees/920811

![image](https://user-images.githubusercontent.com/5744708/153134904-bbb194f6-fb67-4342-ad56-73e78e732dd3.png)

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-02-09%20at%202.30.03%20PM.mp4

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by GabZhou** [comment]
Hi Dadior, I would love to work on this issue :)
