### ISSUE TITLE
Can not share/copy the url of online map to social media

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#485]
Please note, this is on the `master` branch.

https://dadior.s3.ap-northeast-1.amazonaws.com/Treetracker+by+Greenstand+-+Google+Chrome+2022-02-25+12-56-13.mp4

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
Great obersevation! But I see there are also commas in google's URL?

**Comment by dadiorchen** [comment]
Maybe we can avoid using commas? change to other chars like: '|' ?

**Comment by iib0011** [comment]
We can use https://map.treetracker.org/@-10.491943359375002,6.6973427326643975,6.383056640625001,14.82799134735208

**Comment by iib0011** [comment]
Yes ! works
