### ISSUE TITLE
[v1.0] to support wallet=[walletname]&token=[tokenid]

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#487]
We need the v.10 map to support: http://map.treetracker.orgwallet=ABC&token=[token_id]
Opening this URL, the map will jump to the single token/tree, with the logo of the wallet on the corner.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by sebastiangaertner** [comment]
Its 
[http://map.treetracker.org/?wallet=ABC&token=[token_id]](http://map.treetracker.org/?wallet%3Dabc%26token%3D[token_id]/)

**Comment by iib0011** [comment]
@dadiorchen Do you have an example url which should work
