### ISSUE TITLE
Background can not be set with the dark theme

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#499]
we need to set the background color properly.
https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-03-02%20at%2011.54.29%20AM.mp4

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by VWRoli** [comment]
I'll take a look at this. It was working properly in #467.

**Comment by dadiorchen** [comment]
oh, @VWRoli it's my fault
