### ISSUE TITLE
Font problem

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#501]
Now our Montserrat font is different from the Figma (the first one is our implementation, second one is from figma) 
<img width="370" alt="image" src="https://user-images.githubusercontent.com/5744708/156314995-d4abc76b-7b65-48a9-bfa0-7c8ec2133b7f.png">

<img width="486" alt="image" src="https://user-images.githubusercontent.com/5744708/156315067-7e63f001-ad33-4b5a-915e-cebbeb6d7529.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
Both the setting for the font is: 
```
    margin: 0;
    font-family: Montserrat;
    font-weight: 600;
    font-size: 32px;
    line-height: 39px;
    letter-spacing: 0em;
    color: #474B4F;
```
But they are different.

some clue: https://stackoverflow.com/questions/42619820/google-font-montserrat-in-chrome-no-rendering-light-font-weight

**Comment by VWRoli** [comment]
![Screenshot from 2022-03-02 18-03-57](https://user-images.githubusercontent.com/31432331/156411245-17ae7b34-f761-48f1-a9ee-17363f2eef1e.png)

I don't know. I see the difference in your image. On mine though, they seem to be the same, the first image is the Figma.

**Comment by mayankdp** [comment]
Hello @dadiorchen,
If this issue hasn't been resolved then I would like to work on this, if you allow me.
It looks like changing font size/weight should resolve this so I would like to try.
I am a University student and my professor gave us the assignment to do a contribution on Github by end of this month. And this issue looks doable by then.
I have experience in developing mobile as well as web applications.

**Comment by dadiorchen** [comment]
@mayankdp thanks, yes, please make a try.

**Comment by dadiorchen** [comment]
@mayankdp if this one ran into a dead end, you can also try this: https://github.com/Greenstand/treetracker-web-map-client/issues/518 I thought it's easier than this issue
