### ISSUE TITLE
Update DesignSandbox

### ISSUE THREAD

**Issue by VWRoli** [Greenstand/treetracker-web-map-client#503]
Update the designSandbox, complete with dark theme information. Update colors based on Figma. Also, update the readme to contain the color information for new developers.

![Screenshot from 2022-03-02 18-15-52](https://user-images.githubusercontent.com/31432331/156413486-3ceed8ab-b582-436f-b1f2-956946b459be.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by VWRoli** [comment]
I'll work in this.

**Comment by dadiorchen** [comment]
@VWRoli what is this about?

**Comment by VWRoli** [comment]
I updated the colors a bit for the dark theme. Some colors change based on the theme some don't. I want to add this information into the design sandbox and the readme file, so new devs know what colors to use.
