### ISSUE TITLE
A query parameter to ignore the animiation of the map zooming in.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#505]
When you open the url below, there is an animation to show the map, in some case, we need to ignore the animation and show the map directly. 
https://dev.treetracker.org/?userid=5556

like: 
https://dev.treetracker.org/?userid=5556&presentation=[normal|simple|impressive]

We need also to do some changes to the web map core to make this all works.
---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by CodeWithUmair** [comment]
Hi,
I want to fix it please give me more guidance about it.

**Comment by CodeWithUmair** [comment]
If you want my email id for strong relation so here it is : codewithumair867@gmail.com

**Comment by CodeWithUmair** [comment]
I am a fresher looking for opensource contribution so can u help me out, I want to contribute to your project and can u assign me this issue :)
