### ISSUE TITLE
Create a dashboard for web map settings.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#515]
Now we need a dashboard to do some settings stuff for the web map, the coming soon one is the theme customization feature for the web map, so we need to build a dashboard framework to integrate these features.

To save time and avoid inventing the wheel repeatedly, we can consider using template like this: https://material-ui.com/store/

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by GISSIAH** [comment]
hey i wanted to help out . where can i start with the dashboard. my email is shlattbihness@gmail.com .

**Comment by dadiorchen** [comment]
I invited you to Slack let’s onboard you there

Dadior Chen

在 2022年4月7日，19:19，Bryan Malunje ***@***.***> 写道：

﻿

hey i wanted to help out . where can i start with the dashboard. my email is ***@***.******@***.***> .

**Comment by dadiorchen** [comment]
This issue is still open, if anyone wants to make a try, please comment here.

**Comment by SudoMig** [comment]
I'd like to take on this assignment

**Comment by dadiorchen** [comment]
@SudoMig thank you!

**Comment by dadiorchen** [comment]
@RubenSmn could you onboard @SudoMig on this, to give him some guide on the customizable web map?

**Comment by dadiorchen** [comment]
@RubenSmn I think this is already done, I'm correct?

**Comment by RubenSmn** [comment]
The frontend of the dashboard is mostly working, we still need to add the backend connections.

**Comment by dadiorchen** [comment]
Good, I think this is majorly about frontend, so we can close it now
