### ISSUE TITLE
Set up next.js to use relative path for resources

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#518]
Generally, it's fine when we run the app locally, but when we deploy to the dev env, the next.js is trying to load resources from the root path, but because we run the app under `http://domain/web-map-site/` so this lead to 404 failed to load resources:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5744708/164367926-7c341a2f-ac9d-4695-aa97-de21081c30e2.png">

As shown above, we need the website to request: http://dev-k8s.treetracker.org/web-map-site/xxxx rather than http://dev-k8s.treetracker.org/xxxx

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by okdv** [comment]
I can take care of this!
