### ISSUE TITLE
A image-based button similar as Fab in mui

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#528]
We need a button with image behavior like Fab component in mui, or we can use Fab directly by setting up correctly.

When mouse hoving over the icon, we need some highlight to give user some feedback.

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-04-25%20at%2011.50.52%20AM.mp4

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by kenleyshaw** [comment]
I'd love to work on this!!

**Comment by kenleyshaw** [comment]
having trouble getting the dev environment to work, I already did npm install and I am using node version 16. this is the error its giving 
<img width="963" alt="Screen Shot 2022-04-26 at 3 54 06 PM" src="https://user-images.githubusercontent.com/76185224/165381411-ed4d3716-adab-4175-89ab-eb5f0720ea1b.png">
