### ISSUE TITLE
can not show trees/clusters in this case:

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#53]
https://map.treetracker.org/?map_name=mytreestrust

working case: https://map.treetracker.org/?userid=3717 they are the same.

**Comment by sebastiangaertner** [comment]
User id = 3717 is in mytreestrust so it should be included in the map view https://map.treetracker.org/?map_name=mytreestrust
There is also one more planter in there at the moment which does also not get displayed due to zoom levels cluster issues.

**Comment by dadiorchen** [comment]
I have tested this case locally on my computer, in the new version , it works well, so let me confirm that it's working on the prod env when we released the new version.

**Comment by dadiorchen** [comment]
Solved 
<img width="500" alt="Screen Shot 2021-09-09 at 3 16 29 PM" src="https://user-images.githubusercontent.com/5744708/132640581-a2bfafd9-cad4-48a0-87ee-ef38a02167f4.png">
