### ISSUE TITLE
Dim the slider button if mouse is not hovering on it.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#531]
So initially, the slider button is not so clear, but when we move the mouse on it, make it more clear, like highlight it.

<img width="1440" alt="Screen Shot 2022-04-26 at 10 48 59 AM" src="https://user-images.githubusercontent.com/5744708/165210213-2ce48be4-4c89-4daa-9f95-3549de5f990a.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by lucky-chap** [comment]
@dadiorchen can I tackle this issue? If yes, then please assign it to me

**Comment by dadiorchen** [comment]
@lucky-chap sure! Thank you!
