### ISSUE TITLE
Fix a missing flag

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#532]
Please fix these two flag of country for us.
<img width="690" alt="image" src="https://user-images.githubusercontent.com/5744708/165215177-797256e6-cd40-4ce0-926c-cfea7a649aa5.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
visit http://localhost:3000/top you will find this list

**Comment by kenleyshaw** [comment]
working on this one also!
