### ISSUE TITLE
Remove a:hover style on the link

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#537]
http://localhost:3000/top
the text: tree: xxxx

<img width="854" alt="image" src="https://user-images.githubusercontent.com/5744708/165668927-65719104-535d-4d54-a21c-e815efdbc125.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by zainbazaz** [comment]
Hey I am new to open source and would like to contribute to this project/issue

**Comment by dadiorchen** [comment]
Hi, @zainbazaz sorry for the delay, thanks, please feel free to make a try and raise PR!

**Comment by zainbazaz** [comment]
@dadiorchen I also found a typo in readme.md under "Workflow with Github" section. Should I fix it or will that be a separate issue?

**Comment by dadiorchen** [comment]
@zainbazaz thank you for your correction of the doc. Feel free to raise PR for that. And you can raise separate PR for every change you made. We prefer smaller, dedicated PR
