### ISSUE TITLE
Find a better way to import svg icons.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#542]
Now we are loading svg icon like this:

```
 import accuracyIcon from '../../images/icons/accuracy.svg';
<img src={accuracyIcon} alt="accuracy" />
```

It's not so ideal, because as img's src, we can not do control over the SVG, like change the color by `fill` property. According to the material UI, we can use iconSVG or svgIcon, to do this, we failed to do it following the guide, please help us solve this problem.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by pratikmdhr** [comment]
I'll look into this

**Comment by dadiorchen** [comment]
@pratikmdhr this would be a huge help, I encountered many cases that needed this feature.

**Comment by pratikmdhr** [comment]
@dadiorchen how about importing the SVG icons as a react component.. https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs

```
import { ReactComponent as AccuracyIcon } from '../../images/icons/accuracy.svg';

function App() {
	return (
		<AccuracyIcon fill='green'></AccuracyIcon>
	);
}

export default App;
```

**Comment by dadiorchen** [comment]
In this way, can we set the color using theme, or `sx` props, like:
`theme.palette.primary.main` 

The goal of this issue, is making it possible to set the svg's color using theme

**Comment by dadiorchen** [comment]
@pratikmdhr

**Comment by jeremydthomas** [comment]
Are you looking for something like this in the MUI docs? [https://codesandbox.io/s/v1wp6m?file=/demo.tsx](url)

I was going to start on 576 but I see this needs to be done first

**Comment by dadiorchen** [comment]
@jeremydthomas not the same, in the demo you pasted, it's using raw/direct svg string in the js file, but our case is: 
1. The designer do the design on Figma
2. We download the icon as .svg and put it into the repo
3. Import the SVG file into pages
4. Change the SVG icon color by the color defined in the theme of MUI

**Comment by jeremydthomas** [comment]
@dadiorchen I seen how I can change the color to grey by using the fill and stroke option directly in the .svg file, if you want I can do that until something else is figured out. I seen what you were talking about after monkeying around some more to see exactly what you guys had done. Didn't actually open the svg file before I posted that link :laughing:

**Comment by dadiorchen** [comment]
@jeremydthomas according to the MUI doc, it should be a easy thing to use svgicon to achieve what we want, but I failed to do it following this doc: https://mui.com/material-ui/icons/

```
// webpack.config.js
{
  test: /\.svg$/,
  use: ['@svgr/webpack', 'url-loader'],
}

// ---
import { ReactComponent as StarIcon } from './star.svg';

<SvgIcon component={StarIcon} inheritViewBox />
```

**Comment by pratikmdhr** [comment]
@dadiorchen @jeremydthomas added this to `next.config.js` as per [this guide](https://react-svgr.com/docs/next/) .. 

```
 webpack(config) {
    config.module.rules.push({
      test: /\.svg$/,
      use: ["@svgr/webpack"]
    });
    return config;
  },
```
but i get this error: 
![image](https://user-images.githubusercontent.com/52301822/170583158-be83e249-306e-4f43-8429-9484ce6ba852.png)

@dadiorchen did you receive the same error when you tried it? it looks like there is some conflict when we add the svgr webpack config with other image files

**Comment by jeremydthomas** [comment]
@dadiorchen, so I started playing with this again last night. I did find a way to make it work with theme.pallete.primary.main, it requires actually turning the svg files into components (accuracy.js file) and then loading them as react components. Similar to what @pratikmdhr was talking about a few paragraphs up. Plus many other css props for customizing them. I purposely made it bigger so you could see the color and such in this picture.

I could not get this https://github.com/Greenstand/treetracker-web-map-client/issues/542#issuecomment-1124295756 way to work.

if this is interesting to you, let me know and Ill get a draft pr or something up and you can look at what I did fully.

```        {tree.gps_accuracy && (
          <TreeTag
            TreeTagValue={tree.gps_accuracy}
            title="GPS Accuracy"
            icon={
              <SvgAccuracy
                width={50}
                height={50}
                fill={theme.palette.primary.main}
              />
            }
          />
        )}
```

is equal to this picture 
![image](https://user-images.githubusercontent.com/63400531/181135843-9f8919b1-3917-4cd0-b2df-e2b44ee23a26.png)

**Comment by dadiorchen** [comment]
@jeremydthomas yes, I think we should go in this direction, previously, I thought idealy we should be able to import `.svg` file directly and also being able to `fill` the color, but I'm afraid there are some difficulties, so let do as you suggested, correct me if I am wrong:
1. Export icon to `.svg` file
2. Copy the content in the file and create a `.js` file in the repo.
3. Import the `.js` as SVG icon component.
4. `fill` the color.

If this is true, please raise PR for it, thanks!

**Comment by jeremydthomas** [comment]
Yes exactly it, Ill start working on the whole thing tonight @dadiorchen Ill keep the original .svg files untouched and make a svg component folder inside the svg folder and put the components in there.

**Comment by jeremydthomas** [comment]
After figuring everything out tonight, I am now changing everything over to the new way in doing svg files @dadiorchen . Basically what I did was to add 
```  webpack(config) {
    config.module.rules.push(
      {
        test: /\.svg$/i,
        issuer: /\.[jt]sx?$/,
        use: [
          {
            loader: '@svgr/webpack',
            options: { icon: false },
          },
        ],
      },
      {
        test: /\.(png|jpg|gif)$/,
        use: [
          {
            loader: 'file-loader',
            options: {},
          },
        ],
      },
    );
    return config;
  },
```
into next.config.js file, then 
``` 
import AccuracyIcon from '../../images/icons/accuracy.svg';
```
instead of 
 ```
 import accuracyIcon from '../../images/icons/accuracy.svg';
```

I was then able to use this code
 ```
        {tree.gps_accuracy && (
          <TreeTag
            TreeTagValue={tree.gps_accuracy}
            title="GPS Accuracy"
            icon={
              <AccuracyIcon
                height={50}
                width={50}
                fill={theme.palette.primary.main}
              />
            }
          />
        )}
```
to get the same picture that I posted above.

**Comment by jeremydthomas** [comment]
Well, the SvgIcon tag now works as well, so Im going to use that. Ive learned tons about svg files and mui and next.js.  The sx prop works with svgicon, and for theme.palette.primary.main to work, MUI uses just primar.main under the sx prop

**Comment by dadiorchen** [comment]
@jeremydthomas awesome, did you open a PR?

**Comment by jeremydthomas** [comment]
@dadiorchen finally finished and put up a PR. Let me know what you think or how I could improve!
