### ISSUE TITLE
A tiny problem of CSS for dark mode

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#543]
The background/border of the avatar looks a little uncomfortable, maybe we should make the avatar border the same as the whole background, just like in the light mode.
<img width="721" alt="image" src="https://user-images.githubusercontent.com/5744708/166617472-c2b8945b-d6e1-4a13-8fc4-3ed63fd545db.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by Senay-Fekadu2** [comment]
Or may be we should change the background to something with contrast and complementary color. and these is my first time contributing to open source can have shot ?

**Comment by dadiorchen** [comment]
Yes, thank you @Senay-Fekadu2 you can work on it directly, and raise a PR, please let me know if you need any support!

**Comment by Senay-Fekadu2** [comment]
Okay thankyou for assigning me and I will let you know if I have a question

**Comment by dadiorchen** [comment]
Oh, @Senay-Fekadu2 I think is this out-of date, can you go though the list and find another one that intersts you?
