### ISSUE TITLE
Improve the shadow of this case

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#545]
Currently, the /top page is using the default paper shadow, it's different from the UI design, check below, so we need to refine this detail, also, make sure the `dark` mode is good too.

Our implementation:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/5744708/166621428-8f1d031e-4d5f-4a36-b841-aacf4d5a4090.png">

The Figma:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/5744708/166621467-a65e8bde-a228-43af-b3d3-5bab2d3a2168.png">

 ---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by khalatevarun** [comment]
can you share figma link @dadiorchen

**Comment by dadiorchen** [comment]
@khalatevarun this has been solved by @RubenSmn but I didn't make it merged
