### ISSUE TITLE
Support route: /map/[map-name] 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#546]
I think we should use next.js rewrite to make this happen, rewrite rule like:
/map/[map-name] --->  /organizations?map_name=[map-name]

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by okdv** [comment]
@dadiorchen I dont see an existing /map/[map-name] path. what should be expected here?

**Comment by dadiorchen** [comment]
@okdv this is a long story, here are some info:
https://github.com/Greenstand/treetracker-web-map-client/issues/431
https://github.com/Greenstand/treetracker-web-map-client/pull/644#pullrequestreview-1019250555

So we are trying to build a sandbox to customize the theme, and load it for organization, to do this, we are planing to use: http://map.treetracker.org/map/freetown/xxxxxxxx to indicate the map name/org name.

**Comment by dadiorchen** [comment]
Freetown is our biggest panter in Africa: https://map.treetracker.org/?map_name=freetown
