### ISSUE TITLE
The second CSS filter is missing

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#547]
On the page: http://localhost:3000/organizations/19 the first filter works well, but the second is missing

<img width="551" alt="image" src="https://user-images.githubusercontent.com/5744708/166857918-1f6072c8-9600-4823-ac5f-76ce71737da2.png">

<img width="1440" alt="Screen Shot 2022-05-05 at 11 03 14 AM" src="https://user-images.githubusercontent.com/5744708/166857965-9120a37b-16f5-4d19-bd37-0d99222ad0aa.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dharmiknotop** [comment]
can you elaborate on the issue @dadiorchen

**Comment by dadiorchen** [comment]
I if remember this correctly, we use filter to create the shadow for the image, refer to our design here: https://www.figma.com/file/kF69K6r81GxoV8eGCgtOFY/Greenstand-Webmap-(Copy)?node-id=5127%3A20292

But the one mentioned in the issue is missing that effect/shadow

**Comment by keyy123** [comment]
@dadiorchen Is there an URL I can use to reproduce the issue? I tried the same URL in the screenshot and it looks completely different now.
