### ISSUE TITLE
Make the timeline icon more noticeable

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#55]
![image](https://user-images.githubusercontent.com/5744708/118791903-ba643a00-b8c9-11eb-9781-f9d7416e976f.png)

**Comment by dadiorchen** [comment]
example: https://www.windy.com/?22.291,114.150,5

**Comment by adriana-carmo** [comment]
Dadiorchen, I will develop it.

**Comment by ZavenArra** [comment]
1. timeline icon should not show when side panel is open
2. timeline icon should never show when viewing a single tree link (like ?treeid=12312 or ?tree_name=test-name)

**Comment by dadiorchen** [comment]
I will split this to a seperate issue.

**Comment by dadiorchen** [comment]
Solved
