### ISSUE TITLE
A shadow effect for mobile

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#551]
Our mobile version, for example http://localhost:3000/trees/186737
When we scroll down, the layer of the header and the scrollable area is a bit confusing, we need a shadow effect like the google map, check the video below:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/5744708/167059476-ef1c2842-3a5e-4634-8422-fd8b346189a6.png">

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-05-06%20at%2010.58.41%20AM.mp4

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by RubenSmn** [comment]
Played around with this, noticed that the box shadow does not overlaps images. See screenshot below.

![image](https://user-images.githubusercontent.com/31519867/177035023-d3eb56bd-46a4-4cea-9ce7-93c9400b20eb.png)

**Comment by dadiorchen** [comment]
@RubenSmn thanks, I will check it later

**Comment by khalatevarun** [comment]
@dadiorchen please review following PR, have tried fixing the issue. 
https://github.com/Greenstand/treetracker-web-map-client/pull/1019
