### ISSUE TITLE
Tiny CSS problem

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#552]
The zoom button is a bit higher than the logo
<img width="542" alt="image" src="https://user-images.githubusercontent.com/5744708/167064370-1a6ada69-bdde-47b8-a36a-ef5694d66f9b.png">

On this page: http://localhost:3000/trees/186735?embed=true
---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by rsmith-github** [comment]
I've fixed it on my local version. May I open a pull request?

**Comment by tranquanghuy0801** [comment]
@dadiorchen Seem like this issue has been solved in the linked MR?

**Comment by dadiorchen** [comment]
Yes, thank you
