### ISSUE TITLE
An edge case for the photo slider

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#558]
We should hide the button on the slider component in some cases:
1. If the slider area is on the most right, or left, we should hide the button respectively.
2. If there are too few photos, then the buttons have no need to display

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5744708/167556892-a6da1f4a-1802-459d-957c-8070247f7e6f.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by jamwalab** [comment]
Hey I can work on this.

**Comment by dadiorchen** [comment]
@jamwalab hi, yes, please take it, and raise PR when you got any pregress
