### ISSUE TITLE
The 'share to twitter' button doesn't work

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#562]
To reporduce: 

1. visit http://localhost:3000/trees/186735
2. click share
3. click twitter logo

The code:

```
  function handleTwitter() {
    window.open(
      `https://twitter.com/intent/tweet?url=${shareUrl}&via=green_stand&related=Greestand,treetracker`,
    );
  }
```

Seems the Chrome blocked the window.open.

<img width="780" alt="image" src="https://user-images.githubusercontent.com/5744708/167757172-9b70c6b1-c290-42ad-a9c1-8aa785bc2ffe.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
I guess the `facebook` button encountered the same

**Comment by jeremydthomas** [comment]
Id like to work on this, thank you.

**Comment by jeremydthomas** [comment]
I would like this one and I believe I already fixed it.

**Comment by dadiorchen** [comment]
@jeremydthomas thanks! please

**Comment by dadiorchen** [comment]
Please raise a PR for us

**Comment by jeremydthomas** [comment]
@dadiorchen all done my friend, have a good day!
