### ISSUE TITLE
Bad style/spacing on mobile

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#565]
Maybe the `gap` property doesn't work on mobile.

Device: iPhone, ios 13
Browser: Chrome
 
![image](https://user-images.githubusercontent.com/5744708/167759671-bdccf696-eb90-4381-8954-be89148bc9f9.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by jeremydthomas** [comment]
@dadiorchen I dont have an iphone, but on the chrome developer tools iphon12 pro, this isnt showing up. Is this still a problem?

**Comment by dadiorchen** [comment]
could you please test it on android? or others?

**Comment by dadiorchen** [comment]
@jeremydthomas

**Comment by RubenSmn** [comment]
Just checked on android, Chrome and Samsung Internet. And the spacing is correct!
