### ISSUE TITLE
The map doesn't work on some mobile device

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#567]
The map is missing.

Device: iPhone, ios 13
Browser: Chrome

![image](https://user-images.githubusercontent.com/5744708/167759671-bdccf696-eb90-4381-8954-be89148bc9f9.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by siddharth-kaushik** [comment]
Can I fix this?

**Comment by dadiorchen** [comment]
@siddharth-kaushik sure, please!

**Comment by dadiorchen** [comment]
feel free to open PR when you get any progress
