### ISSUE TITLE
Implement page cache via next.js

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#571]
We need to cache our page, say: http://map.treetracker.org/trees/123 next.js should be having some support for this goal.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
The case: because the DB is the bottleneck, we don't want our page to get stuck every time waiting response from DB, so we need to cache the page on the server-side, and speed up the processing. 
Please give a solution for this.

**Comment by okdv** [comment]
Quick clarification, this would also be for the beta branch right? I was confused since the link provided is for the master branch site, and the doesnt seem to use nextjs. 

Assuming its for the beta branch I can also take a crack at this! should be easy enough with SSR and Cache-Control/stale-while-revalidate. Any preference as to how long the cache should be used and/or considered fresh?

**Comment by okdv** [comment]
Can also take a crack at this! Should be pretty straightforward with next and cache-control. Would this be on the master branch (you linked the live website which uses master i thought)? Or is this for the new website?

**Comment by dadiorchen** [comment]
@okdv yes, happy to hear that. This is on `beta` branch, the link is just for explaining the issue.

**Comment by okdv** [comment]
Perfect, thank you for the clarification @dadiorchen I'll take a crack at it :smile:
