### ISSUE TITLE
Refine the shadow of these component

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#575]
These box's shadow is more smoothy then our implementation, please refine it, you can find it here: http://localhost:3000/top

Please make sure the shadow works well on the dark mode (by clicking `theme` button on top right corner)

<img width="521" alt="image" src="https://user-images.githubusercontent.com/5744708/169633732-a9992e47-b0f1-4196-9461-e1c2607d096b.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by sinhaniik** [comment]
hey, I want to work on this but this project is not running on my local machine. I cloned this project and after that, I ran "yarn start"
but it does not host on localhost 3000. can you help me with that

**Comment by dadiorchen** [comment]
@sinhaniik you should run: npm run dev, the `start` is for prod

**Comment by sinhaniik** [comment]
$ npm run dev

> client@2.0.0-beta.5 dev
> next dev

'next' is not recognized as an internal or external command,
operable program or batch file.

now this

**Comment by dadiorchen** [comment]
Weired, the next should be installed after `npm install` if you want, you can also bring your quest in the weekly meeting of web map, it's Thursday ,https://calendar.google.com/calendar/u/0?cid=Z3JlZW5zdGFuZC5vcmdfZmMwZGFsam5icHN1cHQ2c2tiYjc3bWt1cTBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

**Comment by RubenSmn** [comment]
Should we use the `elevation` property for this, or just the `boxShadow` property. Using the `boxShadow` results in a more accurate replica of the figma design

**Comment by dadiorchen** [comment]
Previously, we just simply copy the shadow from figma, it works for light mode, but the problem is darkmode, we need to make sure it works for dark mode too.
Elevation has good behavior when switching between dark and light, as I mentioned here: https://greenstand.slack.com/archives/CA0ALV5S8/p1651203951801449
