### ISSUE TITLE
Make the search button disabled

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#576]
Change the icon color to grey, indicating this feature is not yet ready.
This is related to : #542 by importing SVG correctly, we should be able to use the theme to set the color easily.
Please make sure it works well on dark theme mode.

Also, please add a Tooltip saying: `coming soon` (or better text describing that) sorry about my poor English

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
@jeremydthomas maybe you can help us on this? Just try to test your new mechanism of using SVG

**Comment by jeremydthomas** [comment]
Yes, I've already got a solution for this. The color='disabled' works here @dadiorchen I was going to do this and raise a pr immediately after the other one

**Comment by dadiorchen** [comment]
solved by @jeremydthomas
