### ISSUE TITLE
Display tree species or country rather than tree name

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#577]
Currently we display tree name (three-random-words) in the panel, now we need to change it to show: tree species if any, if the tree has no species specified, then display the country where the tree is.

<img width="1440" alt="Screen Shot 2022-05-21 at 11 56 48 AM" src="https://user-images.githubusercontent.com/5744708/169634590-45aee1d6-f860-4d00-82f4-5685addf7f2b.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by tyler1588** [comment]
I would like to work on this issue. 
I noticed that right now the response object used to map the tree components does not have a country attribute, but it does have a species attribute. 

Any advice on how to proceed with this?

**Comment by dadiorchen** [comment]
Solved by current code
