### ISSUE TITLE
Shorter lat/lon numbers

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#579]
Currently, the latitude and longitude number are too long, no need to display this way, could be as short as below:

On the middle of the screen, the first menu item is a coordinates by google map

![Image](https://user-images.githubusercontent.com/5744708/169639289-214277fa-ab50-4a21-b3dd-e7e4824ac194.png)

**Comment by jeremydthomas** [comment]
@dadiorchen is this what you wanted? I shortened it to 5 decimal places.

![lat,lon](https://user-images.githubusercontent.com/63400531/169680787-2875ceda-a2d7-44af-ad3d-bcbdf2c9ac8a.png)

**Comment by dadiorchen** [comment]
That's perfect, please open PR for us! @jeremydthomas

**Comment by jeremydthomas** [comment]
@dadiorchen just a different question, can I just go down the line on fixing things without getting them assigned? Trying not to be too greedy if someone else wants to work on something. When I fix it, do I just automatically open a PR? Also, does the slack channel have a channel for the this beta web map client? I am in the admin_channel_chat one.
