### ISSUE TITLE
Getting Unhandled Runtime Error on /top page

### ISSUE THREAD

**Issue by ANaphade** [Greenstand/treetracker-web-map-client#581]
Getting an unhandled runtime error when trying to hit endpoint http://localhost:3000/top.
 
The error dialog closes when we click outside the dialog

Please find screenshot below for more details

![image](https://user-images.githubusercontent.com/36621150/169696442-be4f2449-0b49-43e5-8d91-48478eba32f2.png)

After clicking outside the error dialog, the dialog minimizes in bottom left corner ('1 error' in red)

![image](https://user-images.githubusercontent.com/36621150/169696604-d509d131-4c89-47de-9bbe-1e6571b12e72.png)

**Comment by dadiorchen** [comment]
@ANaphade thank you for issue this for us!

My feel on this is that the app accidentally initialed the drawer which registers the onTouch listner, this drawer should be touched on the desktop version, it's for mobile
