### ISSUE TITLE
Super easy: npm install and update the lock file

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#583]
The CI is failing because of wrong package-lock.json, please run npm install and generate it and upload/commit
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5744708/169726734-133bcb24-d01e-49d8-8596-8919ef1f9828.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by svihang8** [comment]
Hello! I would like to work on this issue. @dadiorchen
