### ISSUE TITLE
Planter page: use the first tree to fill the profile background

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#584]
As a temporary solution, use GET /trees?planter_id=[id]&order_by=created_at&desc=true&limit=1 to get the first image, and show it on the profile background (the blue picture below)
<img width="746" alt="image" src="https://user-images.githubusercontent.com/5744708/169728314-f33cd680-2156-49b0-9f7c-b2a5f0b71471.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by jupiterdoom** [comment]
https://github.com/Greenstand/treetracker-web-map-client/pull/662

**Comment by dadiorchen** [comment]
@jupiterdoom thanks for taking this issue, rather than mention PR here, you should mention this issue in your PR :) 
https://github.com/gitbucket/gitbucket/wiki/How-to-Close-Reference-issues-and-pull-request
