### ISSUE TITLE
Miss context when click `next tree`

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#590]
On this page: http://localhost:3000/planters/940/trees/186734?embed=false
When click `next tree` on the map, the page jump to:
http://localhost:3000/trees/186735?embed=false

Please jump to http://localhost:3000/planters/940/trees/186735?embed=false

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by okdv** [comment]
I believe this was fixed by #755 right?
