### ISSUE TITLE
Change to use cookie or localStorage to save the status of fullscreen

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#591]
Currently, we are using a query parameter embed: http://localhost:3000/planters/940/trees/186734?embed=true to indicate this is a fullscreen map, this approach has some downsides:

1. problem prone: easy to lose the query jumping through pages.
2. Ugly URL

We should find another solution for this, either cookies or localStorage, 

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by svihang8** [comment]
Hey @dadiorchen. 
I've had a PR for one of your previous issues. I recently noticed this. If it is still available I would love to work on this issue.
I believe we can make use of cookies to solve the issue. We can have a middleware function that can check to see if the required cookie exists. Thank you!

**Comment by dadiorchen** [comment]
@svihang8 sorry for the delay, thanks for what you've done for us, yes, please go forward and take this one.
Because now we have adapted localStorage somewhere in this project, so I tend to use the same tech to handle this issue, is it okay?
Please check this page:
https://github.com/Greenstand/treetracker-web-map-client/search?q=storage

**Comment by RubenSmn** [comment]
@dadiorchen with 'fullscreen' do you mean whether or not the `embed` value in the url is `true`?

**Comment by dadiorchen** [comment]
@RubenSmn correct!

**Comment by dadiorchen** [comment]
@RubenSmn this one is problematic, in some case we must use the URL to control the embed behavior.

**Comment by dadiorchen** [comment]
BUT, maybe we can do in this way?

1. Open: http://localhost:3000/planters/940/trees/186734?embed=true
2. Display map in embedded mode
3. Save the mode status into cookie/localstorage
4. Jump to another page without `?embed=true`
5. Read the cookie/localstorage
6. Display map in embedded mode

**Comment by dadiorchen** [comment]
Another solution: https://github.com/Greenstand/treetracker-web-map-client/issues/707

**Comment by RubenSmn** [comment]
> BUT, maybe we can do in this way?
> 
>     1. Open: http://localhost:3000/planters/940/trees/186734?embed=true
> 
>     2. Display map in embedded mode
> 
>     3. Save the mode status into cookie/localstorage
> 
>     4. Jump to another page without `?embed=true`
> 
>     5. Read the cookie/localstorage
> 
>     6. Display map in embedded mode

@dadiorchen I think this is a good way to solve this issue
