### ISSUE TITLE
The drawer's border radius become flat/square when dock to the top

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#596]
<img width="1440" alt="Screen Shot 2022-05-23 at 11 07 43 AM" src="https://user-images.githubusercontent.com/5744708/169735891-9944aa79-fe38-4e51-b1b8-8cf0649b9f77.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by RubenSmn** [comment]
I'll work on this!

**Comment by dadiorchen** [comment]
@RubenSmn thank you!
