### ISSUE TITLE
Mobile: can not scroll to the bottom of the page.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#597]
Can not scroll down to the bottom to check all the content on this page. http://localhost:3000/trees/186737

<img width="1440" alt="Screen Shot 2022-05-23 at 11 10 31 AM" src="https://user-images.githubusercontent.com/5744708/169736063-788fbf17-6660-4b98-ba98-cd06bd32bf23.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by jeremydthomas** [comment]
![image](https://user-images.githubusercontent.com/63400531/170192064-14395508-2d9d-488d-95a9-2eb26cfc3b04.png)
@dadiorchen works for all mobile devices on chrome developer tools
