### ISSUE TITLE
Bug: theme problem on the mobile page

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#599]
To produce: 

1. On /top page, change the theme to dark
2. Click the planter name to jump to planter page.
3. The banner is dark, but the panel below is light.

<img width="691" alt="image" src="https://user-images.githubusercontent.com/5744708/169737492-a997fbdd-db8c-46ab-a2aa-6f6fb60921c0.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
This might because of the new Dawer implementation

**Comment by jeremydthomas** [comment]
@dadiorchen so Im pretty sure I figured out what is causing this, I just need to figure out how to use localstorage to recall what mode you are using. If you notice when you go to the top page it doesnt reload and it keeps the theme you had set. If you go to the trees page it also doesnt reload and it keeps the theme you had set. HOWEVER, if you go to the planters page or the organizations page it reloads the page and you go back to the default light theme setting. When you change it back to dark again after the page loads it works fine. 

Do you think using localstorage to recall what setting you had before the page reloaded would be the way to go here, or am I just off on my thinking?
