### ISSUE TITLE
Improved quick links on the verify list

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-web-map-client#6]
See below the two images. Second icon should open the users map to quickly see the overview. (such as https://treetracker.org/?userid=3336)
Changing the order of icons first the pin icon with link to individual_tree, then the user_info_icon and then the user_map_icon
![usermap_link](https://user-images.githubusercontent.com/3283800/103736377-2e7c0080-5001-11eb-8ea0-5c1943f9b843.png)
![userinfo_link](https://user-images.githubusercontent.com/3283800/103736382-3176f100-5001-11eb-9626-53717a880660.png)

**Comment by deepwinter** [comment]
this is an admin panel issue.
