### ISSUE TITLE
The menu definition

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#600]
@sebastiangaertner can you give a quick definition of these links and words here? It could be a temporary one.

<img width="1440" alt="Screen Shot 2022-05-23 at 11 58 45 AM" src="https://user-images.githubusercontent.com/5744708/169740791-fa900aa5-3c6d-4ae9-9652-53ede91c1207.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by sebastiangaertner** [comment]
looks good for now. We can change it later as well.
