### ISSUE TITLE
The zoom button should be disabled in some cases

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#619]
Just like this picture shows, when the zoom level reach the maximum/minimum zoom level, the button should be gray and unclickable.

<img width="209" alt="image" src="https://user-images.githubusercontent.com/5744708/172276002-cbd6d1ff-0f09-4d16-90c4-d2de39e24d7a.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by keyy123** [comment]
I think this issue is already complete 😁👌.

**Comment by RubenSmn** [comment]
Fixed by #1213
