### ISSUE TITLE
Bug: `Like` and `Share` button not visible on tree page using FireFox

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#639]
Visiting http://localhost:3000/trees/186734
There should be a `Like` and `Share` button at the top of the tree image according to the code.
When checking the dom elements with the inspector the items are present.
They are just not visible.

Purple indicating where the buttons should be seen
![image](https://user-images.githubusercontent.com/31519867/175102073-dadf16bc-fb10-48b3-8420-f0aeddfb6d9f.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
@RubenSmn weird, it was there I remember.

**Comment by dadiorchen** [comment]
Maybe some change accidentally hides these buttons,  I think this is the reason we need the visual matching test, https://github.com/Greenstand/treetracker-web-map-client/issues/498

**Comment by jeremydthomas** [comment]
I thought they were there before too

**Comment by RubenSmn** [comment]
I think this might be something on my side, I am also having trouble with the zoom in/out buttons on the map.
When looking at the dom via the inspector I see empty transparent svg's on the img src.
Which is weird because the Search Icon is also an svg and that one I can see.
I checked in the project files and all the image are present.

**Comment by RubenSmn** [comment]
@dadiorchen @jeremydthomas just tried opening the app in chrome and all the buttons are visible. No clue why they are not visible when using FireFox.

**Comment by dadiorchen** [comment]
Oh, that's interesting, good finding!

**Comment by RubenSmn** [comment]
Just noticed that they are present and clickable just not visible!

**Comment by RubenSmn** [comment]
YES found something! It has something to do with a `<g>` element in the `<svg>` element there is filter on which magically `hides` the whole svg, no clue how it happens but will try a fix and open a PR :tada:
