### ISSUE TITLE
Link to species when available

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-web-map-client#640]
By now the species descrition is always used as a link into either the treetracker herbarium or a wiki entry or another plant database source. see attached screenshots. It would be great if a user can click on the species and a _blank link comes up with the corresponding info. 
![Screenshot 2022-06-22 at 22 04 48](https://user-images.githubusercontent.com/3283800/175126333-0ef61ef8-f8dc-4d3f-be3e-3c46d19fcadd.png)
![Screenshot 2022-06-22 at 22 01 16](https://user-images.githubusercontent.com/3283800/175126337-d63a6648-b178-435e-b17a-4239704a7637.png)

**Comment by dadiorchen** [comment]
This is interesting, maybe we can dig deeper to build more features. Where can we get the reflection between the species name and link?
