### ISSUE TITLE
The https://map.treetracker.org/?userid=3350 is broken

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#645]
On line version, `master` branch

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by sebastiangaertner** [comment]
https://map.treetracker.org/?userid=6599 seems to work. @dadiorchen is this still active?
