### ISSUE TITLE
Toggle desktop/mobile view of the web app in theme playground 

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#668]
As the person who customizes the theme I want to be able to view the web app on different 'devices'.
Currently we are only able to view the web app in desktop view.
We want to have an button to change this view. The place should be next to the other buttons in the top bar of the config section.

You can use the `SquareIconButton` as button.
The state for this can be defined in the playgroundContext

- Location -> src/pages/admin/theme.js line: 409
- Location -> src/context/playgroundContext.js

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
I added `challenge` tag is because I think it's a bit tricky to switch between devices, in  a web page, @RubenSmn what kind of technology do you think we can use to implement this? Iframe? HOC in react?

**Comment by RubenSmn** [comment]
The most forward solution; I think; is to use the MUI [Container](https://mui.com/material-ui/api/container/#props) around the current iframe and change the `maxWidth` prop

**Comment by RubenSmn** [comment]
I think that it should work; would have to test it to know for sure

**Comment by dadiorchen** [comment]
Yea that's possible, sometimes, the app will calculate something based on the global property, for example: the window.height

**Comment by RubenSmn** [comment]
@dadiorchen just did some more testing and came to the conclusion that for this to work properly with our `Drawer` we need to update the `Drawer` to use `pointer` events instead of `touch`

**Comment by dadiorchen** [comment]
@RubenSmn I'm not sure if the `pointer` event has big impact on the real mobile device, but I think for the playground, it is fine if the app behavior not 100% the same as the real device? So I think we can just go forward with this flaw.

What do you think?

**Comment by dadiorchen** [comment]
At least they can see the initial view of the mobile page on the playground, right?

**Comment by RubenSmn** [comment]
This is the current `Mobile` preview, the user is able to click on everything (go to trees pages etc) but can't really see anything due to the drawer not being swipable with the mouse.

For now I can just implement the basic toggle feature.

[Kooha-2022-08-08-10:27:00.webm](https://user-images.githubusercontent.com/31519867/183374786-be9234f4-0d38-40e0-9947-9cd2205fdfb5.webm)

**Comment by dadiorchen** [comment]
@RubenSmn I think this is really good enough for now, let's build the Rome city brick by brick :D you can make a challenge issue for dealing with the drawer, but for now let's just leave it as this.
