### ISSUE TITLE
Google analysis installment

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#673]
We need to add the google analysis script into the app, so we got data into google to check the visit chart/statistic.

And check if the data is successfully dumped into the google dashboard.

Maybe we also need to consider the interference of the data from test, dev env, but this is not the highest priority.

I will give you the necessary resource you need to finish this job

**Comment by dadiorchen** [comment]
This issue is a good lesson to understand website statistic and anaysis

**Comment by keyy123** [comment]
@dadiorchen, Is this ticket still open?

**Comment by dadiorchen** [comment]
Google analysis is installed, but I really think there is more to go to improve or to do some like report and discover based on the coming data, but I didn't sort things out and create issues, if you are interested, I can add you to the dashboard and to find out what's more we can do
