### ISSUE TITLE
share by code/facebook/twitter

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#676]
The share feature has been down on our version 1, but the beta version misses this, so please help us migrate the existing version from version 1(master) to beta.

<img width="981" alt="image" src="https://user-images.githubusercontent.com/5744708/183355403-c45ffa5a-4d62-45c4-809b-56055c34569b.png">

**Comment by dadiorchen** [comment]
We have done some work on this, the share button is working, but there sill are some problem, for example, clicking share to facebook will throw error.

Please go though these button for us and make sure they are working.

**Comment by pierrelstan** [comment]
@dadiorchen I'm working on this.

**Comment by pierrelstan** [comment]
@dadiorchen The share to Facebook works using the protected link you gave me.

**Comment by dadiorchen** [comment]
So I think we can close this one?
