### ISSUE TITLE
image placeholder

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#677]
We need a good image placeholder to put into the places where we don't have real data.
For example, picture below, the current planter hasn't a photo yet, so we need a default image here.
It could be a gray logo of greenstand, or anything other appropriately.
![Image](https://user-images.githubusercontent.com/5744708/169639051-f0a585a5-959c-49cf-b77e-1cb7123dcb95.png)

**Comment by dadiorchen** [comment]
![Image](https://user-images.githubusercontent.com/5744708/182287825-6570ca88-96bc-4152-85ac-ff6540a2affe.png)

**Comment by dadiorchen** [comment]
Our designer has made the picture, so just need to add it to the project:
[Archive.zip](https://github.com/Greenstand/treetracker-web-map-client/files/9247437/Archive.zip)

**Comment by jeremydthomas** [comment]
ill be working on this
