### ISSUE TITLE
A mechanism to disable next cache

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#687]
We withdraw the next cache feature in this PR: https://github.com/Greenstand/treetracker-web-map-client/pull/686/files

This is because in the Github action, if we use cache, the execution is slow and will fail sometime, like this: https://github.com/Greenstand/treetracker-web-map-client/runs/7551857265?check_suite_focus=true

So we need an env variable to switch the cache feature, so on the CI, we can close it to avoid failure.
Something like: `NEXT_CACHE_ENABLED=true`

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by keyy123** [comment]
@dadiorchen, The integration test logs expired on this ticket. I would like to try this ticket too?

**Comment by keyy123** [comment]
Would it make sense to make a conditional for all the revalidate props that if the new secret is true to set the revalidate time to 0 else default to the previous behavior? I was researching how to do the same with GitHub action but it seems a bit more troublesome... 😅.

**Comment by dadiorchen** [comment]
you are super!

0 will not be the meaning of no cache, It means forever?

Yes, this is a valid issue, actually I did some try for this, but failed, I tried to conditionally export the cached method or non-cached method, but it is impossible because of js syntax  rules.

Please go and find a way for us.

**Comment by keyy123** [comment]
You are correct 😋! Based on a GitHub issue ticket I've read recently, The minimal value to re-validate is `1` meaning re-validate ASAP. Next will throw an error if anyone sets this value to `0` BUT it allows you to cache infinitely after build-time using `false` as a value.

I will make a conditional that if the secret is true, use the same values for the revalidate prop otherwise re-validate immediately (same as disabling cache).

Sounds good, @dadiorchen ?

**Comment by keyy123** [comment]
Would this work?
```
const getStaticProps = wrapper(async ({ params }) => {
  const props = await serverSideData(params);
  // if secret enabled - cache like normal
  if (process.env.NEXT_CACHE_ENABLED) {
    return {
      props,
      revalidate: Number(process.env.NEXT_CACHE_REVALIDATION_OVERRIDE) || 30,
    };
  }
  // else re-validate immediately
  return {
    props,
    revalidate: 1,
  };
});
```

**Comment by dadiorchen** [comment]
I think this is the same as: setting NEXT_CACHE_REVALIDATION_OVERRIDE = 1 right?

I don't think this is making too much sense. The ideal result is that totally disable the cache and return the result directly rather than returning the previous version, 

So if there isn't better solution, I think setting a short expire time is also good, so this is where to go, I think we can freeze this issue and just set the revalidation override var.

**Comment by keyy123** [comment]
Ok 👍
