### ISSUE TITLE
On this page, can not display logo

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#694]
http://localhost:3000/organizations/1/trees/701767?embed=true

**Comment by dadiorchen** [comment]
We should:
on the left top conner, 

![Image](https://user-images.githubusercontent.com/5744708/181641214-b955a5bd-6fd0-4d2a-b45c-cd577370a94c.png)

**Comment by RubenSmn** [comment]
Do you mean the Greenstand logo? Can we find it in the figma design?

**Comment by dadiorchen** [comment]
This isn't in our current figma file, it is here: https://github.com/Greenstand/treetracker-web-map-client/issues/11

**Comment by dadiorchen** [comment]
You can find it on online version: https://freetown.treetracker.org
