### ISSUE TITLE
Force code format for every commit.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#696]
Before committing code, force to format code using prettier, in this way, the whole project is consistent in code format, avoiding unnecessary file differences when review code.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by tranquanghuy0801** [comment]
https://prettier.io/docs/en/precommit.html 
Seem like option 2 in this link can do this task

**Comment by dadiorchen** [comment]
@tranquanghuy0801 I agree, can you set it up for us?

**Comment by dadiorchen** [comment]
Another think I observed is that seems the pre-check for commit can be bypassed in some way, because I seems saw some violation in some rule even we set for it, but I'm not sure, just a reminder
