### ISSUE TITLE
The dark/light button doesn't work

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#698]
I noticed that by clicking the button, nothing happen, but, refreshing the page will get the expected result.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
@RubenSmn this seems related to your change?

**Comment by RubenSmn** [comment]
@dadiorchen will have a look!

**Comment by RubenSmn** [comment]
This happens when the theme object is not set in the local storage!
