### ISSUE TITLE
New highlighted wallet accounts on the `top` page.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#699]
Just like the featured org and planters, we need a section of `Featured wallet this week` and the UI could be the same, but list 10 newest wallets with logo (we will replace it with real featured list in the future) 
<img width="822" alt="image" src="https://user-images.githubusercontent.com/5744708/181677537-ddcca123-d98e-4e49-8409-b0e8d76d47d8.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by jeremydthomas** [comment]
Im working on this, currently waiting on https://github.com/Greenstand/treetracker-query-api/issues/146

**Comment by dadiorchen** [comment]
@jeremydthomas I think you can continue, that API has been released

**Comment by jeremydthomas** [comment]
Ok thanks, I'll get started on it again. Took a bit of a vacation with the family, so haven't been on much.
