### ISSUE TITLE
Leaflet web map: need to add copyrights information. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#7]
On the right-bottom corner, we need to display approricate map copyright information. 
We are using: google satellite map as background, leaflet library. 
<img width="1440" alt="Screen Shot 2021-03-03 at 2 53 59 PM" src="https://user-images.githubusercontent.com/5744708/109765861-5f0e9e00-7c30-11eb-8a8d-d4b34961b250.png">

**Comment by Maxfrank** [comment]
@dadiorchen @deepwinter 
Created PR for this issue https://github.com/Greenstand/treetracker-web-map-client/pull/13
Google's Terms of Use forbid any means of tile access other than through the Google Maps API, therefore I re-added the google map API script, and use a plugin of leaflet (called GoogleMutant) to integrate google satellite and google attributions with leaflet.

Please refer to https://github.com/Leaflet/Leaflet/blob/master/FAQ.md#i-want-to-use-google-maps-api-tiles-with-leaflet-can-i-do-that
