### ISSUE TITLE
Sometimes, the `nearest arrow` keep showing

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#70]
Even there are icons on the map.

https://www.loom.com/share/0f374c77ff37473d89696ae698b4efb8

**Comment by dadiorchen** [comment]
This is still a problem, we need someone working on this.

**Comment by SuokN** [comment]
> 
 In the current version of map.treetracker.org we don't even have those arrows.
Is this issue still open?

**Comment by dadiorchen** [comment]
@SuokN I'm glad you are interested on this, I think this is still a problem, but maybe the way to reproduce the problem changed, http://prod-k8s.treetracker.org/web-map-beta/demo this is our new online version, and we evolved a lib for the map things, so you need also to look into this repo: https://github.com/Greenstand/treetracker-web-map-core
