### ISSUE TITLE
Reset input fields to their default value

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#701]
### Description

Currently we can only reset the whole theme back to the Greenstand default.
We want to be able to reset the individual style props as well.
Every input should have some reset button/icon

**Comment by khalatevarun** [comment]
could you please provide the design as in where the reset button/icons must be places for every input field

**Comment by RubenSmn** [comment]
@khalatevarun unfortunately we do not have a design for the theme playground. Maybe we can place it on the right side of the label?
