### ISSUE TITLE
Use the route to control the embed behavior

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#707]
Currently, we use this way (query parameter) to control the embed behavior:

http://localhost:3000/planters/940/trees/186734?embed=true

This is annoying because we need add this parameter for every URL when we navigating on the app.

We need to consider use route to control this behavior:

http://localhost:3000/m/planters/940/trees/186734

Probably we need to use next.js rewrite to implement, but any possible solution is welcome!

**Comment by dadiorchen** [comment]
We were thinking about use cooike to implement it, but in this way, we can not let user open the embed map at the first time, right?

http://localhost:3000/planters/940/trees/186734?embed=true

**Comment by okdv** [comment]
I would agree with the cookie solution in #591, as opposed to a next.js rewrite. It's a little more involved, but i think this could work well by creating some routes dedicated to setting and getting the cookie. 

- create /getCookie and /setCookie (as examples)
- in _app check /getCookie
- - if /getCookie finds no cookie, uses /setCookie to set default and returns that
- - if /getCookie finds existing cookie, returns that
- assign /getCookie value to same nextExtraIsEmbed prop and pass it along to page thats being requested so not much work needed in the individual pages/components 

then when a user hits the map embed/fullscreen toggle button, it can call /setCookie and toggle it, and refresh the page, running _app and retrieving new cookie value from /getCookie, etc- cycle continues

if that sounds good, im happy to take a crack at it :smile:

**Comment by dadiorchen** [comment]
@okdv I'm also dislike this solution, it seems not so RESTFul style, the `emebed` is a state of UI rather than a resource, so I don't want to put it into the path rather than query parameter.

But when I re-think the requirements, you know, for the partner of greenstand, say, https://sadu.app/#everyone they want to integrate our map into their app (as a browser view) in this case, we need totally remove the 'un-embed` button, how do we handle this case? So I was thinking use http://domain/m/... to bring a total embed web map app.

Then back to our `embed/un-embed` button, the cookie/localstorage approach is a good solution to avoid cumbersome query parameters.

Maybe we need to implement them all...

what do you think?

**Comment by dadiorchen** [comment]
another question: cookie vs localestorage:

I prefer local storage, it's easy to manipulate, no server-data-sending, so don't need to ask permission of user, last one: we already used it in the project.

@okdv @RubenSmn please comment

**Comment by RubenSmn** [comment]
I also prefer localstorage, it is already set up in the project and easy to use. I think its a good solution, no need to build something new for the cookies

**Comment by okdv** [comment]
agreed, localstorage is better than cookies for this. might be a bit of a pain to implement with SSR/ISR being used on the same pages, but should work if we wait for it to mount first

as for the url bit. I think using them both, so that way there is a easy way to know when to hide that un/embed button. or if hiding the button isnt much concern, we can simply embed by default and no need for url specified embedding i dont think

**Comment by RubenSmn** [comment]
I don't think we need the url. We could just use the localstorage value to check whether to display the embed or unembed button

**Comment by okdv** [comment]
my only concern there is wouldnt need to default to embed so it works for those partners that @dadiorchen mentioned? if so, users wouldnt be able to go to unembed either, so might as well get rid of the un/embed stuff altogether

**Comment by RubenSmn** [comment]
That is true. Then I think @dadiorchen solution in #591 is the way to go

**Comment by dadiorchen** [comment]
>Potentially can also just see if it's being loaded by another webpage and control button from that, depending on how it's done, iframe, etc

Genius idea, but it's a little bit hacking style, I'm not sure it works for all cases, for example embedded by a browser view of a native app like android and ios

Thanks, guys, good discussion! 

I think I tend to implement them both, but let's implement the localstorage solution first as we also discussed here: #591 

@okdv will you take it or you are on others?

**Comment by dadiorchen** [comment]
map.treetracker.org/?integrationversion=true
