### ISSUE TITLE
Tree page: add information sections:  `took at`, and `location info`

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#715]
Add info below, put them under the tree id on the photo panel, replace the tree name (like, Eco-Peace-Vision), the tree name is useless for us for the time being, because most of tree is missing it.

![Image](https://user-images.githubusercontent.com/5744708/169639171-3f230a60-27db-4e44-93b8-bf4395000d8d.png)

**Comment by jeremydthomas** [comment]
![Image](https://user-images.githubusercontent.com/63400531/184468043-72c69e8a-928c-4ff5-b885-35527e035b1f.png)

is this what you want replaced?

**Comment by dadiorchen** [comment]
I just changed my mind, don't replace, just add: took at, and location below the `Palm tree` is this okay?

**Comment by dadiorchen** [comment]
@jeremydthomas how's this issue going?

**Comment by jeremydthomas** [comment]
@dadiorchen I forgot about it, I'll start on it again.
