### ISSUE TITLE
Treetracker timeline not properly exposed

### ISSUE THREAD

**Issue by michaltrunek** [Greenstand/treetracker-web-map-client#72]
Timeline icon is hard to spot on page load. This functionality should be more visible to the user. Maybe this was already fixed by our DEVs but listing it just to be sure. Feel free to close if not valid anymore.

**Details:**
![Screenshot 2021-06-25 at 16 30 25](https://user-images.githubusercontent.com/4280850/123458381-46faca00-d5e5-11eb-9704-341aa5fe8451.png)

**Comment by dadiorchen** [comment]
Solved by @adriana-carmo
