### ISSUE TITLE
Tree icon highlighting is inaccurate

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#722]
Check the video, maybe this is a problem in `core`, the highlighted icon's position is a bit diverged from the right place:

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-08-02%20at%2010.14.20%20AM.mp4

**Comment by pierrelstan** [comment]
@dadiorchen I take that one.

**Comment by dadiorchen** [comment]
@pierrelstan cool!

**Comment by dadiorchen** [comment]
@pierrelstan what's the situation of this one? I tried again on the map, the effect is better than before somehow?

What's the effect of the highlight on your side? This is from my computer:
https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-08-23%20at%205.14.01%20PM.mp4

I think this is almost acceatable, although the number text would still move up or down a bit when you put mouse on it.

**Comment by pierrelstan** [comment]
@dadiorchen, I noticed that the effect is better too.
The problem was probably from the treetracker-web-map-core package.

**Comment by dadiorchen** [comment]
Right, maybe because that we just upgraded the core to the newest version.

**Comment by dadiorchen** [comment]
So @pierrelstan do you think we can close this issue for now?

**Comment by pierrelstan** [comment]
@dadiorchen  I think, we can close it.
