### ISSUE TITLE
Ignore history/back for updating the bounds on url address

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#725]
Currently, everytime we change the bounds (https://prod-k8s.treetracker.org/web-map-beta/demo/top?bounds=-108.10546875000001,-54.77534585936448,145.01953125000003,59.5343180010956), for example, click the zoom in/out button,  the new bounds will push the browser history, we need to ignore this action, because it make no sense that when people clicking back button on browser, the URL jumps back to previous bounds, instead, we should jump to a previous valid URL. 

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-08-02%20at%2010.42.48%20AM.mp4

**Comment by dadiorchen** [comment]
@Mohmn it would be great if you can give any input on this.

**Comment by Mohmn** [comment]
@dadiorchen I totally agree with you here , either the map should respond to bound url changes or we should route back to a url which performs some action

**Comment by dadiorchen** [comment]
Some resource related to this issue: https://developer.mozilla.org/en-US/docs/Web/API/History_API

**Comment by dadiorchen** [comment]
This is valid issue open to contributors

**Comment by QuanGiap** [comment]
I will try yo work on this
