### ISSUE TITLE
Help to analyze a special behavior of next.js

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#726]
This is weired, when we input: https://prod-k8s.treetracker.org/web-map-beta/demo/ the URL will automatically change to : https://prod-k8s.treetracker.org/web-map-beta/demo

I am not sure this is from next.js, but it has impact on the app sometimes:

The ambassador will have problem with: https://domain/services  (without ending with slash) I don't know if we can solve this problem on the side of ambassador to be able to recognize this case?

**Comment by dadiorchen** [comment]
@emmanue do you think we can make ambassador work for this?

**Comment by keyy123** [comment]
@dadiorchen, I may be really late with this but we can configure next.js to add trailing slashes for URLs. If you want me to do so, I can take on this ticket!

**Comment by dadiorchen** [comment]
I think we don't have to do this now, because I set up our front-end gateway to workaround, (so now we use a new domain beta-map.treetracker.org, so we don't need to attach the extra slash anymore) but it would be great if you can paste your solution or links here, it is possible we need it in the future, thank you for having the time looking into this!

FYI we are using ambassador as the front gateway, the root of this reason is that the rewrite of this URL: /web-map-client/ requires an extra slash or the URL will be redirect to a default root path, so actually this is a wired behavior, we need dig deeper to tune ambassador to be better.

**Comment by keyy123** [comment]
Here is the resource to handle this issue: https://nextjs.org/docs/api-reference/next.config.js/trailing-slash.
