### ISSUE TITLE
Remove the extra spacing/padding of the Link component

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#728]
After added the Link component, the UI will be changed a little bit, check the comparison:

without Link
![Image](https://user-images.githubusercontent.com/5744708/182283531-48b5d1ce-42b3-473c-992a-bfc5c776ebc9.png)

with Link
![Image](https://user-images.githubusercontent.com/5744708/182283868-872b9951-34c4-4cde-9b94-119f7a83e7a1.png)

We need to erase the effect of the Link which increased the gap of elements.

**Comment by oscargonzalezdev** [comment]
Hi there! I can help you with this issue.
Where can I find this component?

**Comment by dadiorchen** [comment]
@oscargonzalezdev thank you! The component is: /src/component/Link.js

**Comment by dadiorchen** [comment]
This issue is related to #830
