### ISSUE TITLE
Leaflet link in the bottom right corner with no css style

### ISSUE THREAD

**Issue by michaltrunek** [Greenstand/treetracker-web-map-client#73]
Leaflet link in the bottom right corner has no css styles applied and therefore it doesn't look nice. Do we need to have it from legal point of view?

**Details:**
![Screenshot 2021-06-25 at 16 35 01](https://user-images.githubusercontent.com/4280850/123458626-8c1efc00-d5e5-11eb-8077-413666dd683d.png)

**Comment by dadiorchen** [comment]
Solved by @adriana-carmo
