### ISSUE TITLE
Restrain the image size on planter page

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#730]
When the tree picture is big, the image size is inappropriate:

![Image](https://user-images.githubusercontent.com/5744708/182287554-35d12004-cbfd-490d-93bb-a7580dff1b8e.png)

comparing to the design:

![Image](https://user-images.githubusercontent.com/5744708/182287642-140e11eb-6c6c-4833-b628-8704ca786d38.png)

**Comment by jeremydthomas** [comment]
@dadiorchen something like this? 
![image](https://user-images.githubusercontent.com/63400531/183588511-484e04bf-2712-492b-b752-20f739ccc340.png)
this code here
`          sx={{
            borderRadius: 4,
            mt: 6,
            '& img': {
              width: '100%',
            },
          }}
`
seems to really distort the image when it makes it really wide like that.

**Comment by dadiorchen** [comment]
You are close, we need to refine the UI to close the design here: https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=4819%3A14477

**Comment by jeremydthomas** [comment]
@dadiorchen try number 2, I took the height from the figma and hard coded it. left the width at 100%

![image](https://user-images.githubusercontent.com/63400531/183833591-a80869f9-1f23-4765-82c8-ebf036846a07.png)

**Comment by dadiorchen** [comment]
@jeremydthomas did you open PR?
