### ISSUE TITLE
Set next.js runtime configuration for some env variable

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#731]
The problem:

Now we are using config like this:

`.env.production`

```
NEXT_PUBLIC_API=https://dev-k8s.treetracker.org/query
NEXT_PUBLIC_TILE_SERVER_URL=https://{s}.treetracker.org/tiles/
NEXT_PUBLIC_TILE_SERVER_SUBDOMAINS=dev-k8s
NEXT_PUBLIC_API_NEW=http://127.0.0.1:4010/mock
NEXT_PUBLIC_BASE=
NEXT_PUBLIC_CONFIG_API=
```

The problem is, that we will build the next after merging the code, then deliver the package to dev, test, production env, so we can not allow the settings which would change in different envs.

Solution, according to some research:
https://stackoverflow.com/questions/50416138/nextjs-set-dynamic-environment-variables-at-the-start-of-the-application
https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration

Next.js support runtime config, so in this way we can use the same package and set the config for different env. 

The settings that should be runtime configurable:

```
NEXT_PUBLIC_API=https://dev-k8s.treetracker.org/query
NEXT_PUBLIC_TILE_SERVER_URL=https://{s}.treetracker.org/tiles/
NEXT_PUBLIC_TILE_SERVER_SUBDOMAINS=dev-k8s
NEXT_PUBLIC_API_NEW=http://127.0.0.1:4010/mock
```

**Comment by pierrelstan** [comment]
@dadiorchen I take this one.

**Comment by dadiorchen** [comment]
@pierrelstan if this is not easy, maybe it not the best solution, I think we can also consider to delay the building step to put it into the bundle, so the normal env var could work

**Comment by dadiorchen** [comment]
Finially, we decide to build the next everytime when we run the next.js server
