### ISSUE TITLE
"Greenstand" logo - no link

### ISSUE THREAD

**Issue by michaltrunek** [Greenstand/treetracker-web-map-client#74]
"Greenstand" logo in the bottom right corner should have a link to the Greenstand website if possible. Most probably this is not a bug as such, just an improvement.

**Details:**
![Screenshot 2021-06-25 at 16 35 28](https://user-images.githubusercontent.com/4280850/123458867-d1dbc480-d5e5-11eb-95d1-a1d0f929f49d.png)

**Comment by dadiorchen** [comment]
Resolved
