### ISSUE TITLE
Set next.js redirect url to compatible with old map

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#740]
We need to redirect our old url/path to the new version, so we need to set a redirect rule to bring the old url to the new version:

rule:

http://localhost:3000/?treeid=xxx  --> http://localhost:3000/trees/xxx

http://localhost:3000/?userid=xxx  --> http://localhost:3000/planters/xxx

The best result is a 302 permanent redirect, if it is hard, we could consider other options.

**Comment by okdv** [comment]
ill take care of this real quick, however it will be a 308 redirect. same thing as 301 effectively (except 308 preserves all headers/method) only bc this is supported by next.js out the box, see https://nextjs.org/docs/api-reference/next.config.js/redirects

**Comment by dadiorchen** [comment]
@okdv acceptable! thank you!
