### ISSUE TITLE
Add tooltip to custom card

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#751]
### Description
In the `CustomCard` component we need an tooltip to display helper/info text; the question mark icon.

![image](https://user-images.githubusercontent.com/31519867/183158451-fb7dd5ab-6833-48f7-906a-451c466218bd.png)

For the UI you can follow our Figma design, see the link below for detailed design.

Tooltip: https://mui.com/material-ui/react-tooltip/
Figma: https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=3648%3A13321

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by quyet-v** [comment]
can I take this one?

**Comment by RubenSmn** [comment]
@quyet-v yes go ahead!
