### ISSUE TITLE
Should be able to load the map by `bounds`

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#754]
If the url includes `bounds` parameter, then the map should be load by the bounds:

http://localhost:3000/planters/940?bounds=38.79890441894532,-5.565415753407831,39.29328918457032,-5.069057826784033

As shown above, when open the page, the map should display the view according to the bounds=lat,lon...

The map core (Map object) can be set by bounds, so we just need to set it when we load the page.

Just like our online version: https://map.treetracker.org/?&bounds=13.719177246093752,14.599531422729925,17.674255371093754,16.70986293320658

**Comment by jeremydthomas** [comment]
@dadiorchen Im a bit lost on exactly what you want done here, my localhost link opens it to the map cords like it should when I click on your link. and when i make it http://localhost:3000/?bounds=38.79890441894532,-5.565415753407831,39.29328918457032,-5.069057826784033 that works too.

**Comment by dadiorchen** [comment]
@jeremydthomas good start I think, yes, then it means the web map core support loading by bounds, so, the problem is, the planter/xxx page can not load by `bounds` the map view was decided by the initial calucation, we need to jump the the view indicated by the `bounds` query.

See, this is the planter page, I moved the map after loading:

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/5744708/183590389-69d93b6a-dadc-4ed8-a7fa-641ba9251198.png">



Then I copy the URL and open in a new tag, it will jump back to initial view of that planter.

**Comment by dadiorchen** [comment]
This feature is useful for our patterner, because sometime they want to share the map with other but change a little bit the initial view of the map, doesn't this make sense?

**Comment by Mohmn** [comment]
@dadiorchen i have made some progress on this issue? just have some doubts to clear
can we meet tomorrow

**Comment by dadiorchen** [comment]
https://calendly.com/dadiorchen/meet-with-dadior sure!
