### ISSUE TITLE
Mobile drawer doen't work on the bottom

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#759]
And the id is too long for uuid case to distort the UI

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-08-08%20at%2011.26.51%20AM.mp4

![Image](https://user-images.githubusercontent.com/5744708/183332663-27f4586a-812b-456d-be0a-77fcef7faafd.png)

**Comment by RubenSmn** [comment]
Could we use the `text-overflow` property with `ellipsis` for this? https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

**Comment by dadiorchen** [comment]
@RubenSmn good idea, be aware of the browser compatibility, some properties are not supported by browsers.

**Comment by RubenSmn** [comment]
Not able to use `text-overflow`

**Comment by dadiorchen** [comment]
I think we also need the uuid component to shorten the text  #823

**Comment by RubenSmn** [comment]
Added the UUID component but having some issues with the tags 
Before UUID|After UUID
:-:|:-:
![image](https://user-images.githubusercontent.com/31519867/188416841-810363ec-2e02-4302-9552-e4b9d8f5a831.png)|![image](https://user-images.githubusercontent.com/31519867/188416571-536b54ec-3bf1-4b1f-a025-c910072e57be.png)

**Comment by dadiorchen** [comment]
@dadiorchen I don't think we need the token (unclaimed) here

**Comment by RubenSmn** [comment]
I will work on it!
