### ISSUE TITLE
The app is not loading in IE 11 and Yandex browsers

### ISSUE THREAD

**Issue by michaltrunek** [Greenstand/treetracker-web-map-client#76]
**Details:** 
IE 11, Yandex

![Screenshot 2021-06-25 at 16 54 17](https://user-images.githubusercontent.com/4280850/123459210-457dd180-d5e6-11eb-8227-5dd90f6c7d24.png)
![Screenshot 2021-06-25 at 16 59 11](https://user-images.githubusercontent.com/4280850/123459216-46aefe80-d5e6-11eb-85b6-0cb3f206c948.png)

**Comment by keyy123** [comment]
@dadiorchen, should this PR be closed? 🤔
