### ISSUE TITLE
Need some padding on the bottom

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#760]
![Image](https://user-images.githubusercontent.com/5744708/183333281-da4eb3b2-1dc0-4985-b152-2fd0d1178357.png)

**Comment by Dun-sin** [comment]
Hi, maybe a little more content on where exactly the padding is needed will be helpful

**Comment by RubenSmn** [comment]
@Dun-sin the padding is needed on the wallet page: https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/pages/wallets/%5Bwalletid%5D.js#L270

**Comment by dadiorchen** [comment]
@Dun-sin welcome, if you want to join ur community to find more stuff, please send me your email so I can invite you
