### ISSUE TITLE
Graph not showing on ImpactSection

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#769]
The static graph is not showing on the `ImpactSection` component
This is probably due to the new way we import svgs

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by RubenSmn** [comment]
@jeremydthomas could you have a look at this?

**Comment by jeremydthomas** [comment]
@RubenSmn is it supposed to look like this?
![image](https://user-images.githubusercontent.com/63400531/183593061-f3d5b789-ce9f-4d33-9592-5cda39290028.png)

If so I just fixed it

**Comment by RubenSmn** [comment]
@jeremydthomas yes it does! But I remember the text was on a different spot: https://github.com/Greenstand/treetracker-web-map-client/pull/749#issuecomment-1207171655
