### ISSUE TITLE
Fix UX drawer

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#775]
### Description
On mobile the drawer has bad UX when trying to expand/collapse it.
Scrolling up the content collapses the drawer. The same happens when scrolling down the content then de drawer expands.
See the video for a better insight:

[Kooha-2022-08-09-13:29:05.webm](https://user-images.githubusercontent.com/31519867/183637894-b91b7a59-cff4-47bd-b0ed-aba384b71f3a.webm)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
Bad, I solved this problem before, at least on my side, I tested the scroll is perfect, but don't know why it shows up again, maybe some CSS change cause this. 
How do you test it? By Chrome?

**Comment by RubenSmn** [comment]
Yes I tested it with Chrome. I think it is due to the content being a `ref` for the `touch` event handler. We could simply fix it by only setting the handler on the title/header part of the drawer

**Comment by RubenSmn** [comment]
Also tested it on a real mobile device, same issue

**Comment by dadiorchen** [comment]
Great, open PR if you fixed it

**Comment by RubenSmn** [comment]
Fixed by #865
