### ISSUE TITLE
Invalid pointer to a tree (zoomed in)

### ISSUE THREAD

**Issue by michaltrunek** [Greenstand/treetracker-web-map-client#78]
Upon completely zoom in on one tree (number 1 in a circle, not map pointer yet) sometimes user can see an arrow pointing/suggesting to move to left/right but in fact the tree is already presented on the screen.

**Details:**
iPhone 12, Chrome

![Screenshot 2021-06-25 at 17 15 36](https://user-images.githubusercontent.com/4280850/123459975-45320600-d5e7-11eb-9841-426dce5ef4d2.png)

**Comment by dadiorchen** [comment]
a duplicated issue with #70

**Comment by dadiorchen** [comment]
Duplicated issue
