### ISSUE TITLE
Ugly case of the avatar

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#780]
In this case, the bottom of the avatar is a bit weird because the background of the SVG is white, need to refine this UI

![Image](https://user-images.githubusercontent.com/5744708/184075882-7edea53d-15a3-4be2-a715-d7c37d70cb86.png)

How to reproduce: http://localhost:3000/organizations/178

**Comment by RubenSmn** [comment]
Maybe we could make a semi transparent black background to create more contrast

**Comment by dadiorchen** [comment]
I don't know, semi transparent would mix the log and the background?

**Comment by RubenSmn** [comment]
I think this is quite challenging. This avatar/logo has an transparent background, do we know if all the logo's will have an transparent background?
To create a more visible border we could change the background of the avatar to a semi transparent color like in the screenshot below. If the logo has an transparent background this would be the fallback color. If the logo has a solid background it will just show the background of the logo.

![image](https://user-images.githubusercontent.com/31519867/185624700-aa283469-6960-4153-bb0a-9bc165f1f449.png)

Ofcourse if the logo background is white we would still have the same problem
![image](https://user-images.githubusercontent.com/31519867/185625900-54f82655-6429-4980-92c2-e8dd9a641ead.png)

**Comment by dadiorchen** [comment]
@RubenSmn I like it, please go this way!
