### ISSUE TITLE
There are too much space in the impact area for mobile

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#783]
We need to refine for mobile on this area

![Image](https://user-images.githubusercontent.com/5744708/184244043-fef17690-077a-41a7-b897-58639e35076c.png)

**Comment by RubenSmn** [comment]
I think that is my bad, there is a fixed height on the graph image. Should make it dynamic!

**Comment by dadiorchen** [comment]
Could consider sx{{ height: [height-for-mobile, height-for-desktop]}} ?
