### ISSUE TITLE
How about do some adjustment on the impact selection

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#787]
I think we can make the first card/button in gray color, and move the coming soon higher,  I recorded a video to explain my mind:

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-08-12%20at%203.14.53%20PM.mp4

**Comment by dadiorchen** [comment]
@RubenSmn is this okay for you?

**Comment by RubenSmn** [comment]
@dadiorchen #774 fixes the explanation
We can change the color of the cards easily but then we need another way to indicate which card is 'active'

**Comment by dadiorchen** [comment]
But they are not demo-purposed, we don't need to indicate that, and making them clickable is kindof confusing for people?

**Comment by RubenSmn** [comment]
Aah okay so we make them not clickable and when we have the grapical data we make them working again, correct?

**Comment by dadiorchen** [comment]
Yes, all these are for demonstration.
