### ISSUE TITLE
Theme mode toggle on embed pages

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#791]
### Description
Visiting: http://localhost:3000/trees/701767?embed=true
The user does not have an option to switch between `dark` and `light` themes.
We could use the already exisiting `ChangeThemeButton`

![localhost_3000_trees_701767_embed=true](https://user-images.githubusercontent.com/31519867/184326694-d43bbaa3-11bc-4c7f-a317-6d3091020f7f.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
To avoid distraction, I will remove this from readness project.

**Comment by tranquanghuy0801** [comment]
@RubenSmn Where do we put the Change Theme button on this page?

**Comment by RubenSmn** [comment]
@tranquanghuy0801 thank you for looking into this! For now I think you can just place it to the left of the search button!

**Comment by dadiorchen** [comment]
@RubenSmn @tranquanghuy0801 what would the UI look? A new button on the map?

**Comment by RubenSmn** [comment]
I was thinking of placing it next to the search button, somewhere like this:
![Screen Shot 2022-09-24 at 10 25 16](https://user-images.githubusercontent.com/31519867/192088375-090b1107-90e6-425f-b77a-7c62a0bc02ee.png)

**Comment by tranquanghuy0801** [comment]
<img width="565" alt="image" src="https://user-images.githubusercontent.com/29462498/192099823-abce1a86-ccc0-40b7-bd84-515c06e58370.png">
Yup, I would think the same as Ruben said above and did like this.

Also @RubenSmn, do we have a design of how the embed pages look like when the dark mode is turned on?

**Comment by RubenSmn** [comment]
Ah wow, nice @tranquanghuy0801 No we do not have a design for the dark mode, only for light

**Comment by tranquanghuy0801** [comment]
@RubenSmn I will have a look and find it first. If not, you can feedback on my MR and I will update then.

**Comment by dadiorchen** [comment]
We need re-design the UX now, let's close this issue first and then back to the feature if the design is done.
