### ISSUE TITLE
Mobile menu not closing on click

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#795]
### Description
The mobile menu is not closing when the user clicks the button again. It is only closing when you click on another element.
See the video for a visual explanation

[Kooha-2022-08-12-15:32:14.webm](https://user-images.githubusercontent.com/31519867/184364528-65b07cf5-66ae-49e3-9691-093f8d67aa2c.webm)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by jhhornn** [comment]
Hello
Is this still available for contribution?
I'd love to work on it

**Comment by RubenSmn** [comment]
@jhhornn yes go ahead!

**Comment by kperusi** [comment]
Pls can i stillwork on this

**Comment by RubenSmn** [comment]
@kperusi if you want to you could try and resolve #760

**Comment by jhhornn** [comment]
Thank you @RubenSmn 
I'm on it now

**Comment by jhhornn** [comment]
I'm finding it hard to get the folder that contains the code for this page

**Comment by RubenSmn** [comment]
@jhhornn code can be found at src/components/Navbar.js
