### ISSUE TITLE
Hide the timeline filter on: freetown.greenstand.org

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#8]
Currently, the app has been handled with some case like: treetracker.org/?map_name=freetown, in this case, the timeline filter will be hidden, we also need it be hidden in the case: freetown.treetracker.org

**Comment by adriana-carmo** [comment]
Hello @dadiorchen, about this issue, I would like to understand how someone got this url: freetown.treetracker.org, does it come from another application?

**Comment by deepwinter** [comment]
we have some domains like that set set up to CNAME to map.treetracker.org

**Comment by adriana-carmo** [comment]
Hi Zaven thanks for answering me. I am studying this issue to solve it.

**Comment by dadiorchen** [comment]
@adriana-carmo Sorry I missed the message, for this issue, actually, I think we don't not to care about the domain, because, the workflow is: first we will translate the subdomain to query parameter, like: freetown.treetracker.org ==>  treetracker.org/?map_name=freetown, so we just need to check if the filter is set, there are several different filter: map_name, wallet, userid, currently, the timeline just support the basic map, means there can't be any filter, so check if there is any filter, if true, then hide the timeline icon/

**Comment by adriana-carmo** [comment]
I created the PR
