### ISSUE TITLE
Missing functions for these two buttons

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#804]
http://localhost:3000/trees/186735?embed=false on this page, click `expand` icon to open full screen dialog:

<img width="1440" alt="Screen Shot 2022-08-15 at 2 30 44 PM" src="https://user-images.githubusercontent.com/5744708/184587503-b83d0c18-e970-4813-b642-6ae4a664f525.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by Hansraj8149** [comment]
Hello there,
I want to work on this issue, but I am having some trouble understanding the exact problem. I tried to read the readme file but I didn't find any information regarding this issue on the file. So please can you provide me with some brief on this issue.

Sorry for any convenience. This is my first time to open source contribution.

**Comment by Adarsreg** [comment]
Hello dadiorchen, how can I access this page? The link seems broken.

**Comment by dadiorchen** [comment]
:) that's possible, the app isn't stable now, please join our slack community, so we can coordinate, if you want,  send me your email please.

**Comment by Adarsreg** [comment]
adarsh_202100084@smit.smu.edu.in

**Comment by Adarsreg** [comment]
> 
Here's my github email:
adarsh_202100084@smit.smu.edu.in

**Comment by dadiorchen** [comment]
@RubenSmn can you take a quick fixing on this?

**Comment by RubenSmn** [comment]
I'll take a look!
