### ISSUE TITLE
Replace placeholder embed logo

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#807]
## Description
Visiting: http://localhost:3000/organizations/11?embed=true

The logo in the bottom right is still a the placeholder logo, we want to change this with the actual logo of the organization.
Just like on the planter page: http://localhost:3000/planters/5449?embed=true

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by jeremydthomas** [comment]
@RubenSmn So I fixed this, but I also found a bug that only happened when the link is embeded (?embed=true).

![image](https://user-images.githubusercontent.com/63400531/189836580-4c56e6e8-20ae-427c-b923-9e0b9914d9a1.png)

This happens on both the organization and planter pages. I did figure out how to fix it though. Can I add the fix on this issue?

**Comment by RubenSmn** [comment]
Awesome @jeremydthomas yes we did encounter that in a previous one aswell #813

I think you can add it to this PR id you're using a seperate commit for it, in case we need to come back to it

**Comment by jeremydthomas** [comment]
ooh, I didnt see that issue, I made another one. Should I delete it?

**Comment by RubenSmn** [comment]
You could do that, or you could make a seperate PR for the Portal document issue. Whatever you prefer :+1:

**Comment by keyy123** [comment]
Is this issue still open?

**Comment by RubenSmn** [comment]
Looks like this issue is already resolved @keyy123
