### ISSUE TITLE
The embed logo is distorted

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#811]
http://localhost:3000/trees/186735?embed=false

![Image](https://user-images.githubusercontent.com/5744708/184790596-29cbc71a-9bb4-4c4b-98c7-b8de9f895bc7.png)

The correct UI is:

![Image](https://user-images.githubusercontent.com/5744708/184790670-b73b2e3d-649c-434d-99b5-dc4347f3a71c.png)

You can find code here: https://map.treetracker.org/

**Comment by muhon9** [comment]
Is these issue already solved?
