### ISSUE TITLE
Illegal use of document in SSR components

### ISSUE THREAD

**Issue by okdv** [Greenstand/treetracker-web-map-client#813]
**Describe the bug**
Error was caught recently as embed functionality has been updated and is working properly now

Use of document in components rendered on the server side cause fatal error as document does not exist.

For example, `<Portal container={document.getElementById('embed-logo-container')}>` on `[treeid].js`

Should validate document is available before attempting to render, or find a way to accomplish same functionality without use of client side sources (document, window, etc). 

**To Reproduce**

- Navigate to http://localhost:3000/trees/186737 (for example), assuming embed is not active, note successful render
- Attempt to toggle embed (expand button, top right of map), note success as data has already rendered
- Navigate to http://localhost:3000/trees/186737?embed=true, note fatal error caused by trying to call document on server side

**Expected behavior**
Components rendered on server side should not use client side sources (document, window, etc) or they should verify their existence before calling them

```
error - src/pages/trees/[treeid].js (513:27) @ Tree
ReferenceError: document is not defined
  511 |       <Box height={20} />
  512 |       {nextExtraIsEmbed && (
> 513 |         <Portal container={document.getElementById('embed-logo-container')}>
      |                           ^
```

** Node.js version **
v16.15.0

**Desktop (please complete the following information):**

- OS: Fedora Linux 36 (Silverblue Edition) x86_64
- Browser: Brave / Chromium fork
- Version 1.42.86 Chromium: 104.0.5112.81 (Official Build) (64-bit)

**Comment by RubenSmn** [comment]
Yes I came across this too, fixed it with `container={() => document.getElementBy.....}`
