### ISSUE TITLE
Put featured tree selection to planter page

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#814]
Just like the top page, we need featured trees for /planters/{id} page:

Use /trees?planter_id=xxx endpoint to get the tree list for this slider

![Image](https://user-images.githubusercontent.com/5744708/184282510-f9775bcf-76ee-4c82-ac3a-b6109bf75f6e.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by quyet-v** [comment]
Can I take this one?

**Comment by dadiorchen** [comment]
@quyet-v it's yours, thank you for taking it!

**Comment by dadiorchen** [comment]
Please test it in mobile env too
