### ISSUE TITLE
Add top page embed version

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#815]
## Description
Visiting: http://localhost:3000/top?embed=true

There is nothing but the map. We want to have an embedded version of the top page.
Just like on the planter page: http://localhost:3000/planters/5449?embed=true

You can take the code from the planter page as an example.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by RubenSmn** [comment]
Top page embed is not showing due to this line: https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/pages/top.js#L228

**Comment by jeremydthomas** [comment]
Oh, I didnt even see that you assigned me this until now. Ill get on it

**Comment by dadiorchen** [comment]
@jeremydthomas please hold on, we need rethink this feature, maybe on the embed version we don't need the top page

**Comment by jeremydthomas** [comment]
Sounds good @dadiorchen I figured this was the case when I saw that you were the one who took the feature away
