### ISSUE TITLE
Remove second scrollbar from embed pages

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#819]
## Description
Visiting http://localhost:3000/planters/5449?embed=true or http://localhost:3000/organizations/11?embed=true
There is some issue with the scrollbars. On the pages there are two scrollbars!

![image](https://user-images.githubusercontent.com/31519867/185066281-cbe4a087-242e-43e3-b08f-e2835c0a1baf.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
@RubenSmn which browser you are using? I didn't see the scroll bar on my side, I usually is on Chrome

**Comment by RubenSmn** [comment]
@dadiorchen I use Chromium

**Comment by RubenSmn** [comment]
@muhon9 maybe you could take a look at this?
