### ISSUE TITLE
Direct navigation to the tree details upon 1 tree

### ISSUE THREAD

**Issue by michaltrunek** [Greenstand/treetracker-web-map-client#82]
If there is only one tree in a circle, user should be able to navigate to the tree details directly. Now the user has to click sometimes even 7 times to get to the tree/user details. This takes quite a big amount of time to show the tree details.

**Details:**
All mobile devices and desktop

https://user-images.githubusercontent.com/4280850/123463771-3732b400-d5ec-11eb-84aa-66a58bb811d6.mov

**Comment by dadiorchen** [comment]
This is a huge topic/task, let's leave it here and discuss it somehow.
