### ISSUE TITLE
A component to display uuid

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#823]
UUID is too long in some case, so we'd better has a wey to display the id, some consideration, any suggestion is welcome:

1. Omit part of the uuid, say, `b1e2...55cb`
2. Be able to check the full id by hovering.
3. Styleless, so we can re-use it in all kinds of environment, maybe use `span` tag is good idea, because we dont' want to break the line as shown below:

![Image](https://user-images.githubusercontent.com/5744708/185094371-b191878a-ef9f-45d7-be36-4339563292bb.png)

**Comment by Phant0m-a** [comment]
maybe try using split function to take first and last  3 letters of the id and then add three dots in between and join them!

**Comment by dadiorchen** [comment]
@Phant0m-a that's good, will you make a try

**Comment by pranavmadhu01** [comment]
can i try to implement this component

**Comment by dadiorchen** [comment]
Yes please

**Comment by dadiorchen** [comment]
This component turns out to be pretty priority for us, do you get any progress on this?

A suggestion on this is that please make the component style-unaware, like the font size, spacing, so we can put this component in different env to reuse it
