### ISSUE TITLE
Turn off the light of this icon

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#828]
component: impactplaceholder

![Image](https://user-images.githubusercontent.com/5744708/185498688-0afb9d2b-ba7c-464f-988b-c37c7c45659d.png)

**Comment by RubenSmn** [comment]
Do you mean change the green color?

**Comment by dadiorchen** [comment]
Yes, that green dollar should be gray/disabled in this case, right?

**Comment by dadiorchen** [comment]
anyway, a tiny flaw.
