### ISSUE TITLE
Link component can not use the class to set style

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#830]
For this commit: 

https://github.com/Greenstand/treetracker-web-map-client/pull/829/commits/c4c97cac4166b4d0372e02e88572ea25fac675ba

In the code, I have to set the inline style to specify CSS property, I can not use the className by mui to set it, inline style is not the best solution, so we need to fix the problem.

I wanted to add the style in the class.link, but it doesn't work. to reproduce this problem, you can try to add some inline style into the `a` and check the result on the browser, then, if you move it to the class.link object, it will not work.

I think the reason is that when we render the `a` it is happening on the server side, so maybe the random class name is wrong when we run it on the client side?

**Comment by keyy123** [comment]
Is this issue still open, @dadiorchen? I don't mind adding it to my queue of issues to tackle so I save time not looking for more issues. 😁👌

Since this is my first time working with the project's client side, Is there any set up that I need to do before I can handle this issue?

**Comment by dadiorchen** [comment]
@keyy123 are you on our slack community? if not , please leave your email so I can invite you, for the set up, I recommend you go through the readme, there are some guide and heads up

**Comment by keyy123** [comment]
@dadiorchen  I am already in the slack group for web-map! 😁👌

**Comment by dadiorchen** [comment]
I think we should be more careful on changing the basic class and style for this core common component, so I think we'd better discard the idea of styling the link by class but directly changing inline style instead.
