### ISSUE TITLE
URL does not override embed

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#841]
## Description
`embed` value is `true` in the localstorage
Trying to explicit visit `?embed=false` http://localhost:3000/trees/186735?embed=false does still display the embedded version of the page

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by RubenSmn** [comment]
@okdv is this suppose to happen or maybe a bug?

**Comment by okdv** [comment]
@RubenSmn currently is working as designed since the useEmbed hook is only checking for embed=true. However, if we want this functionality I dont expect it to be too much work to implement off the top of my head

**Comment by RubenSmn** [comment]
I think we should implement this functionality. The behavior for the user is currently different then expected. Visiting explicit `?embed=true` or `?embed=false` should result in the right version of the web map

**Comment by okdv** [comment]
yea i get that, i see no issue adding this, i'll take a look at what it takes to get that feature built. i dont expect it to be very difficult at all
