### ISSUE TITLE
Too big size of the icons on mobile

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#843]
http://localhost:3000/wallets/eecdf253-05b6-419a-8425-416a3e5fc9a0

![Image](https://user-images.githubusercontent.com/5744708/185833507-6e00cebc-1136-415c-86e4-f07073a1a96c.png)

Maybe we need to find a good way to reuse/reduce-maintainness of these cases

**Comment by RubenSmn** [comment]
Currently we are passing an `sx` prop to the CustomCard which only gets applied to the SvgIcon component. That itself is not very intuitive.
To make it more reuseable we could add a standard `height: [32, 52]` and `width: [32, 52]` in the the SvgIcon component here https://github.com/Greenstand/treetracker-web-map-client/blob/beta/src/components/common/CustomCard.js#L47-L55

**Comment by PhiCygni** [comment]
I want to try and work on this issue. I think I know what to do. I will update the component and its Cypress test.

**Comment by RubenSmn** [comment]
@PhiCygni thanks!

**Comment by PhiCygni** [comment]
I have created a PR for this issue https://github.com/Greenstand/treetracker-web-map-client/pull/866. Not sure if I did everything correctly for the PR to be picked up automatically.
