### ISSUE TITLE
Add description/unit to GPS Accuracy tag

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#846]
## Description
Currently we have a GPS Accuracy of just a number, this does not say much about what kind of information it provides.
Is it some rate? Is it some error range in meters?

![image](https://user-images.githubusercontent.com/31519867/185893272-8a577b66-555a-4346-8671-e5af5de6b7cf.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
@sebastiangaertner can you give some support on this? some explanation/text for this?
