### ISSUE TITLE
Improve ui next/previous tree buttons

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#847]
## Description
Visiting: http://localhost:3000/trees/186735
The buttons to go back and forward to the other trees need an update.
We want them to look more like our expand, zoom in/out buttons, to improve the UI/UX.

![image](https://user-images.githubusercontent.com/31519867/185895451-09e72669-1494-49d1-878b-0c2c126ffcf6.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by dadiorchen** [comment]
@RubenSmn is this duplicated with https://github.com/Greenstand/treetracker-web-map-core/issues/98 ?

**Comment by RubenSmn** [comment]
@dadiorchen yes almost, I would also suggest we keep the background of the buttons the same

**Comment by dadiorchen** [comment]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/5744708/186292081-82ef2c8a-d0e7-4e19-8100-5907a632212d.png">
I would suggest that we keep the same to the figma design, just put the button on the top because for mobile version, top is a better solution

**Comment by RubenSmn** [comment]
Ah okay yes we should stick to the figma design!

**Comment by RubenSmn** [comment]
@dadiorchen Is this button supposed to be the next/previous tree button: https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=4500%3A13734?

**Comment by dadiorchen** [comment]
@RubenSmn no the arrow icon for next/prev is here: https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=2497%3A9770

But, considering the mobile version, we will put it on the top of the map rather than the bottom, does it make sense?
