### ISSUE TITLE
Bug on this case: https://map.treetracker.org/?userid=3679 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#86]
No trees/clusters show up on this URL, need to check what happened in this case.

**Comment by mrtillman** [comment]
@dadiorchen - hey, I would like to work on this one. thanks!

**Comment by dadiorchen** [comment]
@mrtillman great, this one concerns backend, DB, and so on, so if you are stuck by any permission trouble, just let me know

**Comment by mrtillman** [comment]
@dadiorchen - actually, I'm not able to reproduce this locally: 

![0000](https://greenstand.surge.sh/dev-map-treetracker-org-userid.png)

the code for the `treetracker-web-map-client` repo does not match https://map.treetracker.org:

## map.treetracker.org:

![0001](https://greenstand.surge.sh/prod-map-treetracker-org.1.png)

## localhost:3000 (treetracker-web-map-client):

![0002](https://greenstand.surge.sh/dev-map-treetracker-org.1.png)

so, I am confused. :confused: 

how do we reproduce the problem if the web pages don't match, and the code does not match?

the local project at http://localhost:3000 also uses the mock server, so there's no back-end connection to get the `userid=3679`

what do I do? please help.

thanks.

**Comment by dadiorchen** [comment]
Yes, the main problem about this is to reproduce the case, let's talk on slack.

**Comment by mrtillman** [comment]
https://github.com/Greenstand/treetracker-web-map-api

https://github.com/Greenstand/node-mapnik-1
