### ISSUE TITLE
title is hiding the button on map

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#867]
The title area on the bottom is hiding the: zoom button, timeline button

The device testing this:
Xiaomi Redmi 10A
Android
Size | 6.53 inches, 102.9 cm2 (~81.0% screen-to-body ratio)
Resolution | 720 x 1600 pixels, 20:9 ratio (~269 ppi density)

To reproduce, maybe we can set the chrome devtool's mobile size to equal to this one

![Screenshot_2022-08-26-17-09-56-974_com android chrome](https://user-images.githubusercontent.com/5744708/186870259-945242f2-42cf-497b-a61d-f25de69229fe.jpg)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by RubenSmn** [comment]
@dadiorchen I think this happens because the browser includes the height of the top bar (home icon, url, tabs) in the view height. On some pages this bar disappears when you scroll down the page. This does not happen in our case since we scroll inline.

**Comment by dadiorchen** [comment]
@RubenSmn I don't get it, you mean this isn't a bug?

**Comment by dadiorchen** [comment]
But it did happen on my phone?
