### ISSUE TITLE
Fix router path

### ISSUE THREAD

**Issue by pierrelstan** [Greenstand/treetracker-web-map-client#868]
When clicking on a single tree. The tree should display all the information about the tree.

**Comment by dadiorchen** [comment]
I think this happens on the top page, which means, on the top/home page, zoom in the map and then click a single tree

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/5744708/187340513-25df8ba6-2bc8-4d99-8171-ad866df13010.png">

**Comment by dadiorchen** [comment]
@pierrelstan I have solved this problem
