### ISSUE TITLE
TO check if we can set the initial view for org map

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#87]
Like this case: https://map.treetracker.org/?map_name=wscm
We need to check if the previous code is working to set the initial view for the organization map (map_name=xxx)
So we can consider using a good setting for it.

**Comment by dadiorchen** [comment]
To clarify, we need to adjust the config file to make this organization map looks good.

**Comment by mrtillman** [comment]
I don't understand.
What is the problem?
Is this a code change?

**Comment by dadiorchen** [comment]
@mrtillman this does not require coding, I'm not sure it's still valid, and I'd better freeze this issue for a while by taking it with `icebox`.
