### ISSUE TITLE
Add tree slider on the organization page

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#876]
Just like we did for the planter page (https://dev-k8s.treetracker.org/web-map-beta/demo/planters/940) , we should display the tree planted by the organization on the organization page. (https://dev-k8s.treetracker.org/web-map-beta/demo/organizations/178)

![Image](https://user-images.githubusercontent.com/5744708/187886647-207e5c7b-095c-4b4c-9e0d-3e7e6d301947.png)

**Comment by jeremydthomas** [comment]
@dadiorchen looks like Im going to have to wait for them to fix the api? https://github.com/Greenstand/treetracker-query-api/issues/173

**Comment by dadiorchen** [comment]
@jeremydthomas yes, and we just solved this problem, thank @mayankbucha
