### ISSUE TITLE
The mouse hovering behaves wrongly in this case

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#879]
on this page: https://dev-k8s.treetracker.org/web-map-beta/demo/top?bounds=38.973827362060554,-5.515930613039982,38.989276885986335,-5.50042427565408

The tree icon will get highlighted even the mouse is far away from the icon. 

![Image](https://user-images.githubusercontent.com/5744708/188075553-610f0fb8-7512-4501-87eb-5280844b20dd.png)

*Please check the video*

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-09-02%20at%202.44.22%20PM.mp4

**Comment by dadiorchen** [comment]
@kparikh9 do you remember how do you solve the similar problem? I feel the problem is that we solved the problem with the cluster icon, but the tree icon is still failing?

**Comment by kparikh9** [comment]
Hey @dadiorchen, yes you're right it looks like it might be having the same UTF-grid issue as with the cluster icons. You can follow [this PR](https://github.com/Greenstand/node-mapnik-1/pull/96) to solve the issue and upload a smaller icon file.

**Comment by dadiorchen** [comment]
@Mohmn did you set up the mapnik successfully? if true, this one is an easy one for you to get started the tile server part

**Comment by Mohmn** [comment]
Check ur slack @dadiorchen
