### ISSUE TITLE
Discusssion: how to deal with this problem:

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#88]
Karen Nicolas - Treetracker Liaison  9:28 PM
Hi. another point that would be super valueable... map.treetracker/?userid=3754.  When you go to this url and others like it, you see the tear drops first.  You have to zoom out to see the circle to know how many trees that farmer planted.  Viewers should see the total in the circle first because they may not know to zoom out and they will most importantly need that total tree count.

![image](https://user-images.githubusercontent.com/5744708/128288233-5c1bd880-3645-4cb3-863c-f37a535ea46f.png)

![image](https://user-images.githubusercontent.com/5744708/128288301-eea4af6d-ed10-4337-820b-7fb5797b65f7.png)

Or, we should consider solve this problem with `admin panel`?

**Comment by sebastiangaertner** [comment]
This is more of an admin panel request seeing the total cou r per planter is coming soon
--
Sent from myMail for Android Thursday, 05 August 2021, 06:54am +03:00 from Dadiorchen  ***@***.*** :

**Comment by dadiorchen** [comment]
Karen Nicolas - Treetracker Liaison  1 hour ago
Hi, I don't think it helps me with marketing farmer sponsorships to have it in the admin panel,  I need to show donors the farmer's trees they are sponsoring and they will want to see that total number of trees.  If its just in the admin panel, I don't think I will be able show that link to donors.
