### ISSUE TITLE
The organization user should be able to pick the initial map view for their map

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#890]
For a organization, they should be able to pick a location and zoom level (or a bounds with two corner locations on the map) as their initial  map view, so when user open the org's map, the map should jump to that location.

**Comment by dadiorchen** [comment]
@RubenSmn maybe picking the initial view by operating on the map directly is more friendly for people? What's your plan for this feature?

**Comment by RubenSmn** [comment]
That is exactly was I am planning to do. See #1122
