### ISSUE TITLE
Add Jest test (unit test) to CI

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#891]
We need to add the jest test as another part of the unit test to the CI checking, it should be run every time a new PR is raised. 

So we can protect some code: model, utiles, basically, they are code not concerning to the UI.

`npm run test`

**Comment by ar563** [comment]
We have Jest unit tests implemented in CI checking, it uses `npx jest --ci` in `pull-request-ci.yml` file.

**Comment by dadiorchen** [comment]
@ar563 thankyou!
