### ISSUE TITLE
Timeline button dark theme color incorrect

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#895]
## Description
The background color of the timeline button is not the same as the drawer

Mobile Screenshot (same on desktop) 
![image](https://user-images.githubusercontent.com/31519867/188425967-a5c1cab0-5270-4ba0-99f8-38350d7c837a.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by RubenSmn** [comment]
@dadiorchen what do you think about this? Change to the same color?

**Comment by dadiorchen** [comment]
Is it different? More dark for the timeline?

**Comment by RubenSmn** [comment]
Yes the button for the timeline is more dark

**Comment by RubenSmn** [comment]
On the drawer and the navbar we have a `background-image: linear-gradient(rgba(255, 255, 255, 0.09), rgba(255, 255, 255, 0.09))` which makes it lighter

**Comment by jeremydthomas** [comment]
The timeline Icon being darker than the rest of the theme does look a bit odd.
