### ISSUE TITLE
Vertical center icon/image in breadcrumbs

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-client#901]
# Description
Visiting the planter page: http://localhost:3000/planters/5449 or the wallet page: http://localhost:3000/wallets/ba95a148-7ff8-42bb-8028-99b747b86ae1
The icons/images are not centered vertically

## Screenshots
Wallet page
![image](https://user-images.githubusercontent.com/31519867/188605948-cd1a50b6-b67a-43e6-833c-4507445d4156.png)
Planter page
![image](https://user-images.githubusercontent.com/31519867/188606121-ec60b556-0c13-478f-a41f-f1b76633af57.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

**Comment by jeremydthomas** [comment]
@RubenSmn are you saying that you want the images/icons to be centered vertically to the words? For example lower the icon a bit so the middle of the icon lines up with the words, instead of the bottom of the icon lining up with the bottom of the words?

**Comment by RubenSmn** [comment]
@jeremydthomas yes I think the icons/images should be vertically centered of the text

**Comment by jeremydthomas** [comment]
@RubenSmn 
![image](https://user-images.githubusercontent.com/63400531/189518653-89415a9f-3e3e-4027-9efd-0c05a84042a0.png)

Something like that?

**Comment by jeremydthomas** [comment]
hmm the / is a bit off I think

**Comment by RubenSmn** [comment]
It looks better! Can you set a before/after side by side?

**Comment by jeremydthomas** [comment]
![image](https://user-images.githubusercontent.com/63400531/189520006-41bd7a34-3ad2-471f-a892-361f047b4695.png)
![image](https://user-images.githubusercontent.com/63400531/189519566-94a9696b-37bd-47e6-95a2-99a9ce61d116.png)


I THINK the top one looks better @RubenSmn , but my eyes are starting to trick me looking at the small pictures and adjusting things haha.

**Comment by RubenSmn** [comment]
Hahah I can imagine, yes the top one looks better!

**Comment by RubenSmn** [comment]
Closed with #935
