### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by jeremydthomas** [Greenstand/treetracker-web-map-client#939]
**Describe the bug**
When going to a link with the ?embed= true ( for example http://localhost:3000/planters/5449?embed=true, and http://localhost:3000/organizations/11?embed=true) we get the ReferenceError: document is not defined. 

**To Reproduce**
Go to http://localhost:3000/planters/5449?embed=true and http://localhost:3000/organizations/11?embed=true

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/63400531/189836580-4c56e6e8-20ae-427c-b923-9e0b9914d9a1.png)

**Comment by okdv** [comment]
Ah yea looks to be related to my issue from a few weeks ago, #813 
I'm gonna go ahead and take a look at these, i dont think i realized it was so prevalent
