### ISSUE TITLE
The next.js dev mode can not display the source code correctly

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#940]
The next.js should be able to display the source code rather than compiled bundle raw javascript code as shown below:

![Image](https://user-images.githubusercontent.com/5744708/189851351-46a5f07e-3997-484b-9837-92b966295947.png)

**Comment by keyy123** [comment]
@dadiorchen, What version of next.js does CWM use?

**Comment by keyy123** [comment]
@dadiorchen, I'll attempt this issue ticket

**Comment by keyy123** [comment]
I also noticed while testing it that this is web-map-core API that returns a minified code but when I make an error in one of the client side directories/files the error is properly linked to the sourcemap/original code. I look into ways to link source map of installed dependencies from other repos. 

Note: This may be an issue for web-map-core repo (worst case)

**Comment by dadiorchen** [comment]
@keyy123 which means we can close this issue now?

And let's continue the discussion of the honeybadger, it is something in our consideration too.

**Comment by dadiorchen** [comment]
Thanks for the analysis

**Comment by dadiorchen** [comment]
I think we just need to access source-map in development mode, it is good enough

**Comment by dadiorchen** [comment]
@keyy123 I hope you can raise some discussion in the #engerning channel, about the log tracing and monitoring, I did some research on Sentry https://sentry.io/ it seems the same role as honeybadger, also, the mobile team (android,ios) prefer to firebase (it has log tracing feature with free charge but I am sure they are real), but I wanted to unify all clients: web, native, node.js, maybe it is impossible, so maybe your experience on this can help us build the understanding on this.
