### ISSUE TITLE
The correct 500 page is flashing and then dispear

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#942]
To reproduce, open this page: https://dev-k8s.treetracker.org/web-map-beta/demo/trees/top
There was a correct 500 page show up, but immediately replaced by this :

![Image](https://user-images.githubusercontent.com/5744708/189859620-8d7f9e74-e75b-4a30-8a9a-f758895584cb.png)

**Comment by RubenSmn** [comment]
I changed this in the `[treeid].js`
```js
// throw e;
return {
  redirect: {
    destination: '/500',
    permanent: false,
  },
};
```
And it seems to be fixed

**Comment by dadiorchen** [comment]
@RubenSmn super! did you raise a PR

**Comment by RubenSmn** [comment]
I will in a bit!
