### ISSUE TITLE
The tree point is too huge?

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#943]
The tree icon seems too big? Even zoom into the maximum zoom level, it's hard to tell every single tree point from the icons. Should we consider improving the UX here? 

https://map.treetracker.org/?userid=3937&bounds=36.638806164264686,-3.205451921326484,36.64073735475541,-3.2043833937573076

Our version: 

![Image](https://user-images.githubusercontent.com/5744708/189873312-6e96fa81-b5b3-47a3-a98a-c1cc53af5bc6.png)

The online version:

![Image](https://user-images.githubusercontent.com/5744708/189873394-abc1ff46-a650-4c17-9035-d0a5417463b1.png)

**Comment by RubenSmn** [comment]
Maybe instead of the full white circle we could only use the tree icon

**Comment by jeremydthomas** [comment]
Thats a good idea, about the tree icon, however if we do that I think we should keep a small white outline like these red ones so they are still easy to see on the map. Otherwise the green icons over green grass or other green trees might be hard to see.

**Comment by dobinator** [comment]
I agree that the icon is too large. It is overwhelming to the user. I would reduce the white space and keep the green icon with smaller white border and background.

**Comment by dobinator** [comment]
It would still show up against the earth/ image.

**Comment by RubenSmn** [comment]
Something like this, without the black background : )

![bitmap](https://user-images.githubusercontent.com/31519867/190090495-cbcea255-7895-4f5c-912f-512001cb82d6.png)

**Comment by dadiorchen** [comment]
Actually for the tree icon, there are three status:
1. Default appreance
2. Highlighted, (by hovering the mouse)
3. Selected, (by clicking)

You can directly try it on the app here: https://prod-k8s.treetracker.org/web-map-beta/demo/planters/4735/trees/1630486
and the Figma defines it here: https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=2497%3A9770

**Comment by jeremydthomas** [comment]
Perhaps keep the big ones when you are zoomed way out, and when you start getting into the closer views start using the little ones.

**Comment by dadiorchen** [comment]
new design

<img width="425" alt="image" src="https://user-images.githubusercontent.com/5744708/193398819-5a01a683-5eb8-4079-b542-3b314961c507.png">
