### ISSUE TITLE
Tree page: species tag, `click to learn more`

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#953]
For species tag, add text at the third line (sub title) `click to learn more` and add the species_desc as the link.

Prerequisites: https://github.com/Greenstand/treetracker-query-api/issues/189

![Image](https://user-images.githubusercontent.com/5744708/190096206-55a42940-4674-4f02-b035-2d4f0e2f01ca.png)

**Comment by juliana-mol** [comment]
Can I work on this issue ?

**Comment by khalatevarun** [comment]
@dadiorchen @RubenSmn please review the PR, have fixed the issue.
