### ISSUE TITLE
Fullscreen: layout is incorrect

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#956]
![Image](https://user-images.githubusercontent.com/5744708/190106585-5eff11a4-fa92-4e18-97b4-879ac4532cb5.png)

As shown here, we need to scroll the page to see the buttons on the bottom, actually we need to be able to see them directly

https://prod-k8s.treetracker.org/web-map-beta/demo/planters/4788/trees/1707041?bounds=47.583847045898445,-19.163512306880474,47.59929656982422,-19.154756035599753

**Comment by Medmly20208** [comment]
is this issue still open?

**Comment by dadiorchen** [comment]
Yes, @Medmly20208 please help us on this if you want

**Comment by Medmly20208** [comment]
Yes of course I will work on it

**Comment by Medmly20208** [comment]
@dadiorchen 
![GreenStand](https://user-images.githubusercontent.com/69359301/190688990-59db19e7-bae9-49ce-96cf-330cf7858ebe.png)
are you talking about "meet Planter" Button

**Comment by dadiorchen** [comment]
See my explanation here: 
https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-09-17%20at%203.03.20%20PM.mp4

**Comment by Medmly20208** [comment]
understood thanks I will work on it immediately

**Comment by Medmly20208** [comment]
![treetrackererror](https://user-images.githubusercontent.com/69359301/190856671-bb526284-07cc-4871-97df-4d1efb8d0d32.png)
I have a problem with "npm run dev"  
I forked the repo and clone it then execute "npm i" but it throws this error 
and I don't now exactly the problem
