### ISSUE TITLE
On the default map, click tree will clean all data on map

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#968]
This just happens on the global map (without any filter, like planter, org)

![Image](https://user-images.githubusercontent.com/5744708/190516414-126076c6-3c20-47af-b510-4c2cde6fede9.png)

**Comment by okdv** [comment]
![image](https://user-images.githubusercontent.com/65867719/192642732-58442824-8561-4093-9d8f-a930121f9524.png)
I'm having trouble reproducing this one on my side, maybe there were issues with the prod db when you ran into this?

**Comment by dadiorchen** [comment]
I think this problem has been solved by some other PR
