### ISSUE TITLE
Improve the UX for `next` tree

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#976]
Currently, if we click next tree button, the next.js will load the data in ajax-like way, this is good to reduce the network traffic, but if the net condition is slow, the experience is not so good, the user don't know what's happening after clicking the button, see video below, maybe we should find a way to indicate the progress of loading, like the process bar on the top of the page or so?

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-09-21%20at%204.12.43%20PM.mp4

To reproduce: https://prod-k8s.treetracker.org/web-map-beta/demo/wallets/1f2a0862-66d1-4b42-8216-5a5cb9c6eca5/tokens?tree_id=95602

**Comment by dadiorchen** [comment]
Acutally, I think this is a common case on our site, for example, on the top page, click organization  Bôndy, and it takes dozens of seconds to open new page, but before that, the UI is doing nothing to let the user know what's happening.

**Comment by okdv** [comment]
Definitely seems to be a few approaches, we can just inject the loading indicator at the App level so it works for all page loads. I'd just say add a delay before we show the indicator so it doesnt try to pop up even when the page loads quickly. 

Could keep it really simple and use something like [nprogress](https://www.npmjs.com/package/nprogress)?

**Comment by dadiorchen** [comment]
@okdv good, if the mui component works for this, https://mui.com/material-ui/react-progress/#main-content I prefer to use it directly, but if it doesn't I am good to choose another lib, 

and also I found some discussion related: https://stackoverflow.com/questions/55624695/loading-screen-on-next-js-page-transition
