### ISSUE TITLE
Add tree slider to wallet page

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#980]
https://prod-k8s.treetracker.org/web-map-beta/demo/wallets/8de4ce55-f17c-41fe-9cc7-c21a47872405

![Image](https://user-images.githubusercontent.com/5744708/191462815-c1e50f74-9582-4554-be25-da6accd91680.png)

![Image](https://user-images.githubusercontent.com/5744708/191464043-63eb4afd-4d96-4148-8750-070492c02fed.png)

Just as we do on the planter page and organization page.

**Comment by jeremydthomas** [comment]
@dadiorchen can I reword that "wallet since October 08, 2021"
 to Wallet Created On, or Wallet Minted On? When I do this issue? It will read/flow better.

**Comment by dadiorchen** [comment]
Yes, @jeremydthomas please

**Comment by dadiorchen** [comment]
@jeremydthomas are you waiting for this API? https://dev-k8s.treetracker.org/query/trees?wallet_id=eecdf253-05b6-419a-8425-416a3e5fc9a0
It is implemented now.

**Comment by jeremydthomas** [comment]
Yes I was, thank you.
