### ISSUE TITLE
A error case: the tree id is 0

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#983]
When open this wallet and jump the this bounds, and click the tree icon, the id of the tree is 0 

http://localhost:3000/wallets/8de4ce55-f17c-41fe-9cc7-c21a47872405?bounds=-80.50781250000001,-27.215556209029675,46.05468750000001,35.02999636902566

![Image](https://user-images.githubusercontent.com/5744708/191471722-0d5a3e82-7201-4122-87b0-93bf46170be7.png)

**Comment by RubenSmn** [comment]
I am unable to see the wallet
![image](https://user-images.githubusercontent.com/31519867/191476167-dadece4e-c9ce-4ec3-9ab4-680895861259.png)

**Comment by dadiorchen** [comment]
@RubenSmn this is on prod db, you need to follow this to connect to prod: https://github.com/Greenstand/treetracker-web-map-client#how-to-connect-to-production-data-locally

**Comment by okdv** [comment]
from what I can tell, this is being returned by the map core, so web map client is working as designed at least. 

As far as what is causing this in the map core, im not sure at the moment...

heres an example of the grid for the trees in that bunch
https://tiles3.treetracker.org/12/1898/1952.grid.json?icon=ptk-s&wallet=dadiorchen

interestingly, if you zoom in further to narrow it to an individual tree, it returns the correct id 
https://tiles1.treetracker.org/16/30371/31237.grid.json?icon=ptk-s&wallet=dadiorchen
