### ISSUE TITLE
Planter page: broken layout

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#992]
https://prod-k8s.treetracker.org/web-map-beta/demo/planters/3939?keyword=undefined

The species component get distort because of long text

![Image](https://user-images.githubusercontent.com/5744708/191858432-41a0f344-c4d4-4c7c-8ba6-3a7e84c47e54.png)

**Comment by khalatevarun** [comment]
@RubenSmn please review the following PR, have tried fixing the issue.
https://github.com/Greenstand/treetracker-web-map-client/pull/1018
