### ISSUE TITLE
Mobile: can not click the title text to expand the drawer

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#993]
As shown below, we can not expand the drawer by clicking the text (red arrow on the left), we must click the black area on the right to do so.

![Image](https://user-images.githubusercontent.com/5744708/191858991-a494c348-8766-4918-be41-e22126f8bb0c.png)

**Comment by RubenSmn** [comment]
Same as #863
Will be fixed by #885

**Comment by dadiorchen** [comment]
Sorry for the duplication, I have merged that one
