### ISSUE TITLE
Mobile: a link doesn't work

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#995]
On the mobile device, can not click `meet the organization` to jump, but the same button works on desktop 

![Image](https://user-images.githubusercontent.com/5744708/191859939-dad481fb-4ebc-4d30-a1b5-16c5ecf1b9f0.png)

**Comment by dadiorchen** [comment]
Seem my wrong operation

**Comment by dadiorchen** [comment]
Still exists, and for the embed mode, the button doesn't work too
https://prod-k8s.treetracker.org/web-map-beta/demo/planters/3937?keyword=undefined

**Comment by RubenSmn** [comment]
@dadiorchen it does work, but the fetch for the organization is quite long:

http://localhost:3000/web-map-beta/demo/planters/3937
![image](https://user-images.githubusercontent.com/31519867/192136898-af0f9725-60dc-4a6b-bf2f-eb4901ae65bb.png)

http://localhost:3000/web-map-beta/demo/planters/3937?keyword=undefined
![image](https://user-images.githubusercontent.com/31519867/192136908-0fafdc41-432d-4f40-9dd4-1f644f9dcafd.png)

**Comment by dadiorchen** [comment]
@RubenSmn yes, I relized that later, I think we can do these to solve the problem:
1. Add the slow pages to pre-cache on next.js
2. Improve the UX mentioned here: https://github.com/Greenstand/treetracker-web-map-client/issues/976
