### ISSUE TITLE
Research: could we manually trigger the cache update for next.js

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-client#998]
Currently, we are going to use the next.js's cache to speed up the performance, and set an expiration time for that. Can we find a way to manually trigger some page's cache update so we can get the newest data immediately.

This is to bring convenience for our operator, usually, after doing some data management, they want to check the result on the map immediately, but with the cache of next.js, they need to wait.

**Comment by okdv** [comment]
On-demand revalidation should work in nextjs out of the box: https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#using-on-demand-revalidation

Basically they recommend creating an endpoint where we can supply a token and the path to revalidate, it'll purge the cache and force re-render on next call. Then we can just call this endpoint when/where needed. I'm happy to take a look and draft up a PR assuming all goes well

**Comment by dadiorchen** [comment]
Okay, great, then let's define this issue to test this next.js feature, and put the guiding document into our readme.

**Comment by okdv** [comment]
related to #1277

**Comment by dadiorchen** [comment]
Duplicated issue

**Comment by dadiorchen** [comment]
duplicated issue
